Repository hmcts/nfdiv-frontend, pull requests merged in 2020-12, with the labels that each got.

#16 Add steps system
  .eslintignore
  Dockerfile
  jest.config.js
  package.json
  sonar-project.properties
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/HomeController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/webpack/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/common/macros/csrf.njk
  src/main/steps/common/template.njk
  src/main/steps/common/webpack/css-template.njk
  src/main/steps/common/webpack/css.njk
  src/main/steps/common/webpack/js-template.njk
  src/main/steps/common/webpack/js.njk
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/error/error.njk
  src/main/steps/error/not-found.njk
  src/main/steps/first-page/first-page.content.ts
  src/main/steps/first-page/first-page.get.test.ts
  src/main/steps/first-page/first-page.get.ts
  src/main/steps/first-page/first-page.njk
  src/main/steps/first-page/first-page.post.test.ts
  src/main/steps/first-page/first-page.post.ts
  src/main/steps/home/home.content.ts
  src/main/steps/home/home.get.test.ts
  src/main/steps/home/home.get.ts
  src/main/steps/home/home.njk
  src/main/steps/urls.ts
  src/main/views/webpack/js-template.njk
  src/main/views/webpack/js.njk
  src/test/a11y/a11y.ts
  src/test/smoke/smoke.ts
  src/test/unit/app/controller/HomeController.ts
  src/test/unit/sample.ts
  src/test/unit/utils/mockRequest.ts
  tsconfig.json
  webpack/htmlWebpack.js
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-16

#18 Add form validation
  package.json
  sonar-project.properties
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/modules/awilix/index.ts
  src/main/steps/common/error/summary.njk
  src/main/steps/common/macros/csrf.njk
  src/main/steps/common/page.njk
  src/main/steps/common/template.njk
  src/main/steps/error/error.controller.ts
  src/main/steps/error/error.njk
  src/main/steps/error/not-found.njk
  src/main/steps/first-page/first-page.content.ts
  src/main/steps/first-page/first-page.form.ts
  src/main/steps/first-page/first-page.njk
  src/main/steps/first-page/first-page.post.test.ts
  src/main/steps/first-page/first-page.post.ts
  src/main/steps/home/home.njk
  src/test/a11y/a11y.ts
  tsconfig.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-18

#25 Add env syncing
  Jenkinsfile_CNP
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-25

#23 Nfdiv 200 state management
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/app/step/SessionStateStorage.ts
  src/main/app/step/StepStateStorage.ts
  src/main/modules/session/index.ts
  src/main/server.ts
  src/main/steps/first-page/first-page.content.ts
  src/main/steps/first-page/first-page.form.ts
  src/main/steps/first-page/first-page.get.test.ts
  src/main/steps/first-page/first-page.post.test.ts
  src/main/steps/first-page/first-page.post.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-23

#28 Change oauth-client-secret to idam-secret
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-28

#35 Add option and radio form fields, add language preference page
  sonar-project.properties
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/form/Form.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/session/index.ts
  src/main/routes.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/home/content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/home/template.njk
  src/main/steps/screen-questions/language-preference/content.ts
  src/main/steps/screen-questions/language-preference/form.ts
  src/main/steps/screen-questions/language-preference/get.test.ts
  src/main/steps/screen-questions/language-preference/get.ts
  src/main/steps/screen-questions/language-preference/post.test.ts
  src/main/steps/screen-questions/language-preference/post.ts
  src/main/steps/screen-questions/language-preference/template.njk
  src/main/steps/urls.ts
  tsconfig.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-35

#37 Add more pages
  src/main/app/form/Form.ts
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/steps/common/page.njk
  src/main/steps/screen-questions/has-marriage-broken/content.ts
  src/main/steps/screen-questions/has-marriage-broken/form.ts
  src/main/steps/screen-questions/has-marriage-broken/get.test.ts
  src/main/steps/screen-questions/has-marriage-broken/get.ts
  src/main/steps/screen-questions/has-marriage-broken/post.test.ts
  src/main/steps/screen-questions/has-marriage-broken/post.ts
  src/main/steps/screen-questions/has-marriage-broken/template.njk
  src/main/steps/screen-questions/language-preference/form.ts
  src/main/steps/screen-questions/language-preference/post.test.ts
  src/main/steps/screen-questions/language-preference/post.ts
  src/main/steps/screen-questions/marriage-certificate/content.ts
  src/main/steps/screen-questions/marriage-certificate/form.ts
  src/main/steps/screen-questions/marriage-certificate/get.test.ts
  src/main/steps/screen-questions/marriage-certificate/get.ts
  src/main/steps/screen-questions/marriage-certificate/post.test.ts
  src/main/steps/screen-questions/marriage-certificate/post.ts
  src/main/steps/screen-questions/marriage-certificate/template.njk
  src/main/steps/screen-questions/respondent-address/content.ts
  src/main/steps/screen-questions/respondent-address/form.ts
  src/main/steps/screen-questions/respondent-address/get.test.ts
  src/main/steps/screen-questions/respondent-address/get.ts
  src/main/steps/screen-questions/respondent-address/post.test.ts
  src/main/steps/screen-questions/respondent-address/post.ts
  src/main/steps/screen-questions/respondent-address/template.njk
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-37
