Repository hmcts/nfdiv-frontend, pull requests merged in 2021-02, with the labels that each got.

#130 feat(NFDIV-375): Cross browser testing
  .gitignore
  Jenkinsfile_nightly
  README.md
  package.json
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
  src/test/cross-browser/happy-path.test.ts
  src/test/cross-browser/steps.d.ts
  src/test/cross-browser/tsconfig.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-130

#134 feat: share gherkin feature steps between functional & cross browser tests
  .eslintignore
  .gitignore
  package.json
  src/test/cross-browser/codecept.conf.js
  src/test/cross-browser/codecept.conf.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/cross-browser/happy-path.test.ts
  src/test/functional/.eslintrc.js
  src/test/functional/codecept.conf.js
  src/test/functional/codecept.conf.ts
  src/test/functional/features/homepage.feature
  src/test/functional/puppeteer.config.ts
  src/test/functional/steps/homepage.ts
  src/test/functional/support/hooks.ts
  src/test/functional/support/scope.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/steps/homepage.ts
  src/test/steps/steps.d.ts
  src/test/tsconfig.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-134

#137 fix: Jenkins nightly build
  Jenkinsfile_nightly
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-137

#139 fix: JS initialisation error
  webpack/scss.js
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-139

#122 chore: use matching @types/node version for Node 12.x
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-122

#141 chore: log unhandled promise rejections
  src/main/modules/error-handler/index.ts
  src/main/server.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-141

#67 Nfdiv 296/terms and conditions
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/terms-and-conditions/content.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/terms-and-conditions/get.ts
  src/main/steps/terms-and-conditions/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/footer-links.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-67

#145 chore: redirect to first question after login
  src/main/modules/awilix/index.ts
  src/main/routes.ts
  src/main/steps/first-page/first-page.content.ts
  src/main/steps/first-page/first-page.get.test.ts
  src/main/steps/first-page/first-page.get.ts
  src/main/steps/first-page/first-page.njk
  src/main/steps/first-page/first-page.post.test.ts
  src/main/steps/first-page/first-page.post.ts
  src/main/steps/home/content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/home/template.njk
  src/main/steps/urls.ts
  src/test/smoke/smoke.ts
  src/test/steps/homepage.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-145

#146 fix: pa11y-tests & accessibility issues
  jest.a11y.config.js
  package.json
  src/main/steps/common/form/form.njk
  src/main/steps/screen-questions/has-marriage-broken/content.ts
  src/main/steps/screen-questions/language-preference/content.ts
  src/main/steps/screen-questions/marriage-certificate/content.ts
  src/main/steps/screen-questions/respondent-address/content.ts
  src/test/a11y/a11y.ts
  src/test/config.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/features/footer-links.feature
  src/test/functional/features/homepage.feature
  src/test/smoke/smoke.ts
  src/test/steps/homepage.ts
  src/test/tsconfig.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-146

#150 chore: removed unused devDependency + bump node 12 types
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-150

#156 Nfdiv 385/case created
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  jest.config.js
  jest.smoke.config.js
  src/main/modules/api/cos-api.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-156

#159 feat(NFDIV-431): new steps and navigation logic
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/modules/awilix/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/error/warning.njk
  src/main/steps/common/form/form.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/screen-questions/has-marriage-broken/content.ts
  src/main/steps/screen-questions/has-marriage-broken/get.test.ts
  src/main/steps/screen-questions/has-marriage-broken/get.ts
  src/main/steps/screen-questions/has-marriage-broken/post.test.ts
  src/main/steps/screen-questions/has-marriage-broken/post.ts
  src/main/steps/screen-questions/has-marriage-broken/template.njk
  src/main/steps/screen-questions/language-preference/content.ts
  src/main/steps/screen-questions/language-preference/get.test.ts
  src/main/steps/screen-questions/language-preference/get.ts
  src/main/steps/screen-questions/language-preference/post.test.ts
  src/main/steps/screen-questions/language-preference/post.ts
  src/main/steps/screen-questions/language-preference/template.njk
  src/main/steps/screen-questions/marriage-certificate/content.ts
  src/main/steps/screen-questions/marriage-certificate/get.test.ts
  src/main/steps/screen-questions/marriage-certificate/get.ts
  src/main/steps/screen-questions/marriage-certificate/post.test.ts
  src/main/steps/screen-questions/marriage-certificate/post.ts
  src/main/steps/screen-questions/respondent-address/content.ts
  src/main/steps/screen-questions/respondent-address/get.test.ts
  src/main/steps/screen-questions/respondent-address/get.ts
  src/main/steps/screen-questions/respondent-address/post.test.ts
  src/main/steps/screen-questions/respondent-address/post.ts
  src/main/steps/screen-questions/respondent-address/template.njk
  src/main/steps/sequence.test.ts
  src/main/steps/sequence.ts
  src/main/steps/sequence/has-relationship-broken/content.ts
  src/main/steps/sequence/marriage-certificate/content.ts
  src/main/steps/sequence/marriage-certificate/template.njk
  src/main/steps/sequence/relationship-not-broken/content.ts
  src/main/steps/sequence/relationship-not-broken/template.njk
  src/main/steps/sequence/template.njk
  src/main/steps/sequence/your-details/content.ts
  src/main/steps/terms-and-conditions/content.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/terms-and-conditions/get.ts
  src/main/steps/urls.ts
  src/test/steps/homepage.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-159

#175 feat(NFDIV-440): Added Save & sign out link with session storage update
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/step/SessionStateStorage.ts
  src/main/app/step/StepStateStorage.ts
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/session/index.ts
  src/main/routes.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/form.njk
  src/main/steps/urls.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-175

#174 Nfdiv 385/case created
  README.md
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  jest.config.js
  jest.smoke.config.js
  src/main/app/api/CosApi.test.ts
  src/main/app/api/CosApi.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-174

#179 feat(NFDIV-440): Send spouse to content + clear session on sign out
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/modules/oidc/index.ts
  src/main/modules/session/index.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/form.njk
  src/main/steps/sequence.ts
  src/main/steps/sequence/has-relationship-broken/content.ts
  src/main/steps/sequence/relationship-not-broken/content.ts
  src/main/steps/sequence/your-details/content.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-179

#187 feat(NFDIV-440): Added save & sign out exit page
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/modules/awilix/index.ts
  src/main/modules/oidc/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/save-sign-out/content.ts
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/save-sign-out/get.ts
  src/main/steps/save-sign-out/template.njk
  src/main/steps/urls.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-187

#190 feat(NFDIV-440): functional tests
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/codecept.conf.ts
  src/test/functional/features/footer-links.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/my-details-step.feature
  src/test/steps/common.ts
  src/test/steps/homepage.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-190

#69 Nfdiv 295/cookies page
  .github/dependabot.yml
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  src/main/assets/scss/main.scss
  src/main/modules/awilix/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/common/page.njk
  src/main/steps/cookies/content.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/cookies/get.ts
  src/main/steps/cookies/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/footer-links.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-69

#66 Nfdiv 294/accessibility statement
  src/main/modules/awilix/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/accessibility-statement/get.ts
  src/main/steps/accessibility-statement/template.njk
  src/main/steps/common/page.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/footer-links.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-66

#194 feat(NFDIV-369): Irretrievably broken down question
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/sequence/has-relationship-broken/content.ts
  src/main/steps/sequence/relationship-not-broken/content.ts
  src/main/steps/sequence/relationship-not-broken/template.njk
  src/main/steps/sequence/your-details/content.ts
  src/main/steps/urls.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/features/footer-links.feature
  src/test/functional/features/homepage.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-194

#192 feat(NFDIV-440): redirect to next incomplete step (handling sub steps)
  package.json
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/sequence.test.ts
  src/main/steps/sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-192

#201 feat(NFDIV-472): Hide back button on first question
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/steps/common/page.njk
  src/test/functional/features/your-details-step.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-201

#208 feat(NFDIV-369): Added functional & accessibility tests
  src/test/a11y/a11y.ts
  src/test/functional/features/homepage.feature
  src/test/functional/features/relationship-broken-down.feature
  src/test/functional/features/your-details-step.feature
  src/test/steps/common.ts
  src/test/steps/homepage.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-208

#191 Nfdiv 378/date formed
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/parser.test.ts
  src/main/app/form/parser.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/form.njk
  src/main/steps/index.test.ts
  src/main/steps/sequence.ts
  src/main/steps/sequence/relationship-date-less-than-year/content.ts
  src/main/steps/sequence/relationship-date/content.ts
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/relationship-broken-down.feature
  src/test/functional/features/relationship-date-formed.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-191

#203 Has certificate step
  src/main/steps/sequence.ts
  src/main/steps/sequence/has-certificate/content.ts
  src/main/steps/sequence/has-certificate/template.njk
  src/main/steps/sequence/has-no-certificate/content.ts
  src/main/steps/sequence/has-no-certificate/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/has-certificate-step.feature
  src/test/functional/features/relationship-date-formed.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-203

#61 Nfdiv 293 privacy statements
  src/main/modules/awilix/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/common/page.njk
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/privacy-policy/get.ts
  src/main/steps/privacy-policy/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/footer-links.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-61

#211 feat(NFDIV-474): Additional date validation
  src/main/app/form/Form.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/sequence/date-from-certificate/content.ts
  src/test/functional/features/relationship-date-formed.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-211

#209 feat: help with fees questions
  src/main/app/api/case.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields.njk
  src/main/steps/common/form/form.njk
  src/main/steps/sequence.ts
  src/main/steps/sequence/apply-for-help-with-fees/content.ts
  src/main/steps/sequence/apply-for-help-with-fees/template.njk
  src/main/steps/sequence/date-from-certificate/content.ts
  src/main/steps/sequence/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/sequence/help-with-your-fee/content.ts
  src/main/steps/sequence/help-with-your-fee/template.njk
  src/main/steps/sequence/irretrievable-breakdown/content.ts
  src/main/steps/sequence/template.njk
  src/main/steps/sequence/your-details/content.ts
  src/main/steps/urls.ts
  src/test/functional/features/has-certificate-step.feature
  src/test/functional/features/help-with-fee.feature
  src/test/functional/features/relationship-date-formed.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-209

#225 feat: test resiliency
  cucumber.js
  jest.a11y.config.js
  jest.smoke.config.js
  package.json
  src/main/modules/oidc/index.ts
  src/main/modules/session/index.ts
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/save-sign-out/get.ts
  src/main/steps/save-sign-out/template.njk
  src/test/a11y/a11y.ts
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/codecept.conf.ts
  src/test/functional/features/footer-links.feature
  src/test/functional/features/has-certificate-step.feature
  src/test/functional/features/help-with-fee.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/relationship-broken-down.feature
  src/test/functional/features/relationship-date-formed.feature
  src/test/functional/features/your-details-step.feature
  src/test/smoke/smoke.ts
  src/test/steps/common.ts
  src/test/steps/homepage.ts
  src/test/steps/steps.d.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-225

#226 fix: handle a service type switch
  src/main/app/api/to-api-format.test.ts
  src/main/app/api/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/test/functional/features/relationship-broken-down.feature
  src/test/functional/features/your-details-step.feature
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-226

#234 Undo case reset and throw error
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-234

#229 change api to case
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/home/get.test.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/sequence.ts
  src/main/steps/sequence/date-from-certificate/content.ts
  src/main/steps/sequence/do-you-have-your-certificate/content.ts
  src/main/steps/sequence/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/sequence/help-with-your-fee/content.ts
  src/main/steps/sequence/irretrievable-breakdown/content.ts
  src/main/steps/sequence/your-details/content.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-229

#235 Remove awilix
  package.json
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/PostController.ts
  src/main/modules/awilix/index.ts
  src/main/modules/error-handler/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/timeouts/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/test/unit/utils/mockRequest.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-235

#239 feat: save help with fees to the correct API fields
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/sequence/have-you-applied-for-help-with-fees/content.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-239

#241 fix: checkbox deselection
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/parser.test.ts
  src/main/app/form/parser.ts
  src/main/steps/common/form/fields.njk
  src/main/steps/common/form/form.njk
  src/main/steps/sequence/your-details/content.ts
  src/test/tsconfig.json
  tsconfig.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-241

#242 Refactor oidc
  src/main/app/auth/service/get-auth-token.test.ts
  src/main/app/auth/service/get-auth-token.ts
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CaseApi.ts
  src/main/app/controller/AppRequest.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-242

#227 fix: inferred petitioner/respondent gender
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/index.test.ts
  src/main/steps/sequence/check-answers/content.ts
  src/main/steps/sequence/your-details/content.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/relationship-broken-down.feature
  src/test/functional/features/your-details-step.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-227

#240 Add service auth provider client
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.aat.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/test.yaml
  package.json
  src/main/app/auth/service/get-auth-token.test.ts
  src/main/app/auth/service/get-auth-token.ts
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CaseApi.ts
  src/main/app/controller/AppRequest.ts
  src/main/modules/auth-provider/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/server.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-240

#247 Nfdiv 478 integrate ccd
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/aat.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/docker.yaml
  package.json
  src/main/app/auth/service/get-service-auth-token.test.ts
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/controller/AppRequest.ts
  src/main/modules/auth-provider/index.ts
  src/main/modules/oidc/index.ts
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/save-sign-out/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-247

#252 Add type definitions
  package.json
  src/main/app/case/CaseApi.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-252
