Repository hmcts/nfdiv-frontend, pull requests merged in 2021-05, with the labels that each got.

#526 Remove Claim Costs page and all references
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/apply-claim-costs/content.ts
  src/main/steps/apply-claim-costs/template.njk
  src/main/steps/check-your-answers/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/apply-claim-costs.feature
  src/test/functional/features/apply-for-financial-order.feature
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-526

#542 chore(NFDIV-608): Handle AddressGlobalUK field types
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-542

#547 Update ccd definition
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-547

#518 feat(NFDIV-305): Added upload documents page
  .gitignore
  config/default.yaml
  nodemon.assets.json
  nodemon.express.json
  package.json
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/DocumentManagementController.test.ts
  src/main/app/controller/DocumentManagementController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/document/DocumentManagementClient.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/document/__mocks__/DocumentManagementClient.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/assets/js/index.ts
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/UploadedFiles.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/upload-documents.scss
  src/main/modules/csrf/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/img/upload-arrow-icon.svg
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/common/form/fields/checkboxes.njk
  src/main/steps/common/form/form.njk
  src/main/steps/home/get.ts
  src/main/steps/sequence.ts
  src/main/steps/upload-your-documents/content.ts
  src/main/steps/upload-your-documents/template.njk
  src/main/steps/urls.ts
  src/test/functional/features/upload-your-documents.feature
  src/test/steps/happy-path.ts
  src/test/unit/utils/mockResponse.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-518

#541 feat(NFDIV-481): Welsh updates to not long enough page
  src/main/steps/common/common.content.ts
  src/main/steps/not-long-enough-to-apply/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-541

#537 content update
  src/main/steps/your-details/content.ts
  src/test/functional/features/check-your-answers.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-537

#535 content update
  src/main/steps/address-private/content.ts
  src/test/functional/features/address-private.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-535

#533 welsh content
  src/main/steps/your-names-on-certificate/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-533

#536 content update
  src/main/steps/apply-for-help-with-fees/content.ts
  src/main/steps/apply-for-help-with-fees/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-536

#534 welsh content
  src/main/steps/dividing-money-property/content.ts
  src/main/steps/how-did-you-change-your-name/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-534

#558 fix: new user first page regression
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-558

#559 Update ccd definition document types
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-559

#556 Added details of legal proceedings page
  src/main/app/case/case.ts
  src/main/steps/details-other-proceedings/content.ts
  src/main/steps/details-other-proceedings/template.njk
  src/main/steps/sequence.ts
  src/main/steps/upload-your-documents/content.ts
  src/main/steps/urls.ts
  src/test/functional/features/details-other-proceedings.feature
  src/test/functional/features/other-court-cases.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-556

#560 feat(NFDIV-519): Welsh "Were you both last habitually resident" page
  src/main/steps/habitually-resident-england-wales/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-560

#561 feat(NFDIV-619): Welsh "Other court cases" page
  src/main/steps/other-court-cases/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-561

#563 feat(NFDIV-617): Welsh "Do you have their address" page
  src/main/steps/do-you-have-address/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-563

#564 feat(NFDIV-622): Welsh "You need to get their address" page
  src/main/steps/common/common.content.ts
  src/main/steps/need-to-get-address/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-564

#572 feat(NFDIV-618): Welsh translations for "contact us"
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-572

#573 feat(NFDIV-624): Welsh translations for "Residual jurisdiction" page
  src/main/steps/are-you-eligible-for-residual-jurisdiction/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-573

#557 feat(NFDIV-656): Remove isInternational fields & use formatted AddressGlobalUK only
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/assets/js/address/links.ts
  src/main/assets/js/address/submit.ts
  src/main/assets/js/enter-address.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/enter-their-address/content.ts
  src/main/steps/enter-their-address/form.njk
  src/main/steps/enter-their-address/postcodeEnter.njk
  src/main/steps/enter-their-address/postcodeError.njk
  src/main/steps/enter-their-address/postcodeSelect.njk
  src/main/steps/enter-their-address/template.njk
  src/main/steps/enter-your-address/content.ts
  src/main/steps/enter-your-address/postcodeEnter.njk
  src/main/steps/enter-your-address/postcodeError.njk
  src/test/functional/features/their-address.feature
  src/test/functional/features/your-address.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-557

#578 disable autoscaling Update values.yaml
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-578

#576 chore: auto create/delete IDAM test users for functional tests
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
  src/test/functional/codecept.conf.ts
  src/test/steps/IdamUserManager.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-576

#581 Added document management url config so that correct url is set for all envs
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-581

#574 NFDIV-666 update fields
  README.md
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/Form.test.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/steps/common/common.content.ts
  src/main/steps/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/how-to-apply-to-serve/content.ts
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/template.njk
  src/main/steps/their-email-address/content.ts
  src/main/steps/you-can-use-english-welsh-courts/content.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-574

#562 feat(NFDIV-621): Welsh "Enter address" page
  src/main/steps/common/common.content.ts
  src/main/steps/enter-their-address/content.ts
  src/main/steps/enter-your-address/content.ts
  src/main/steps/enter-your-address/postcodeEnter.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-562

#579 feat(NFDIV-551): Welsh translations for "their email" page
  src/main/steps/their-email-address/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-579

#575 chore: added functional test for document upload & delete
  src/test/functional/features/upload-your-documents.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-575

#588 NFDIV 636 how do you want to apply page
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/how-do-you-want-to-apply/content.ts
  src/main/steps/how-do-you-want-to-apply/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/has-certificate-step.feature
  src/test/functional/features/how-do-you-want-to-apply.feature
  src/test/steps/happy-path.ts
  src/test/steps/jurisdiction.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-588

#595 chore: functional tests - set case directly from fixtures
  package.json
  src/test/functional/codecept.conf.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
  src/test/functional/features/check-your-answers.feature
  src/test/functional/features/living-in-england-wales-six-months.feature
  src/test/functional/features/living-in-england-wales-twelve-months.feature
  src/test/functional/fixtures/completeCase.ts
  src/test/steps/check-your-answers.ts
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
  src/test/steps/jurisdiction.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-595

#597 NFDIV-666: Rename partner to applicant 2 in relevant locations
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/steps/address-private/content.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/dividing-money-property/content.ts
  src/main/steps/do-you-have-address/content.ts
  src/main/steps/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/enter-their-address/content.ts
  src/main/steps/enter-their-name/content.ts
  src/main/steps/how-do-you-want-to-apply/content.ts
  src/main/steps/how-the-court-will-contact-you/content.ts
  src/main/steps/how-to-apply-financial-order/content.ts
  src/main/steps/other-court-cases/content.ts
  src/main/steps/sequence.ts
  src/main/steps/their-email-address/content.ts
  src/main/steps/where-your-lives-are-based/content.ts
  src/main/steps/you-can-use-english-welsh-courts/content.ts
  src/main/steps/you-need-your-certificate/content.ts
  src/main/steps/your-domicile/content.ts
  src/main/steps/your-names-on-certificate/content.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-597

#603 chore(NFDIV-666): Refactor your/their to applicant
  src/main/app/case/case.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/Form.test.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/assets/js/enter-address.ts
  src/main/steps/address-private/content.ts
  src/main/steps/changes-to-your-name/content.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/do-you-have-address/content.ts
  src/main/steps/enter-their-address/content.ts
  src/main/steps/enter-their-name/content.ts
  src/main/steps/enter-your-address/content.ts
  src/main/steps/enter-your-address/postcodeSelect.njk
  src/main/steps/enter-your-name/content.ts
  src/main/steps/habitually-resident-england-wales/content.ts
  src/main/steps/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/help-with-your-fee/content.ts
  src/main/steps/how-did-you-change-your-name/content.ts
  src/main/steps/how-the-court-will-contact-you/content.ts
  src/main/steps/living-england-wales-six-months/content.ts
  src/main/steps/living-england-wales-twelve-months/content.ts
  src/main/steps/sequence.ts
  src/main/steps/their-email-address/content.ts
  src/main/steps/upload-your-documents/content.ts
  src/main/steps/upload-your-documents/template.njk
  src/main/steps/where-your-lives-are-based/content.ts
  src/main/steps/your-domicile/content.ts
  src/main/steps/your-names-on-certificate/content.ts
  src/test/functional/fixtures/completeCase.ts
  src/test/steps/check-your-answers.ts
  src/test/steps/jurisdiction.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-603

#606 NFDIV-703 Update with new marriage fields
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-606

#607 Increase timeouts
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-607

#615 Increase initial mem
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-615

#617 fix: production node-ts memory usage
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-617

#596 chore(NFDIV-272): Irretrievable content update
  src/main/steps/irretrievable-breakdown/content.ts
  src/test/functional/features/union-broken-down.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-596

#618 NFDIV-714: Migrate new fields on Frontend
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-618

#590 feat(NFDIV-661): Prevent uploaded doc changes if state is not draft
  jest.config.js
  package.json
  src/global.d.ts
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/controller/DocumentManagementController.test.ts
  src/main/app/controller/DocumentManagementController.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/steps/common/common.content.ts
  src/main/steps/upload-your-documents/template.njk
  src/test/unit/utils/defaultViewArgs.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-590

#589 Nfdiv 504 connection summary
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/assets/js/go-back.ts
  src/main/steps/common/common.content.ts
  src/main/steps/connection-summary/content.ts
  src/main/steps/connection-summary/template.njk
  src/main/steps/enter-their-address/content.ts
  src/main/steps/need-to-get-address/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/you-can-use-english-welsh-courts/content.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
  src/test/functional/features/habitually-resident.feature
  src/test/functional/features/living-in-england-wales-six-months.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-589

#616 delay the active call for 2 minutes
  src/main/assets/js/session-timeout.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-616

#614 feat(NFDIV-638): "Application sent to your partner for review" page
  src/main/steps/application-sent-for-review/content.ts
  src/main/steps/application-sent-for-review/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-614

#608 Nfdiv 691 enter applicant2 email
  src/main/steps/common/common.content.ts
  src/main/steps/sequence.ts
  src/main/steps/their-email-address/content.ts
  src/main/steps/you-need-their-email-address/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-608

#625 fix: save & sign out + correctly detect if app is draft
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/test/functional/features/homepage.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-625

#640 rename events
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/controller/DocumentManagementController.test.ts
  src/main/app/controller/DocumentManagementController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-640

#623 feat(NFDIV-701): redirect to certificate names if joint application
  src/main/steps/sequence.ts
  src/test/functional/features/your-their-name.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-623

#619 update content
  src/main/steps/check-your-answers/content.ts
  src/main/steps/check-your-answers/form.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-619

#645 extend cookie expiration before saving session manually.
  src/main/assets/js/session-timeout.ts
  src/main/modules/session/index.ts
  src/main/routes.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-645

#624 update content
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/apply-for-help-with-fees/content.ts
  src/main/steps/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/sequence.ts
  src/test/functional/features/your-address.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-624
