Repository hmcts/nfdiv-frontend, pull requests merged in 2021-03, with the labels that each got.

#251 Nfdiv 446/447/448
  src/main/app/case/case.ts
  src/main/app/controller/GetController.ts
  src/main/steps/common/common.content.ts
  src/main/steps/sequence.ts
  src/main/steps/sequence/certificate-in-english/content.ts
  src/main/steps/sequence/certificate-in-english/template.njk
  src/main/steps/sequence/certified-translation/content.ts
  src/main/steps/sequence/certified-translation/template.njk
  src/main/steps/sequence/in-the-uk/content.ts
  src/main/steps/urls.ts
  src/test/functional/features/certificate-original.feature
  src/test/functional/features/help-with-fee.feature
  src/test/functional/features/relationship-in-the-uk.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-251

#238 Nfdiv 371 relationship not long enough
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/sequence.ts
  src/main/steps/sequence/less-than-year-together/content.ts
  src/main/steps/sequence/less-than-year-together/template.njk
  src/main/steps/sequence/not-long-enough-to-apply/content.ts
  src/main/steps/sequence/not-long-enough-to-apply/template.njk
  src/main/steps/urls.ts
  src/test/config.ts
  src/test/functional/features/relationship-date-formed.feature
  src/test/steps/common.ts
  src/test/steps/date.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-238

#275 fix my dumb mistake
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-275

#278 fix functional test
  src/test/functional/features/certificate-original.feature
  src/test/functional/features/relationship-in-the-uk.feature
  src/test/steps/date.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-278

#260 feat(NFDIV-306): Check answers page
  package.json
  src/main/app/case/answers/formatDate.test.ts
  src/main/app/case/answers/formatDate.ts
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/govUkNunjucksSummary.d.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/parser.test.ts
  src/main/app/form/parser.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/common/form/fields.njk
  src/main/steps/common/page.njk
  src/main/steps/cookies/get.test.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/sequence.ts
  src/main/steps/sequence/check-answers/content.ts
  src/main/steps/sequence/check-answers/template.njk
  src/main/steps/sequence/check-your-answers/content.ts
  src/main/steps/sequence/check-your-answers/template.njk
  src/main/steps/sequence/date-from-certificate/content.ts
  src/main/steps/sequence/your-details/content.ts
  src/main/steps/sequence/your-details/template.njk
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/urls.ts
  src/test/config.ts
  src/test/functional/features/check-your-answers.feature
  src/test/steps/common.ts
  src/test/unit/utils/defaultViewArgs.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-260

#279 fix: back button + reset tests changing session language
  jest.a11y.config.js
  jest.config.js
  jest.smoke.config.js
  nodemon.json
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/steps/sequence.ts
  src/test/functional/features/help-with-fee.feature
  src/test/functional/features/relationship-in-the-uk.feature
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-279

#281 feat(NFDIV-409): updated save/sign out text + refactored to remove cookie
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/steps/save-sign-out/content.ts
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/save-sign-out/get.ts
  src/main/steps/save-sign-out/post.test.ts
  src/main/steps/save-sign-out/post.ts
  src/main/steps/save-sign-out/template.njk
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/functional/features/homepage.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-281

#289 Nfdiv 419/get certified translation
  src/main/steps/sequence.ts
  src/main/steps/sequence/get-certified-translation/content.ts
  src/main/steps/sequence/get-certified-translation/template.njk
  src/main/steps/urls.ts
  src/test/functional/features/certificate-original.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-289

#286 welsh translation
  src/main/steps/common/common.content.ts
  src/main/steps/sequence/apply-for-help-with-fees/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-286

#284 feat(NFDIV-416): Welsh: Did you get married in the UK?
  src/main/steps/common/common.content.ts
  src/main/steps/sequence/do-you-have-your-certificate/content.ts
  src/main/steps/sequence/in-the-uk/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-284

#285 feat(NFDIV-417): Welsh: Is your original marriage certificate in English?
  src/main/steps/common/common.content.ts
  src/main/steps/sequence/certificate-in-english/content.ts
  src/main/steps/sequence/certified-translation/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-285

#283 feat(NFDIV-373): Welsh "You need your certificate" content
  src/main/steps/common/common.content.ts
  src/main/steps/sequence/you-need-your-certificate/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-283

#290 fix: sign in again link on error pages to trigger a logout
  src/main/steps/error/error.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-290

#282 Nfdiv 293/privacy policy content update
  src/main/steps/common/page.njk
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/privacy-policy/get.ts
  src/main/steps/privacy-policy/template.njk
  src/test/functional/features/certificate-original.feature
  src/test/steps/date.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-282

#297 Use types from API
  package.json
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/home/get.test.ts
  src/main/steps/index.test.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/save-sign-out/post.test.ts
  src/main/steps/sequence/your-details/content.ts
  src/test/unit/utils/mockResponse.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-297

#292 NFDIV-374: Implementation of welsh
  src/main/steps/sequence/have-you-applied-for-help-with-fees/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-292

#276 Session Timeout Task
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/assets/js/index.ts
  src/main/assets/js/session-timeout.ts
  src/main/modules/session/index.ts
  src/main/routes.ts
  src/main/steps/timed-out/content.ts
  src/main/steps/timed-out/get.test.ts
  src/main/steps/timed-out/get.ts
  src/main/steps/timed-out/template.njk
  src/main/steps/urls.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-276

#305 fix variable name
  src/main/steps/privacy-policy/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-305

#299 feat(NFDIV-427): Where did you get married
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/sequence.ts
  src/main/steps/sequence/country-and-place/content.ts
  src/main/steps/urls.ts
  src/test/functional/features/certificate-original.feature
  src/test/functional/features/country-and-place.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-299

#320 Add getAnswerRows to content
  src/main/modules/nunjucks/index.ts
  src/main/steps/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-320

#321 feat: updated copy for civil partnership dissolution title
  src/main/steps/common/common.content.ts
  src/test/functional/features/your-details-step.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-321

#316 chore: smoke test web apps dependencies before running functional tests
  src/test/smoke/smoke.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-316

#331 chore: added user case id comment & optional axios logging
  README.md
  package.json
  src/main/modules/axios-logger/index.ts
  src/main/server.ts
  src/main/steps/common/page.njk
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-331

#322 feat(NFDIV-428): Added session timeout Welsh translations
  package.json
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/assets/js/session-timeout.ts
  src/main/modules/i18n/index.ts
  src/main/steps/timed-out/content.ts
  src/main/steps/timed-out/get.test.ts
  src/main/steps/timed-out/get.ts
  src/test/unit/utils/defaultViewArgs.ts
  src/test/unit/utils/mockRequest.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-322

#308 fix: save & sign out get controller
  src/main/routes.ts
  src/main/steps/apply-for-help-with-fees/template.njk
  src/main/steps/get-certified-translation/template.njk
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/save-sign-out/get.ts
  src/main/steps/save-sign-out/post.test.ts
  src/main/steps/save-sign-out/post.ts
  src/main/steps/urls.ts
  src/main/steps/you-need-your-certificate/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-308

#315 feat(NFDIV-368): Added Welsh translations for your details
  src/main/steps/your-details/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-315

#336 Fix Jenkins nightly build
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-336

#330 Pain
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/apply-for-help-with-fees/content.ts
  src/main/steps/certificate-in-english/content.ts
  src/main/steps/certified-translation/content.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/cookies/content.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/country-and-place/content.ts
  src/main/steps/date-from-certificate/content.ts
  src/main/steps/do-you-have-your-certificate/content.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/get-certified-translation/content.ts
  src/main/steps/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/help-with-your-fee/content.ts
  src/main/steps/in-the-uk/content.ts
  src/main/steps/irretrievable-breakdown/content.ts
  src/main/steps/not-long-enough-to-apply/content.ts
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/relationship-not-broken/content.ts
  src/main/steps/save-sign-out/content.ts
  src/main/steps/save-sign-out/get.test.ts
  src/main/steps/save-sign-out/get.ts
  src/main/steps/save-sign-out/post.test.ts
  src/main/steps/save-sign-out/post.ts
  src/main/steps/terms-and-conditions/content.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/terms-and-conditions/get.ts
  src/main/steps/timed-out/content.ts
  src/main/steps/timed-out/get.test.ts
  src/main/steps/timed-out/get.ts
  src/main/steps/you-need-your-certificate/content.ts
  src/main/steps/your-details/content.ts
  src/test/unit/utils/defaultViewArgs.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-330

#337 feat: added docs on debugging functional tests
  README.md
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-337

#323 feat(NFDIV-510): Added check if you can get a divorce page
  src/main/steps/check-jurisdiction/content.ts
  src/main/steps/check-jurisdiction/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/check-jurisdiction.feature
  src/test/functional/features/country-and-place.feature
  src/test/functional/features/relationship-in-the-uk.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-323

#307 fix: omit unreachable questions from check your answers page
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/omitUnreachableAnswers.test.ts
  src/main/app/case/answers/omitUnreachableAnswers.ts
  src/main/app/form/Form.ts
  src/main/app/form/parser.ts
  src/test/config.ts
  src/test/functional/features/check-your-answers.feature
  src/test/functional/features/country-and-place.feature
  src/test/functional/features/homepage.feature
  src/test/steps/check-your-answers.ts
  src/test/steps/common.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-307

#346 README.md update for zsh terminal on older MacOS systems.
  README.md
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-346

#340 feat(NFDIV-493): Added Where are your lives based question
  src/main/app/case/case.ts
  src/main/app/form/Form.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/certificate-in-english/content.ts
  src/main/steps/certified-translation/content.ts
  src/main/steps/common/form/fields.njk
  src/main/steps/date-from-certificate/content.ts
  src/main/steps/do-you-have-your-certificate/content.ts
  src/main/steps/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/help-with-your-fee/content.ts
  src/main/steps/in-the-uk/content.ts
  src/main/steps/irretrievable-breakdown/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/where-your-lives-are-based/content.ts
  src/main/steps/your-details/content.ts
  src/test/functional/features/check-jurisdiction.feature
  src/test/functional/features/country-and-place.feature
  src/test/functional/features/relationship-in-the-uk.feature
  src/test/functional/features/where-your-lives-are-based.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-340

#344 Nfdiv 497
  src/main/app/case/case.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/habitually-resident-england-wales/content.ts
  src/main/steps/habitually-resident-england-wales/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/habitually-resident.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-344

#345 Add save and close event
  package.json
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/routes.ts
  src/main/steps/save-sign-out/post.test.ts
  src/main/steps/save-sign-out/post.ts
  src/test/unit/utils/mockRequest.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-345

#341 Nfdiv 495 living england wales twelve months
  src/main/app/case/case.ts
  src/main/steps/jurisdiction/interstitial/content.ts
  src/main/steps/jurisdiction/interstitial/template.njk
  src/main/steps/living-england-wales-twelve-months/content.ts
  src/main/steps/sequence.ts
  src/main/steps/your-domicile/content.ts
  src/test/functional/features/habitually-resident.feature
  src/test/functional/features/living-in-england-wales-twelve-months.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-341

#371 Increased Redis connection timeout as suggested by MS best practice doc
  src/main/modules/session/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-371

#339 Nfdiv 500/living in england walse six months
  src/main/app/case/case.ts
  src/main/steps/english-welsh-courts/content.ts
  src/main/steps/living-england-wales-six-months/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/living-in-england-walse-six-months.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-339

#351 Nfdiv 300
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/common/common.content.ts
  src/main/steps/english-or-welsh/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/language-preference.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-351

#372 feat(NFDIV-487): Allow users to have one divorce & one civil dissolution case
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-372

#354 feat(NFDIV-496): Added your domicile question
  src/main/app/case/case.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/your-domicile/content.ts
  src/main/steps/your-domicile/template.njk
  src/test/functional/features/habitually-resident.feature
  src/test/functional/features/your-domicile.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-354

#352 feat(NFDIV-486): Welsh version of Where did you get married
  src/main/steps/country-and-place/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-352

#318 feat(NFDIV-427): Added Where did you get married fields
  src/main/app/case/case.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-318

#361 fix: enable nightly smoke tests
  Jenkinsfile_nightly
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-361

#365 chore: refactored steps with content
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/routes.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-365

#355 Nfdiv 494 interstitial template
  src/main/assets/js/go-back.ts
  src/main/steps/english-welsh-courts/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
  src/test/functional/features/living-in-england-walse-six-months.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-355

#353 feat(NFDIV-530): null unreachable answers
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-353

#378 feat(NDIV-250): Added how courts will contact you page
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields.njk
  src/main/steps/cookies/get.test.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/how-the-court-will-contact-you/content.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/sequence.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/timed-out/get.test.ts
  src/main/steps/urls.ts
  src/test/functional/features/how-the-court-will-contact-you.feature
  src/test/unit/utils/defaultViewArgs.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-378

#392 fix: handle triggerEvent errors on sign out
  src/main/app/controller/PostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-392

#386 Nfdiv 515 get connection
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.ts
  src/main/routes.ts
  src/main/steps/index.ts
  src/main/steps/jurisdiction/interstitial/connections.test.ts
  src/main/steps/jurisdiction/interstitial/connections.ts
  src/main/steps/jurisdiction/interstitial/post.test.ts
  src/main/steps/jurisdiction/interstitial/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-386

#375 Nfdiv 422
  src/main/app/case/case.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/common/common.content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/your-names-on-certificate/content.ts
  src/main/steps/your-names-on-certificate/template.njk
  src/test/functional/features/your-names-on-certificate.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-375

#417 rename all the things
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.test.ts
  src/main/steps/certificate-in-english/content.ts
  src/main/steps/certified-translation/content.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/country-and-place/content.ts
  src/main/steps/do-you-have-your-certificate/content.ts
  src/main/steps/habitually-resident-england-wales/content.ts
  src/main/steps/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/help-with-your-fee/content.ts
  src/main/steps/in-the-uk/content.ts
  src/main/steps/index.test.ts
  src/main/steps/irretrievable-breakdown/content.ts
  src/main/steps/jurisdiction/interstitial/connections.test.ts
  src/main/steps/jurisdiction/interstitial/post.test.ts
  src/main/steps/living-england-wales-six-months/content.ts
  src/main/steps/living-england-wales-twelve-months/content.ts
  src/main/steps/sequence.ts
  src/main/steps/where-your-lives-are-based/content.ts
  src/main/steps/your-domicile/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-417

#412 Nfdiv 499 no jurisdiction
  src/main/assets/js/go-back.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/you-may-not-be-able-to-england-and-wales/content.ts
  src/main/steps/you-may-not-be-able-to-england-and-wales/template.njk
  src/test/functional/features/habitually-resident.feature
  src/test/functional/features/may-not-be-able-to-england-and-wales.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-412

#419 Allow custom controllers for steps
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/app/jurisdiction/JurisdictionPostController.ts
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/routes.ts
  src/main/steps/habitually-resident-england-wales/post.ts
  src/main/steps/index.ts
  src/main/steps/jurisdiction/interstitial/post.ts
  src/main/steps/living-england-wales-six-months/post.ts
  src/main/steps/living-england-wales-twelve-months/post.ts
  src/main/steps/where-your-lives-are-based/post.ts
  src/main/steps/your-domicile/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-419

#387 cant not apply in england or wales
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/you-cannot-apply/content.ts
  src/main/steps/you-cannot-apply/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-387

#422 chore: set @typescript-eslint/no-shadow to error
  .eslintrc.js
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/form/Form.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-422

#413 Nfdiv 424 changes to your name
  src/main/app/case/case.ts
  src/main/steps/changes-to-your-name/content.ts
  src/main/steps/common/form/fields.njk
  src/main/steps/date-from-certificate/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/changes-to-your-name.feature
  src/test/functional/features/your-names-on-certificate.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-413
