Repository hmcts/nfdiv-frontend, pull requests merged in 2021-04, with the labels that each got.

#400 Nfdiv 425
  src/main/app/case/case.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/how-did-you-change-your-name/content.ts
  src/main/steps/sequence.ts
  src/test/functional/features/how-did-you-change-your-name.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-400

#418 Nfdiv 265 keep address private
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/address-private/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/address-private.feature
  src/test/functional/features/language-preference.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-418

#434 chore: handle multiple errors being caught
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-434

#433 chore: added service health checks
  src/main/modules/health/index.ts
  src/main/modules/session/index.ts
  src/main/server.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-433

#447 bump version
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-447

#431 feat(NFDIV-509): You can use English or Welsh courts interstitial page
  src/main/app/controller/GetController.test.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/cookies/get.test.ts
  src/main/steps/jurisdiction/interstitial/content.ts
  src/main/steps/jurisdiction/interstitial/post.ts
  src/main/steps/jurisdiction/interstitial/template.njk
  src/main/steps/sequence.ts
  src/main/steps/timed-out/template.njk
  src/main/steps/urls.ts
  src/main/steps/you-can-use-english-welsh-courts/content.ts
  src/main/steps/you-can-use-english-welsh-courts/post.ts
  src/main/steps/you-can-use-english-welsh-courts/template.njk
  src/test/config.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
  src/test/functional/features/habitually-resident.feature
  src/test/functional/features/living-in-england-wales-six-months.feature
  src/test/functional/features/living-in-england-wales-twelve-months.feature
  src/test/functional/features/where-your-lives-are-based.feature
  src/test/functional/features/your-domicile.feature
  src/test/steps/jurisdiction.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-431

#437 feat(NFDIV-536): Added "How to apply to serve" page
  src/main/app/case/case.ts
  src/main/steps/common/common.content.ts
  src/main/steps/how-to-apply-to-serve/content.ts
  src/main/steps/how-to-apply-to-serve/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/how-to-apply-to-serve.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-437

#432 NFDIV-520: Welsh content for jurisdiction pages
  src/main/steps/living-england-wales-six-months/content.ts
  src/main/steps/where-your-lives-are-based/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-432

#423 Nfdiv 432
  package.json
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/sequence.ts
  src/main/steps/their-email-address/content.ts
  src/main/steps/their-email-address/template.njk
  src/main/steps/urls.ts
  src/test/functional/features/address-private.feature
  src/test/functional/features/their-email-address.feature
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-423

#436 Nfdiv 249 do you have address
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/common/common.content.ts
  src/main/steps/do-you-have-address/content.ts
  src/main/steps/do-you-have-address/template.njk
  src/main/steps/sequence.ts
  src/main/steps/their-email-address/content.ts
  src/main/steps/urls.ts
  src/test/functional/features/do-you-have-address.feature
  src/test/functional/features/their-email-address.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-436

#453 fix: handlle missing session data when service-auth-token errors
  src/main/steps/common/common.content.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-453

#451 translation
  src/main/steps/check-jurisdiction/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-451

#452 translations
  src/main/steps/living-england-wales-twelve-months/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-452

#446 Nfdiv 302
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/parser.test.ts
  src/main/app/form/parser.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/date-from-certificate/content.ts
  src/main/steps/how-the-court-will-contact-you/content.ts
  src/main/steps/other-court-cases/content.ts
  src/main/steps/other-court-cases/template.njk
  src/main/steps/sequence.ts
  src/main/steps/their-email-address/content.ts
  src/main/steps/urls.ts
  src/main/steps/your-details/content.ts
  src/test/functional/features/other-court-cases.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-446

#435 feat(NFDIV-453): Added "You need to get their address page"
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/Form.ts
  src/main/app/form/parser.test.ts
  src/main/app/form/parser.ts
  src/main/steps/address-private/content.ts
  src/main/steps/common/form/fields/checkboxes.njk
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/need-to-get-address/content.ts
  src/main/steps/need-to-get-address/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/need-to-get-address.feature
  src/test/functional/features/your-details.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-435

#460 Nfdiv 521
  src/main/steps/your-domicile/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-460

#465 NFDIV-522: Welsh content for /english-or-welsh
  src/main/steps/common/common.content.ts
  src/main/steps/english-or-welsh/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-465

#457 feat(NFDIV-498): Residual jurisdiction flow, copy & tests
  src/main/app/jurisdiction/connections.ts
  src/main/steps/are-you-eligible-for-residual-jurisdiction/content.ts
  src/main/steps/are-you-eligible-for-residual-jurisdiction/post.ts
  src/main/steps/check-jurisdiction/template.njk
  src/main/steps/common/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/you-can-use-english-welsh-courts/content.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
  src/test/functional/features/habitually-resident.feature
  src/test/functional/features/residual-jurisdiction.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-457

#458 Nfdiv 304 apply claim costs
  src/main/app/case/case.ts
  src/main/steps/apply-claim-costs/content.ts
  src/main/steps/apply-claim-costs/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/apply-claim-costs.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-458

#459 Nfdiv 297
  src/main/assets/scss/contact-us.scss
  src/main/assets/scss/main.scss
  src/main/steps/check-your-answers/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us.njk
  src/main/steps/common/page.njk
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-459

#481 fix: show residual jurisdiction screen if applicant is based based in England or Wales and everything else is no
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/steps/sequence.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
  src/test/functional/features/habitually-resident.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-481

#480 chore: switch to a mainstream OTP library
  package.json
  src/main/app/auth/service/get-service-auth-token.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-480

#486 feat(NFDIV-541): Added financial order pages/questions & functional tests
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/dividing-money-property/content.ts
  src/main/steps/dividing-money-property/template.njk
  src/main/steps/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/do-you-want-to-apply-financial-order/template.njk
  src/main/steps/how-to-apply-financial-order/content.ts
  src/main/steps/how-to-apply-financial-order/template.njk
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/apply-for-financial-order.feature
  src/test/functional/features/other-court-cases.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-486

#470 feat(NFDIV-557): Check your answers prayer & truth confirmation
  README.md
  package.json
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/check-your-answers/form.njk
  src/main/steps/check-your-answers/template.njk
  src/main/steps/common/form/fields/hidden.njk
  src/main/steps/common/form/fields/input.njk
  src/main/steps/index.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/main/steps/you-can-use-english-welsh-courts/content.ts
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/features/check-your-answers.feature
  src/test/functional/features/their-address.feature
  src/test/functional/features/your-address.feature
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-470

#487 feat(NFDIV-562): Enter your & their names
  src/main/app/case/case.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/enter-their-name/content.ts
  src/main/steps/enter-your-name/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/your-their-name.feature
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-487

#503 welsh content
  src/main/steps/you-may-not-be-able-to-england-and-wales/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-503

#502 Nfdiv 246 pay your fee
  src/main/steps/check-your-answers/template.njk
  src/main/steps/pay-your-fee/content.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/features/check-your-answers.feature
  src/test/functional/features/pay-your-fee.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-502

#506 612
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/steps/you-can-use-english-welsh-courts/content.ts
  src/test/functional/features/can-use-english-or-welsh-courts.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-506

#514 WIP: change e2e config
  src/test/functional/codecept.conf.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-514

#507 content update
  src/main/steps/are-you-eligible-for-residual-jurisdiction/content.ts
  src/main/steps/are-you-eligible-for-residual-jurisdiction/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-507
