Repository hmcts/nfdiv-frontend, pull requests merged in 2021-11, with the labels that each got.

#1393 applicant 1 sole and joint e2e sequence
  src/main/steps/applicant1/connection-summary/content.ts
  src/test/functional/features/address-private.feature
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/application-ended.feature
  src/test/functional/features/application-submitted.feature
  src/test/functional/features/apply-for-financial-order.feature
  src/test/functional/features/certificate-original.feature
  src/test/functional/features/changes-to-your-name.feature
  src/test/functional/features/check-jurisdiction.feature
  src/test/functional/features/check-your-answers.feature
  src/test/functional/features/confirm-your-joint-application.feature
  src/test/functional/features/country-and-place.feature
  src/test/functional/features/details-other-proceedings.feature
  src/test/functional/features/do-you-have-address.feature
  src/test/functional/features/footer-links.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/features/habitually-resident.feature
  src/test/functional/features/has-certificate-step.feature
  src/test/functional/features/help-with-fee.feature
  src/test/functional/features/how-did-you-change-your-name.feature
  src/test/functional/features/how-do-you-want-to-apply.feature
  src/test/functional/features/how-the-court-will-contact-you.feature
  src/test/functional/features/how-to-apply-financial-order.feature
  src/test/functional/features/how-to-apply-to-serve.feature
  src/test/functional/features/joint-application-sent-for-review.feature
  src/test/functional/features/joint-check-your-answers.feature
  src/test/functional/features/language-preference.feature
  src/test/functional/features/need-to-get-address.feature
  src/test/functional/features/other-court-cases.feature
  src/test/functional/features/pay-your-fee.feature
  src/test/functional/features/respondent.feature
  src/test/functional/features/their-address.feature
  src/test/functional/features/their-email-address.feature
  src/test/functional/features/union-broken-down.feature
  src/test/functional/features/union-date-formed.feature
  src/test/functional/features/union-in-the-uk.feature
  src/test/functional/features/upload-your-documents.feature
  src/test/functional/features/your-address.feature
  src/test/functional/features/your-details.feature
  src/test/functional/features/your-names-on-certificate.feature
  src/test/functional/features/your-their-name.feature
  src/test/functional/fixtures/jointApplicant2CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1393

#1336 NFDIV-1191 Alternate service page
  config/default.yaml
  src/main/steps/applicant1/how-you-can-proceed/content.ts
  src/main/steps/applicant1/how-you-can-proceed/template.njk
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/how-you-can-proceed.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1336

#1400 clean up
  src/main/steps/applicant1/hub-page/sole/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1400

#1402 Fix date and content on how you can proceed page
  src/main/steps/applicant1/how-you-can-proceed/content.ts
  src/main/steps/applicant1/how-you-can-proceed/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1402

#1412 fix idam user
  src/test/steps/IdamUserManager.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1412

#1408 NFDIV-1029 Add response pdf to hub page
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1408

#1426 raise FE mem Update values.yaml
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1426

#1416 Dependabot/npm and yarn/eslint plugin jest 25.2.3
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1416

#1418 Alternative unreachable answers
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1418

#1437 updating definition and field change
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1437

#1417 Add respondent answers pdf to hub page in pendingDispute state
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/test/functional/fixtures/completeCaseWithHWF.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1417

#1371 Nfdiv 1259 amend contact details page
  src/main/steps/applicant1/address-private/post.ts
  src/main/steps/applicant1/check-contact-details/content.ts
  src/main/steps/applicant1/check-contact-details/template.njk
  src/main/steps/applicant1/check-phone-number/content.ts
  src/main/steps/applicant1/check-phone-number/post.test.ts
  src/main/steps/applicant1/check-phone-number/post.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant1/enter-your-address/post.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/address-private/post.ts
  src/main/steps/applicant2/check-contact-details/content.ts
  src/main/steps/applicant2/check-contact-details/template.njk
  src/main/steps/applicant2/check-phone-number/content.ts
  src/main/steps/applicant2/check-phone-number/post.ts
  src/main/steps/applicant2/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant2/enter-your-address/post.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/index.ts
  src/main/steps/respondent/address-private/content.ts
  src/main/steps/respondent/address-private/post.ts
  src/main/steps/respondent/check-contact-details/content.ts
  src/main/steps/respondent/check-contact-details/template.njk
  src/main/steps/respondent/check-phone-number/content.ts
  src/main/steps/respondent/check-phone-number/post.ts
  src/main/steps/respondent/enter-your-address/content.ts
  src/main/steps/respondent/enter-your-address/post.ts
  src/main/steps/respondent/enter-your-address/template.njk
  src/main/steps/respondentSequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant2.feature
  src/test/functional/features/update-contact-details.feature
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1371

#1446 make userCase compulsory
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/controller/GetController.test.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/application-ended/get.test.ts
  src/main/steps/applicant1/application-sent-for-review/content.ts
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/connection-summary/content.ts
  src/main/steps/applicant1/country-and-place/content.ts
  src/main/steps/applicant1/do-you-have-address/content.ts
  src/main/steps/applicant1/how-to-apply-to-serve/content.ts
  src/main/steps/applicant1/how-you-can-proceed/content.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/applicant2/enter-your-access-code/get.test.ts
  src/main/steps/applicant2/needs-to-confirm-joint-application/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/respondent/disputing-the-application/content.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1446

#1447 Try to run the app without ts-node
  .eslintignore
  .gitignore
  Dockerfile
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  package.json
  src/main/routes.ts
  src/main/steps/index.ts
  tsconfig.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1447

#1450 Fix form failures nightly tests
  src/test/functional/features/form-failures.feature
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1450

#1451 Nfdiv 1286
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/form.njk
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/connection-summary/content.ts
  src/main/steps/applicant1/connection-summary/template.njk
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/applicant2/confirm-your-joint-application/content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/template.njk
  src/test/functional/features/applicant2.feature
  src/test/functional/features/switch-to-sole-application.feature
Labels: enhancement, ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1451

#1452 fix state-redirect error
  src/main/modules/state-redirect/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1452

#1460 Fix nighty tests after content update
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1460

#1459 Fix preview app insights
  charts/nfdiv-frontend/values.preview.template.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1459

#1462 show all residences under what it means
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/connection-summary/content.ts
Labels: bug, ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1462

#1467 Switch back out of docker containers for functional tests
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1467

#1461 Enable code coverage
  sonar-project.properties
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1461

#1468 NFDIV-1423
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1468

#1474 try coverage again
  sonar-project.properties
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1474

#1477 Add code coverage
  sonar-project.properties
  src/main/app/case/to-api-format.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1477

#1478 NFDIV-1428: Add app2 email to form data passed when linking applicant
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/case/case.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1478

#1479 Map disputeApplication tohowToRespondApplication
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1479

#1476 Fix jurisdiction fields
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/app/jurisdiction/JurisdictionPostController.ts
  src/main/steps/applicant1/connection-summary/content.ts
  src/main/steps/applicant1/connection-summary/template.njk
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1476

#1466 nfdiv-771 app2 switch to sole
  src/main/steps/applicant1/switch-to-sole-application/post.test.ts
  src/main/steps/applicant1/switch-to-sole-application/post.ts
  src/test/functional/features/switch-to-sole-application.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1466

#1485 Fix jurisdiction fields
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1485

#1470 Nfdiv 1346
  config/default.yaml
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1470

#1487 add showInSection for some question.
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1487

#1490 Fix residual jurisdiction field
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1490

#1486 Redirect to pay and submit page in awaitingPayment state
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1486

#1494 Fix nextStep url for access code errors and add f-test
  src/main/app/access-code/AccessCodePostController.ts
  src/test/functional/features/switch-to-sole-application.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1494

#1480 allow document upload for all 3 initial states.
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant2/upload-your-documents/template.njk
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1480

#1500 Fix document upload state
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1500

#1504 update states for allowing delete
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1504

#1475 remove custom get for CYA
  src/main/steps/applicant1/check-your-answers/get.ts
  src/test/functional/fixtures/completeCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1475

#1505 Hide the document UUID from the delete url
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/assets/js/upload-manager/UploadedFiles.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant2/upload-your-documents/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1505
