Repository hmcts/nfdiv-frontend, pull requests merged in 2021-06, with the labels that each got.

#660 fix save and close email issue
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/possibleAnswers.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-660

#678 NFDIV-676 Welsh translation - How to apply to serve
  src/main/app/case/definition.ts
  src/main/steps/how-to-apply-to-serve/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-678

#690 rename gender fields
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-690

#686 NFDIV-696
  src/main/app/case/case.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/app/invite-applicant2/InviteApplicant2PostController.test.ts
  src/main/app/invite-applicant2/InviteApplicant2PostController.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/check-your-answers/joint-form.njk
  src/main/steps/check-your-answers/post.ts
  src/main/steps/check-your-answers/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/sequence.ts
  src/test/functional/features/joint-check-your-answers.feature
  src/test/steps/check-your-answers.ts
  src/test/steps/jurisdiction.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-686

#703 NFDIV-696: Fix conditional rendering on CYA
  src/main/steps/check-your-answers/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-703

#710 fix: when functional tests leave case in an undoable state
  src/test/config.ts
  src/test/functional/features/joint-check-your-answers.feature
  src/test/steps/IdamUserManager.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-710

#653 feat(NFDIV-680): Payment
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/docker.yaml
  jest.config.js
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/controller/DocumentManagementController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/validation.ts
  src/main/app/invite-applicant2/InviteApplicant2PostController.test.ts
  src/main/app/invite-applicant2/InviteApplicant2PostController.ts
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/app/payment/PaymentModel.test.ts
  src/main/app/payment/PaymentModel.ts
  src/main/app/payment/__mocks__/PaymentClient.ts
  src/main/assets/js/go-back.ts
  src/main/modules/axios-logger/index.ts
  src/main/modules/state-redirect/index.ts
  src/main/server.ts
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/template.njk
  src/main/steps/check-your-answers/post.test.ts
  src/main/steps/check-your-answers/post.ts
  src/main/steps/check-your-answers/template.njk
  src/main/steps/index.ts
  src/main/steps/pay-your-fee/post.test.ts
  src/main/steps/pay-your-fee/post.ts
  src/main/steps/payment-callback/get.test.ts
  src/main/steps/payment-callback/get.ts
  src/main/steps/sequence.ts
  src/main/steps/urls.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/features/check-your-answers.feature
  src/test/functional/features/pay-your-fee.feature
  src/test/functional/fixtures/completeCase.ts
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
  src/test/unit/mocks/hmcts/nodejs-logging.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-653

#714 fix: nightly cross browser tests
  package.json
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
  src/test/functional/codecept.conf.ts
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-714

#712 feat(NFDIV-694): Welsh copy for enter your/their international address
  src/main/steps/common/common.content.ts
  src/main/steps/enter-their-address/content.ts
  src/main/steps/enter-your-address/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-712

#716 feat(NFDIV-548): Welsh translations for "Changes to your name" page
  src/main/steps/changes-to-your-name/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-716

#715 feat(NFDIV-698): Welsh translations for "Upload your documents" page
  src/main/steps/common/common.content.ts
  src/main/steps/upload-your-documents/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-715

#705 Nfdiv 273
  package.json
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/assets/scss/application-submitted.scss
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/sequence.ts
  src/test/functional/features/application-submitted.feature
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-705

#722 NFDIV-696: Fix casing on Send for review button
  src/main/steps/check-your-answers/content.ts
  src/test/functional/features/joint-check-your-answers.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-722

#721 Nfdiv 806
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-721

#717 feat(NFDIV-802): Allow address entry with no JS
  src/main/assets/js/enter-address.ts
  src/main/steps/enter-their-address/content.ts
  src/main/steps/enter-your-address/content.ts
  src/main/steps/enter-your-address/postcodeEnter.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-717

#719 feat(NFDIV-802): Allow document upload with no JS
  package.json
  src/main/app/controller/DocumentManagementController.test.ts
  src/main/app/controller/DocumentManagementController.ts
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/common/common.content.ts
  src/main/steps/upload-your-documents/template.njk
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-719

#736 fix: functional tests when postcode service is unavailable
  src/test/config.ts
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/features/application-submitted.feature
  src/test/functional/features/their-address.feature
  src/test/functional/features/your-address.feature
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
  src/test/steps/postcode.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-736

#737 chore: move 3rd party functional tests to nightly build
  src/test/functional/features/application-submitted.feature
  src/test/functional/features/check-your-answers.feature
  src/test/functional/features/pay-your-fee.feature
  src/test/functional/features/their-address.feature
  src/test/functional/features/upload-your-documents.feature
  src/test/functional/features/your-address.feature
  src/test/functional/fixtures/completeCaseWithHWF.ts
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-737

#738 fix: test from mutating user state
  src/test/functional/features/enter-your-access-code.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-738

#728 fix: screen reader accessibility
  src/main/assets/js/address/submit.ts
  src/main/assets/js/selectors.ts
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/assets/scss/main.scss
  src/main/steps/common/form/fields/checkboxes.njk
  src/main/steps/common/form/fields/date.njk
  src/main/steps/common/form/fields/input.njk
  src/main/steps/common/form/fields/option.njk
  src/main/steps/common/form/fields/radios.njk
  src/main/steps/common/form/fields/textarea.njk
  src/main/steps/enter-your-address/form.njk
  src/main/steps/enter-your-address/postcodeEnter.njk
  src/main/steps/enter-your-address/postcodeError.njk
  src/main/steps/enter-your-address/postcodeSelect.njk
  src/main/steps/upload-your-documents/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-728

#739 Tidy up
  sonar-project.properties
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/formatter/uploaded-files.test.ts
  src/main/app/case/formatter/uploaded-files.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/app/postcode/postcode-lookup.test.ts
  src/main/app/postcode/postcode-lookup.ts
  src/main/routes.ts
  src/main/steps/postcode-lookup/post.test.ts
  src/main/steps/postcode-lookup/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-739

#747 fix: postcode lookup endpoint + added functional test stubs
  config/default.yaml
  src/main/app/postcode/postcode-lookup.test.ts
  src/main/app/postcode/postcode-lookup.ts
  src/main/steps/postcode-lookup/post.test.ts
  src/main/steps/postcode-lookup/post.ts
  src/test/functional/features/their-address.feature
  src/test/functional/features/your-address.feature
  src/test/steps/postcode.ts
  src/test/unit/utils/mockPostcodeResponses.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-747

#746 NFDIV-752: Create get ccd case role endpoint client
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/case-roles.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-746

#745 NFDIV-689 Add redirect url for applicant 2 login
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/modules/oidc/index.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-745

#729 NFDIV-786 Other court cases content update
  src/main/steps/other-court-cases/content.ts
  src/main/steps/other-court-cases/template.njk
  src/test/functional/features/other-court-cases.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-729

#727 feat(NFDIV-752): Added applicant 2 has relationship broken down
  sonar-project.properties
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case-roles.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/AppRequest.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/irretrievable-breakdown/content.ts
  src/main/steps/applicant2/you-need-to-review-your-application/content.ts
  src/main/steps/applicant2/you-need-to-review-your-application/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/check-your-answers/content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/urls.ts
  src/main/steps/your-details/template.njk
  src/test/functional/features/joint-check-your-answers.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-727

#756 Fix joint app being sent for review before completed
  src/main/steps/check-your-answers/template.njk
  src/test/functional/features/joint-check-your-answers.feature
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-756

#759 NFDIV-719: Add functional tests for you need to review page
  src/test/config.ts
  src/test/functional/features/you-need-to-review-your-application.feature
  src/test/steps/you-need-to-review-your-application.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-759

#761 feat(NFDIV-752): Functional tests for broken union
  src/test/config.ts
  src/test/functional/features/applicant2/union-broken-down.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-761

#763 Update lastNameChangedWhenMarried field name
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-763

#768 NFDIV-961
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-768

#731 feat(NFDIV-749): Added applicant 2 enter your name
  src/main/modules/oidc/index.ts
  src/main/steps/applicant2/enter-your-name/content.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant2/your-name.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-731

#772 NFDIV-743: Use case reference passed to trigger event
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-772

#765 NFDIV-755 & NFDIV-778
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/post.test.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/post.ts
  src/main/steps/applicant1/how-the-court-will-contact-you/content.ts
  src/main/steps/applicant2/address-private/content.ts
  src/main/steps/applicant2/how-the-court-will-contact-you/content.ts
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/enter-your-access-code.feature
  src/test/functional/features/applicant2/how-the-court-will-contact-you.feature
  src/test/functional/features/applicant2/you-need-to-review-your-application.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-765

#757 feat: added test postcode lookup API request to the nightly build
  src/test/functional/features/your-address.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-757

#780 NFDIV-778: Add feature tests for applicant 2 address private page
  src/test/functional/features/applicant2/address-private.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-780

#778 fix: enter access code redirect & tests
  src/main/modules/oidc/index.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/enter-your-access-code/content.ts
  src/main/steps/applicant2/enter-your-access-code/post.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/index.test.ts
  src/test/a11y/a11y.ts
  src/test/config.ts
  src/test/functional/features/applicant2/enter-your-access-code.feature
  src/test/functional/features/apply-for-financial-order.feature
  src/test/steps/IdamUserManager.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-778

#781 NFDIV-689
  src/main/app/controller/GetController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-781

#790 NFDIV-966: Migrate new definition file
  charts/nfdiv-frontend/Chart.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-790

#767 feat(NFDIV-757): Added applicant 2 your address page
  src/main/steps/applicant2/enter-your-address/content.ts
  src/main/steps/applicant2/enter-your-address/template.njk
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/your-address.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-767
