Repository hmcts/nfdiv-frontend, pull requests merged in 2021-01, with the labels that each got.

#44 implementing validation
  package.json
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/modules/awilix/index.ts
  src/main/steps/common/error/summary.njk
  src/main/steps/first-page/first-page.content.ts
  src/main/steps/first-page/first-page.form.ts
  src/main/steps/first-page/first-page.post.test.ts
  src/main/steps/first-page/first-page.post.ts
  src/main/steps/home/get.test.ts
  src/main/steps/screen-questions/has-marriage-broken/content.ts
  src/main/steps/screen-questions/has-marriage-broken/form.ts
  src/main/steps/screen-questions/has-marriage-broken/get.test.ts
  src/main/steps/screen-questions/has-marriage-broken/post.test.ts
  src/main/steps/screen-questions/has-marriage-broken/post.ts
  src/main/steps/screen-questions/language-preference/content.ts
  src/main/steps/screen-questions/language-preference/form.ts
  src/main/steps/screen-questions/language-preference/get.test.ts
  src/main/steps/screen-questions/language-preference/post.test.ts
  src/main/steps/screen-questions/language-preference/post.ts
  src/main/steps/screen-questions/marriage-certificate/content.ts
  src/main/steps/screen-questions/marriage-certificate/form.ts
  src/main/steps/screen-questions/marriage-certificate/get.test.ts
  src/main/steps/screen-questions/marriage-certificate/post.test.ts
  src/main/steps/screen-questions/marriage-certificate/post.ts
  src/main/steps/screen-questions/respondent-address/content.ts
  src/main/steps/screen-questions/respondent-address/form.ts
  src/main/steps/screen-questions/respondent-address/get.test.ts
  src/main/steps/screen-questions/respondent-address/post.test.ts
  src/main/steps/screen-questions/respondent-address/post.ts
  src/main/utils/validation.test.ts
  src/main/utils/validation.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-44

#45 Csrftoken
  src/main/modules/csrf/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/error/csrf-token.njk
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-45

#58 Move validation under form
  src/main/app/form/Form.test.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/screen-questions/language-preference/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-58

#59 Add language toggle
  package.json
  src/main/assets/js/go-back.ts
  src/main/assets/js/index.ts
  src/main/assets/scss/banner.scss
  src/main/assets/scss/main.scss
  src/main/modules/helmet/index.ts
  src/main/modules/i18n/index.ts
  src/main/modules/session/index.ts
  src/main/server.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/test/functional/features/homepage.feature
  src/test/functional/steps/homepage.ts
  src/test/functional/utlis/puppeteer.util.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-59

#64 Idam setup
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.aat.template.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/modules/session/index.ts
  src/main/server.ts
  src/test/functional/features/homepage.feature
  src/test/functional/steps/homepage.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-64

#60 Add additional ingress host
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.aat.template.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/controller/GetController.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/home/template.njk
  src/test/functional/features/homepage.feature
  src/test/functional/steps/homepage.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-60

#70 FOR JON, ALWAYS
  src/main/assets/scss/header.scss
  src/main/assets/scss/main.scss
  src/main/modules/oidc/index.ts
  src/main/steps/common/page.njk
  src/test/functional/features/homepage.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-70

#87 disable idampr in aat preventing neuvector alerts
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.aat.template.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-87

#86 chore: removed unnecessary jquery dependency
  package.json
  src/main/assets/js/go-back.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-86

#93 Update packages
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-93

#79 chore: remove unused React extensions from config
  jest.a11y.config.js
  jest.config.js
  jest.smoke.config.js
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-79

#94 update preview domains
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/steps/home/content.ts
  src/main/steps/home/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-94

#81 Chore/refactor form
  src/main/steps/common/error/summary.njk
  src/main/steps/common/form/form.njk
  src/main/steps/common/page.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-81

#84 Chore/fix eslint warnings
  .eslintignore
  .eslintrc.js
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.ts
  src/main/modules/i18n/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/session/index.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/first-page/first-page.content.ts
  src/main/steps/first-page/first-page.post.test.ts
  src/main/steps/first-page/first-page.post.ts
  src/main/steps/screen-questions/has-marriage-broken/content.ts
  src/main/steps/screen-questions/has-marriage-broken/post.test.ts
  src/main/steps/screen-questions/has-marriage-broken/post.ts
  src/main/steps/screen-questions/language-preference/content.ts
  src/main/steps/screen-questions/language-preference/post.test.ts
  src/main/steps/screen-questions/language-preference/post.ts
  src/main/steps/screen-questions/marriage-certificate/content.ts
  src/main/steps/screen-questions/marriage-certificate/post.test.ts
  src/main/steps/screen-questions/marriage-certificate/post.ts
  src/main/steps/screen-questions/respondent-address/content.ts
  src/main/steps/screen-questions/respondent-address/post.test.ts
  src/main/steps/screen-questions/respondent-address/post.ts
  src/test/functional/steps/homepage.ts
  src/test/functional/utlis/puppeteer.util.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
  tsconfig.eslint.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-84

#106 update packages
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-106

#108 chore: reuse existing translations & remove unused file extension
  .eslintrc.js
  src/main/steps/home/content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/template.njk
  webpack.config.js
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-108

#95 chore: update readme dev setup
  README.md
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-95

#107 feat(NFDIV-379): handle 4xx, 5xx errors, timeouts, and asynchronous errors
  config/default.yaml
  package.json
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/modules/awilix/index.ts
  src/main/modules/csrf/index.ts
  src/main/modules/error-handler/index.ts
  src/main/modules/health/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/timeouts/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/error/content.ts
  src/main/steps/error/csrf-token.njk
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/error/error.njk
  src/main/steps/error/not-found.njk
  src/main/steps/home/get.test.ts
  src/test/unit/utils/mockRequest.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-107

#121 fix: version /info endpoint & transform regex
  .dockerignore
  jest.a11y.config.js
  jest.config.js
  jest.smoke.config.js
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-121

#124 chore: use ts-node-dev for faster reloads
  nodemon.json
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-124

#118 set appinsights to collect logs.
  src/main/modules/appinsights/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-118

#128 chore: removed unused dev dep sinon
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-128
