Repository hmcts/nfdiv-frontend, pull requests merged in 2021-07, with the labels that each got.

#789 NFDIV-550 address private - Welsh translation
  src/main/steps/applicant1/address-private/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-789

#809 Handle zero index months in Feature tests
  src/test/steps/date.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-809

#808 Fix partner title for app2
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/controller/GetController.ts
  src/main/steps/common/common.content.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-808

#798 NFDIV-976: Trigger app2 update if the user logged in isApplicant2
  charts/nfdiv-frontend/Chart.yaml
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-798

#812 remove password from repo
  Jenkinsfile_CNP
  src/test/a11y/a11y.ts
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-812

#764 Nfdiv 754 changes to your name joint app2
  src/main/steps/applicant2/changes-to-your-name/content.ts
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/changes-to-your-name.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-764

#813 NFDIV-719: Fix typo in content
  src/main/steps/applicant2/you-need-to-review-your-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-813

#792 chore: added testing process
  README.md
  TESTING.md
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-792

#791 url update
  src/main/steps/applicant2/you-cannot-apply/content.ts
  src/main/steps/applicant2/you-cannot-apply/template.njk
  src/main/steps/applicant2Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-791

#793 NFDIV-725: You have not confirmed your joint application page
  src/main/steps/applicant2/you-have-not-confirmed-joint-application/content.ts
  src/main/steps/applicant2/you-have-not-confirmed-joint-application/template.njk
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-793

#825 NFDIV-725: Update content to allow for civil partnership content to be rendered
  src/main/steps/applicant2/you-have-not-confirmed-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-825

#826 NFDIV-758
  src/main/steps/applicant2/needs-to-confirm-joint-application/content.ts
  src/main/steps/applicant2/needs-to-confirm-joint-application/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-826

#797 feat(NFDIV-796): Content updates to application sent for review page
  src/main/steps/applicant1/application-sent-for-review/content.ts
  src/main/steps/applicant1/application-sent-for-review/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-797

#856 NFDIV-758: Parse dueDate field
  src/main/app/case/from-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-856

#857 NFDIV-778
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant2/address-private/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-857

#861 NFDIV-982: Migrate latest definition into the frontend app
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-861

#862 Cookie banner
  package.json
  src/main/assets/js/cookie.ts
  src/main/assets/js/index.ts
  src/main/assets/scss/cookie-banner.scss
  src/main/assets/scss/main.scss
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/cookie-banner/template.njk
  src/main/steps/cookies/template.njk
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-862

#867 Use system user
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/modules/properties-volume/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-867

#863 NFDIV-964
  src/main/steps/applicant1/application-sent-for-review/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-863

#875 fix e2e locally
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/modules/properties-volume/index.ts
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-875

#810 NFDIV-793 app2 how to apply financial order page
  src/main/steps/applicant1/how-to-apply-financial-order/content.ts
  src/main/steps/applicant2/how-to-apply-financial-order/content.ts
  src/main/steps/applicant2/how-to-apply-financial-order/template.njk
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/apply-for-financial-order.feature
  src/test/functional/features/applicant2/how-to-apply-financial-order.feature
  src/test/functional/features/how-to-apply-financial-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-810

#794 feat(NFDIV-720): Added check your answers page for applicant 2
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/controller/Applicant2GetController.test.ts
  src/main/app/controller/Applicant2GetController.ts
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-answers/get.ts
  src/main/steps/applicant2/check-your-answers/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-794

#876 Configure getAllPossibleAnswers to include Applicant2 Sequence when application type is Joint
  src/main/app/case/answers/possibleAnswers.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/post.test.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-876

#880 update link applicant2 event name
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-880

#887 Add api parser for app 2 /how-the-court-will-contact-you page
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-887

#888 Add payment logging
  src/main/app/payment/PaymentClient.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-888

#881 Nfdiv 721
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/case/answers/govUkNunjucksSummary.d.ts
  src/main/app/case/case.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/applicant2/check-your-joint-application/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant2/check-your-joint-applicant.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-881

#890 attempt to fix cross browser tests
  Jenkinsfile_nightly
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-890

#899 Increase staging mem and CPU
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.aat.template.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-899

#900 NFDIV-987
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/english-or-welsh/content.ts
  src/main/steps/applicant2/english-or-welsh/content.ts
  src/main/steps/applicant2Sequence.ts
  src/test/config.ts
  src/test/functional/features/applicant2/english-or-welsh.feature
  src/test/functional/features/applicant2/how-the-court-will-contact-you.feature
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-900

#892 NFDIV-787
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/uploaded-files.test.ts
  src/main/app/case/formatter/uploaded-files.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant2/upload-your-documents/content.ts
  src/main/steps/applicant2/upload-your-documents/template.njk
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/upload-your-documents.feature
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
  src/test/unit/utils/defaultViewArgs.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-892

#909 NFDIV-787
  charts/nfdiv-frontend/Chart.yaml
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/steps/applicant2/upload-your-documents/content.ts
  src/test/functional/features/applicant2/upload-your-documents.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-909

#916 Make Jon happy
  src/main/app/case/case.ts
  src/main/steps/applicant2/irretrievable-breakdown/content.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/home/get.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-916

#919 update deps
  package.json
  src/main/modules/health/index.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-919

#922 NFDIV-787
  src/main/app/document/DocumentManagementController.test.ts
  src/main/assets/js/upload-manager/UploadedFiles.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/test/functional/features/applicant2/upload-your-documents.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-922

#924 quick fix for payment
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/test/functional/features/application-submitted.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-924

#925 NFDIV-787: Resolve redirect issues when uploading and deleting files
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-925

#923 NFDIV-987
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-923

#921 NFDIV-769
  src/main/steps/applicant2/your-comments-sent/content.ts
  src/main/steps/applicant2/your-comments-sent/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant2/check-your-joint-applicant.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-921

#908 NFDIV-988: Add applicant 2 other court cases page
  charts/nfdiv-frontend/Chart.yaml
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/other-court-cases/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/applicant2/other-court-cases/content.ts
  src/main/steps/applicant2/other-court-cases/template.njk
  src/main/steps/applicant2Sequence.ts
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-908

#788 NFDIV-753 app2 Changed name how page
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/Form.ts
  src/main/steps/applicant1/how-did-you-change-your-name/content.ts
  src/main/steps/applicant2/how-did-you-change-your-name/content.ts
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/how-did-you-change-your-name.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-788

#940 Fix bug and clean up
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/upload-your-documents.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-940

#942 Nightly fix
  src/test/functional/features/applicant2/upload-your-documents.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-942

#941 Fix nameChangeHow field
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-941

#945 NFDIV-787: Fix conditional statement text in Nunjucks template
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant2/upload-your-documents/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-945

#946 Update applicant prayer and sot fields
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/test/functional/fixtures/completeCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-946

#950 update chart
  charts/nfdiv-frontend/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-950
