Repository hmcts/nfdiv-frontend, pull requests merged in 2021-12, with the labels that each got.

#1510 Fix an issue where the index of uploadedFiles was incorrect
  src/main/app/controller/GetController.ts
  src/main/assets/js/upload-manager/UploadedFiles.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1510

#1507 Nfdiv-1474 fix and update states for sole hub page
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1507

#1512 back link loop fix.
  src/main/assets/js/go-back.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1512

#1511 Nfdiv 1311
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1511

#1513 Nfdiv 1415
  src/main/steps/applicant1/how-do-you-want-to-apply/post.test.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/post.ts
  src/test/functional/features/switch-to-sole-application.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1513

#1520 Fix for missing filename on no JS clients
  src/main/steps/applicant1/upload-your-documents/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1520

#1532 Clean up confirm joint app page
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1532

#1538 Update fields
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1538

#1550 NFDIV-1534: Add extra ccd id param and config checks
  src/main/steps/applicant1/equality/createToken.test.ts
  src/main/steps/applicant1/equality/createToken.ts
  src/main/steps/applicant1/equality/get.test.ts
  src/main/steps/applicant1/equality/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1550

#1551 NFDIV-1176
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/continue-with-your-application/content.ts
  src/main/steps/applicant1/continue-with-your-application/template.njk
  src/main/steps/applicant1/withdrawing-your-application/content.ts
  src/main/steps/applicant1/withdrawing-your-application/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1551

#1555 Remove saveBeforeSessionTimeout
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1555

#1543 change the way fixture data is imported to the case
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/test/config.ts
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
  src/test/steps/check-your-answers.ts
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
  src/test/steps/jurisdiction.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1543

#1562 only allow defined fields to be submitted in a form
  src/main/app/controller/PostController.test.ts
  src/main/app/form/Form.ts
  src/main/steps/applicant1/check-phone-number/post.test.ts
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/main/steps/applicant2/confirm-your-joint-application/post.test.ts
  src/main/steps/respondent/review-the-application/post.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1562

#1563 NFDIV-1204: Configure is info still correct page
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/continue-with-your-application/template.njk
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/template.njk
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1563

#1515 Nfdiv 1289
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/post.test.ts
  src/main/steps/applicant1/hub-page/post.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/form.njk
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/home/get.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1515

#1531 Nfdiv 995 joint hub page awaiting conditional order
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/form/Form.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/post.test.ts
  src/main/steps/applicant1/hub-page/post.ts
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant2/hub-page/form.njk
  src/main/steps/applicant2/hub-page/post.test.ts
  src/main/steps/applicant2/hub-page/post.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/test/functional/features/applicant2.feature
  src/test/functional/features/hub-page.feature
  src/test/functional/features/switch-to-sole-application.feature
  src/test/functional/features/update-contact-details.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1531

#1569 Fix certifiedTranslationField unsetting 2
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1569

#1571 Fix confirmReceipt field showing twice
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant2/hub-page/form.njk
  src/test/functional/features/hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1571

#1570 NFDIV-1569: Migrate changes to CO questions
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/continue-with-your-application/content.ts
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1570

#1572 clean up template
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1572

#1552 NFDIV 1173
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/applicant1/read-the-response/content.ts
  src/main/steps/applicant1/read-the-response/template.njk
  src/main/steps/applicant1Sequence.ts
  src/test/functional/features/applicant1-sole-conditional-order.feature
  src/test/functional/fixtures/respondentCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1552

#1557 Rewrite CYA pages
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/applicant2/check-your-joint-application/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/check-your-answers/content.ts
  src/main/steps/respondentSequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1557

#1564 NFDIV 1205
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/form.njk
  src/main/steps/applicant1/check-your-conditional-order-answers/post.test.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/post.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant1-sole-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1564

#1577 scss clean up on cya table
  src/main/assets/scss/check-your-answers.scss
  src/main/assets/scss/main.scss
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1577
