Repository hmcts/nfdiv-frontend, pull requests merged in 2021-09, with the labels that each got.

#1096 Fix text duplication in document upload widget
  src/main/assets/js/upload-manager/index.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant2/upload-your-documents/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1096

#1097 Add PCQ to crossbrowser tests
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1097

#1098 NFDIV-1138: Fix uploaded documents list on CYA page
  src/main/steps/applicant2/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1098

#1062 NFDIV-991-direct-to-hub-page-in-holding-state
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1062

#1102 NFDIV-1145 implementation
  src/main/assets/js/go-back.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/payment-callback/get.test.ts
  src/main/steps/applicant1/payment-callback/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1102

#1106 remove token from idam url
  src/main/modules/health/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1106

#1107 clean up e2e test
  src/test/config.ts
  src/test/steps/IdamUserManager.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1107

#1117 Fix app2 home get controller and clean up
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1117

#1119 clean up
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/main/steps/applicant1/check-your-answers/post.ts
  src/test/functional/features/applicant2/check-your-joint-applicant.feature
  src/test/steps/happy-path.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1119

#1118 Import the index.ts file from the nfdiv-case-api NFDIV-1144 ticket ch…
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1118

#1125 fix nightly e2e
  src/test/functional/features/help-with-fee.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1125

#1126 Remove unused AoS fields from ccd definition
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1126

#1127 NFDIV-1066
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case.ts
  src/main/steps/applicant1/equality/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1127

#1132 remove timer
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1132

#1134 add timer back and increase it to 30 secs
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1134

#1148 Fix idam cleanup script
  src/test/steps/IdamUserManager.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1148

#1146 Clean up how unanswerable questions are nulled
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/to-api-format.ts
  src/main/modules/oidc/index.ts
  src/main/steps/index.ts
  src/test/functional/features/confirm-your-joint-application.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1146

#1152 reduce number of checks for user role
  src/main/modules/oidc/index.ts
  src/main/steps/applicant2/enter-your-access-code/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1152

#1160 Update ccd definition ts file
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1160

#1147 NFDIV-770
  src/main/modules/oidc/index.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/application-ended/get.test.ts
  src/main/steps/applicant1/application-ended/get.ts
  src/main/steps/applicant1/no-response-yet/content.ts
  src/main/steps/applicant1/pay-and-submit/content.ts
  src/main/steps/applicant1/switch-to-sole-application/content.ts
  src/main/steps/applicant1/switch-to-sole-application/form.njk
  src/main/steps/applicant1/switch-to-sole-application/post.test.ts
  src/main/steps/applicant1/switch-to-sole-application/post.ts
  src/main/steps/applicant1/switch-to-sole-application/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/application-ended.feature
  src/test/functional/features/switch-to-sole-application.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1147

#1185 Nfdiv 1027
  src/main/assets/scss/hub-page.scss
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1185

#1191 clean up test
  src/test/functional/features/their-email-address.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1191

#1192 Allow user to have 2 cases
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1192

#1206 Fix pipeline
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1206

#1212 Change confidential address type
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1212

#1213 respondent login redirect/callback
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/steps/respondent/enter-your-access-code/content.ts
  src/main/steps/respondent/enter-your-access-code/get.test.ts
  src/main/steps/respondent/enter-your-access-code/get.ts
  src/main/steps/respondent/enter-your-access-code/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1213

#1220 Nfdiv-1212 Fix app2 HomeGetController
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/test/functional/fixtures/jointApplicant2CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1220

#1228 Make fees configurable
  config/default.yaml
  src/main/steps/applicant1/dividing-money-property/content.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant1/help-with-your-fee/content.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/content.ts
  src/main/steps/applicant1/how-to-apply-to-serve/content.ts
  src/main/steps/applicant1/need-to-get-address/content.ts
  src/main/steps/applicant1/pay-and-submit/content.ts
  src/main/steps/applicant1/pay-your-fee/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/applicant2/help-with-your-fee/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1228

#1153 Nfdiv 1010 hub page
  package.json
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/assets/scss/hub-page.scss
  src/main/assets/scss/main.scss
  src/main/modules/document-download/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/form.njk
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/post.test.ts
  src/main/steps/applicant1/hub-page/post.ts
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/hub-page/content.ts
  src/main/steps/applicant2/hub-page/form.njk
  src/main/steps/applicant2/hub-page/joint/hub.njk
  src/main/steps/applicant2/hub-page/post.test.ts
  src/main/steps/applicant2/hub-page/post.ts
  src/main/steps/applicant2/hub-page/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant2/hub-page.feature
  src/test/functional/features/hub-page.feature
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1153

#1230 fix date test
  src/test/steps/date.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1230

#1222 Nfdiv 1054/1052
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/index.ts
  src/main/steps/respondent/details-other-proceedings/content.ts
  src/main/steps/respondent/details-other-proceedings/template.njk
  src/main/steps/respondent/other-court-cases/content.ts
  src/main/steps/respondent/other-court-cases/template.njk
  src/main/steps/respondentSequence.ts
  src/test/functional/features/applicant2/hub-page.feature
  src/test/functional/features/hub-page.feature
  src/test/functional/features/respondent/other-court-cases.feature
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1222
