Repository hmcts/nfdiv-frontend, pull requests merged in 2021-10, with the labels that each got.

#1229 NFDIV-770
  charts/nfdiv-frontend/Chart.yaml
  src/main/steps/applicant1/application-ended/get.ts
  src/main/steps/applicant1/switch-to-sole-application/post.test.ts
  src/main/steps/applicant1/switch-to-sole-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1229

#1239 Hub page update
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1239

#1235 Nfdiv 1089
  src/main/steps/respondent/how-the-court-will-contact-you/content.ts
  src/main/steps/respondentSequence.ts
  src/test/functional/features/respondent/how-the-court-will-contact-you.feature
  src/test/functional/features/their-email-address.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1235

#1256 Remove more references to financial order for that result in an empty string
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1256

#1247 clean up content
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1247

#1257 Update content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1257

#1275 mega dep update
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1275

#1255 Update getAnswerRows.ts
  src/main/app/case/answers/getAnswerRows.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1255

#1291 Nfdiv 1087
  src/main/app/utils/get-connection-to-england-and-wales.ts
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant1/other-court-cases/template.njk
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/respondent/how-do-you-want-to-respond/template.njk
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/template.njk
  src/main/steps/respondentSequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/respondent/legal-jurisdiction-of-the-courts.feature
Labels: enhancement, ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1291

#1292 Fix respondent sequence
  src/main/steps/respondentSequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1292

#1295 use correct financial order change link
  src/main/steps/applicant1/check-your-answers/content.ts
  src/test/functional/features/check-your-answers.feature
  src/test/steps/check-your-answers.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1295

#1305 add welsh translation for "/application-sent-for-review" page
  src/main/steps/applicant1/application-sent-for-review/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1305

#1309 Update test content
  src/test/functional/features/has-certificate-step.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1309

#1326 Nfdiv 1092
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/steps/applicant1/check-your-answers/form.njk
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/check-your-answers/content.ts
  src/main/steps/respondent/check-your-answers/post.test.ts
  src/main/steps/respondent/check-your-answers/post.ts
  src/main/steps/respondent/check-your-answers/template.njk
  src/main/steps/respondentSequence.ts
  src/test/functional/fixtures/respondentCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1326

#1335 reset functional tests back to using chromium
  .nvmrc
  Dockerfile
  package.json
  src/test/config.ts
  src/test/functional/features/address-private.feature
  src/test/functional/features/applicant2/address-private.feature
  src/test/functional/features/applicant2/apply-for-financial-order.feature
  src/test/functional/features/applicant2/english-or-welsh.feature
  src/test/functional/features/applicant2/help-with-fee.feature
  src/test/functional/features/applicant2/how-did-you-change-your-name.feature
  src/test/functional/features/applicant2/how-to-apply-financial-order.feature
  src/test/functional/features/applicant2/union-broken-down.feature
  src/test/functional/features/applicant2/your-name.feature
  src/test/functional/features/certificate-original.feature
  src/test/functional/features/details-other-proceedings.feature
  src/test/functional/features/do-you-have-address.feature
  src/test/functional/features/footer-links.feature
  src/test/functional/features/has-certificate-step.feature
  src/test/functional/features/how-do-you-want-to-apply.feature
  src/test/functional/features/how-to-apply-to-serve.feature
  src/test/functional/features/language-preference.feature
  src/test/functional/features/respondent/english-or-welsh.feature
  src/test/functional/features/respondent/other-court-cases.feature
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1335

#1349 fix test after name change
  src/main/steps/respondent/disputing-the-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1349
