Repository hmcts/nfdiv-frontend, pull requests merged in 2021-08, with the labels that each got.

#966 fix e2e issue
  src/test/functional/features/applicant2/check-your-joint-applicant.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-966

#961 Update payment client
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/app/payment/PaymentModel.test.ts
  src/main/app/payment/PaymentModel.ts
  src/main/server.ts
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/applicant1/pay-your-fee/post.ts
  src/main/steps/applicant1/payment-callback/get.test.ts
  src/main/steps/applicant1/payment-callback/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-961

#957 NFDIV-750
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant2/help-with-your-fee/content.ts
  src/main/steps/applicant2/help-with-your-fee/template.njk
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/help-with-fee.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-957

#976 undo using pr url
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-976

#968 Fix jurisdiction on CYA page
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/connection-summary/content.ts
  src/main/steps/applicant1/connection-summary/post.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-968

#985 App2 hwf
  charts/nfdiv-frontend/Chart.yaml
  src/main/steps/applicant2/apply-for-help-with-fees/content.ts
  src/main/steps/applicant2/apply-for-help-with-fees/template.njk
  src/main/steps/applicant2/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/help-with-fee.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-985

#952 Rename field screenHasUnionBroken to applicant1ScreenHasUnionBroken
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/steps/applicant1/irretrievable-breakdown/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/irretrievable-breakdown/content.ts
  src/main/steps/index.test.ts
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
  src/test/steps/check-your-answers.ts
  src/test/steps/jurisdiction.ts
  src/test/steps/you-need-to-review-your-application.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-952

#993 NFDIV-975 direct app1 to confirmation page in app2approved state
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-993

#1004 upgrade deps
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1004

#992 removing tags
  src/main/steps/applicant1/check-your-answers/content.ts
  src/test/functional/features/pay-your-fee.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-992

#1006 NFDIV-1061 Make newest docs appear first
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1006

#1007 Update upload check to 60seconds
  src/test/functional/features/applicant2/upload-your-documents.feature
  src/test/functional/features/upload-your-documents.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1007

#1008 failed screenshot full screen
  src/test/functional/codecept.conf.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1008

#1010 E2e update
  src/test/functional/features/applicant2/upload-your-documents.feature
  src/test/functional/features/upload-your-documents.feature
  src/test/functional/features/your-address.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1010

#1012 better handling when under load
  package.json
  src/main/modules/too-busy/index.ts
  src/main/server.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1012

#1015 update definition file
  src/main/app/case/definition.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant2/do-you-want-to-apply-financial-order/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1015

#1019 HFW has no payment receipt
  src/main/steps/applicant1/application-submitted/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1019

#1029 Stop unsetting fields that we need
  src/main/app/case/answers/possibleAnswers.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1029

#1030 NFDIV-1105: Add dividing money property page to app2 journey
  src/main/steps/applicant2/dividing-money-property/content.ts
  src/main/steps/applicant2/dividing-money-property/template.njk
  src/main/steps/applicant2Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1030

#1034 Add confirmation page functional test
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/test/functional/features/applicant2/confirm-your-joint-application.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1034

#1038 Set default app2 name
  src/main/steps/applicant2/enter-your-access-code/post.test.ts
  src/main/steps/applicant2/enter-your-access-code/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1038

#1009 Nfdiv 723
  charts/nfdiv-frontend/Chart.yaml
  src/main/steps/applicant1/pay-and-submit/content.ts
  src/main/steps/applicant1/pay-and-submit/post.ts
  src/main/steps/applicant1/pay-and-submit/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1009

#1026 clean up
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1026

#1024 NFDIV-1066: Set up PCQ integration
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/applicant1/equality/PcqParameters.ts
  src/main/steps/applicant1/equality/content.ts
  src/main/steps/applicant1/equality/createToken.test.ts
  src/main/steps/applicant1/equality/createToken.ts
  src/main/steps/applicant1/equality/get.test.ts
  src/main/steps/applicant1/equality/get.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/equality.feature
  src/test/functional/features/upload-your-documents.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1024

#1046 NFDIV-1066
  src/main/steps/applicant1/equality/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1046

#1039 Update applicant 2 sequence
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2/apply-for-financial-order.feature
  src/test/functional/features/applicant2/how-to-apply-financial-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1039

#1025 submit joint application
  src/main/app/case/answers/possibleAnswers.ts
  src/main/steps/applicant1/confirm-your-joint-application/post.test.ts
  src/main/steps/applicant1/confirm-your-joint-application/post.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/confirm-your-joint-application/form.njk
  src/test/config.ts
  src/test/functional/features/confirm-your-joint-application.feature
  src/test/functional/features/where-your-lives-are-based.feature
  src/test/functional/fixtures/jointApplicant2CompleteCase.ts
  src/test/steps/IdamUserManager.ts
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1025

#1056 update deps
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1056

#1076 Import the index.ts file from the nfdiv-case-api NFDIV-1093 ticket ch…
  src/main/app/case/definition.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1076

#1063 update post controllers to consider save and sign out
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/applicant1/pay-your-fee/post.ts
  src/main/steps/applicant2/enter-your-access-code/post.test.ts
  src/main/steps/applicant2/enter-your-access-code/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1063

#1067 Fix dividing assets on confirmation page
  src/main/app/case/answers/getAnswerRows.test.ts
  src/main/app/case/answers/getAnswerRows.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant2Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1067

#1089 NFDIV-1138: Ensure all Applicant 2 answers are displayed on CYA page
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1089
