Repository hmcts/nfdiv-frontend, pull requests merged in 2022-08, with the labels that each got.

#2405 Add logging for old divorce redirect
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2405

#2411 Update access code logging
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2411

#2406 nfdiv-2585 Fix old divorce redirect
  src/main/app/case/case-api.test.ts
  src/main/app/case/case-api.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2406

#2413 Nfdiv-2648 Fix access code undefined issue
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/steps/applicant2/enter-your-access-code/get.test.ts
  src/main/steps/applicant2/enter-your-access-code/get.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2413

#2359 Nfdiv-2558 clear invalid data on save and sign out
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/post.ts
  src/main/steps/applicant1/your-details/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2359

#2424 Add logging for existing application page
  src/main/app/access-code/AccessCodePostController.ts
  src/main/steps/existing-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2424

#2420 Nfdiv 2614
  src/main/steps/applicant1/application-sent-for-review/content.ts
  src/main/steps/applicant1/email-resent/content.ts
  src/main/steps/applicant1/their-email-address/content.ts
  src/main/steps/applicant1/you-cannot-update-their-email/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2420

#2373 NFDIV-2545
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2373

#2433 clean up after NFDIV 2636 was implemented
  src/main/steps/applicant1Sequence.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2433

#2437 Update coDateAndTimeOfHearing format to fix e2e tests
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/sole-hub-page.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2437

#2171 nfdiv-2197: reinstate language preference question - DO NOT MERGE until all welsh tickets are done
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/common/page.njk
  src/main/steps/respondentSequence.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/respondent.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2171

#2393 Date translation
  src/main/app/case/answers/formatDate.test.ts
  src/main/app/case/answers/formatDate.ts
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/modules/i18n/index.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/applicant1/application-ended/get.test.ts
  src/main/steps/applicant1/application-sent-for-review/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/date-from-certificate/content.ts
  src/main/steps/applicant1/equality/createToken.test.ts
  src/main/steps/applicant1/equality/get.ts
  src/main/steps/applicant1/finalising-your-application/content.ts
  src/main/steps/applicant1/how-you-can-proceed/content.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant2/enter-your-access-code/get.test.ts
  src/main/steps/applicant2/needs-to-confirm-joint-application/content.ts
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/get.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/contact-us/get.test.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/existing-application/get.test.ts
  src/main/steps/no-response-yet/get.test.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/respondent/disputing-the-application/content.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/switch-to-sole-application/get.test.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/timed-out/get.test.ts
  src/test/steps/common.ts
  src/test/unit/utils/defaultViewArgs.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2393

#2407 NFDIV-2635
  src/main/steps/applicant1/details-other-proceedings/content.ts
  src/main/steps/applicant1/how-the-court-will-contact-you/content.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant2/details-other-proceedings/content.ts
  src/main/steps/applicant2/enter-your-access-code/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/check-your-answers/content.ts
  src/main/steps/respondent/disputing-the-application/content.ts
  src/main/steps/respondent/how-do-you-want-to-respond/content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2407

#2409 NFDIV-2639
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2409

#2410 NFDIV-2636
  src/main/steps/applicant1/need-to-get-address/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2410

#2432 nfdiv-2646: match applicant2Email also for invite search
  src/main/app/case/case-api-client.ts
  src/main/app/case/case-api.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2432

#2452 Fix crossbrowser tests
  src/main/app/controller/GetController.ts
  src/main/steps/save-sign-out/get.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/respondent.feature
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2452

#2455 increase login timeout
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2455

#2417 NFDIV-2655 - Add welsh cookie banner content
  src/main/steps/applicant1/hub-page/common/court-feedback.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/download-link.njk
  src/main/steps/common/page-link.njk
  src/main/steps/cookie-banner/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2417

#2418 NFDIV-2553 Submit AOS bug (v3)
  src/main/assets/js/confirm-read-petition-submit.ts
  src/main/assets/js/index.ts
  src/main/steps/common/content.utils.ts
  src/main/steps/respondent/review-the-application/content.ts
  src/main/steps/respondent/review-the-application/post.test.ts
  src/main/steps/respondent/review-the-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2418

#2388 Nfdiv-2350 Create unique sole and joint urls for enter-your-name page
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/enter-your-names/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/enter-your-names/content.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2388

#2390 Nfdiv 2350 unique urls for application submitted page 2
  src/main/modules/state-redirect/index.ts
  src/main/routes.ts
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/progress-bar.njk
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/joint-application-submitted/content.ts
  src/main/steps/applicant1/joint-application-submitted/template.njk
  src/main/steps/applicant1/payment-callback/get.test.ts
  src/main/steps/applicant1/payment-callback/get.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/joint-application-submitted/content.ts
  src/main/steps/applicant2/joint-application-submitted/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/application-submitted/get.test.ts
  src/main/steps/application-submitted/get.ts
  src/main/steps/index.ts
  src/main/steps/urls.ts
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2390

#2414 NFDIV-2627
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-pronouncement.njk
  src/test/functional/features/joint-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2414

#2465 Fix e2e tests after enter-your-names url update
  src/test/functional/features/applicant2.feature
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2465

#2361 nfdiv-2551 set UsedWelshTranslationOnSubmission field
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/main/steps/applicant1/check-your-answers/post.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/post.test.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/post.ts
  src/main/steps/applicant1/confirm-your-joint-application/post.test.ts
  src/main/steps/applicant1/confirm-your-joint-application/post.ts
  src/main/steps/applicant1/finalising-your-application/post.test.ts
  src/main/steps/applicant1/finalising-your-application/post.ts
  src/main/steps/applicant2/confirm-your-joint-application/post.test.ts
  src/main/steps/applicant2/confirm-your-joint-application/post.ts
  src/main/steps/respondent/check-your-answers/post.test.ts
  src/main/steps/respondent/check-your-answers/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2361

#2439 NFDIV-2675 Fix offline cases not seeing access code page
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/controller/AppRequest.ts
  src/main/modules/oidc/index.ts
  src/main/steps/applicant2/enter-your-access-code/get.test.ts
  src/main/steps/applicant2/enter-your-access-code/get.ts
  src/main/steps/existing-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2439

#2427 NFDIV-2398 - Welsh translation for switch to sole co
  src/main/steps/applicant1/changing-to-a-sole-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2427

#2419 NFDIV-2544 Display Conditional Order Granted document on hub page
  src/main/app/case/case.ts
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/conditional-order-pronounced.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/conditional-order-pronounced.njk
  src/main/steps/respondent/hub-page/content.ts
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2419

#2462 NFDIV-2685: Bug fix with CO tick
  src/main/steps/applicant1/hub-page/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2462

#2470 NFDIV-2399 - Welsh translation for co check-your-answers
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/test/functional/features/sole-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2470

#2428 NFDIV-2443 & NFDIV-2445 & NFDIV-2448 - Awaiting clarification and Clarification submitted hub pages (Welsh)
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2428

#2440 NFDIV-2621
  src/main/steps/applicant1/hub-page/joint/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2440

#2493 Add backstage configuration file
  catalog-info.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2493

#2487 Feature/nfdiv 2588 display offline aos pdf
  package.json
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/assets/js/index.ts
  src/main/assets/js/pdfjs.ts
  src/main/assets/scss/main.scss
  src/main/steps/applicant1/read-the-response/content.ts
  src/main/steps/applicant1/read-the-response/template.njk
  webpack/app.js
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2487

#2461 Nfdiv:2567 update hub citizen backlog
  config/default.yaml
  src/main/steps/applicant1/hub-page/progressBarLabels.test.ts
  src/main/steps/applicant1/hub-page/progressBarLabels.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2461

#2423 NFDIV-2382: Add Welsh translation for the pages
  src/main/steps/applicant1/continue-with-your-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2423

#2431 NFDIV-2383, 2384: Welsh withdraw screen add translation for sole and joint applications
  src/main/steps/applicant1/withdrawing-your-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2431

#2438 NFDIV-2386: Add Welsh translation for Review Application
  src/main/steps/applicant1/review-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2438

#2492 NFDIV-2580: Display bailiff serve date on hub
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-conditional-order.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/holding.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2492
