Repository hmcts/nfdiv-frontend, pull requests merged in 2022-05, with the labels that each got.

#2053 nfdiv-2146 fix document download bug
  src/main/modules/document-download/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2053

#2054 Nfdiv-2149 fix error for respondent url
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2054

#2083 nfdiv-2199 Add isApplicant2AlreadyLinked check
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2083

#2092 NFDIV-2166
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2092

#2080 NFDIV-2170 - Make certain URLs accessible without sign in
  src/main/app/controller/GetController.ts
  src/main/modules/oidc/index.ts
  src/main/modules/oidc/noSignInRequiredUrls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2080

#2087 NFDIV-1724 Offline AoS visible to digital applicant
  src/main/app/case/case.ts
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2087

#2101 Fix pa11y issue for webchat
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2101

#2107 Fix nightly test (RE NFDIV-2166)
  src/test/functional/features/respondent.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2107

#2129 Renaming SOT fields for convenience
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/post.test.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/check-your-answers/post.test.ts
  src/main/steps/applicant2/confirm-your-joint-application/content.ts
  src/main/steps/applicant2/confirm-your-joint-application/post.test.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/check-your-answers/content.ts
  src/main/steps/respondent/check-your-answers/post.test.ts
  src/main/steps/respondent/review-the-application/post.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2129

#2131 Move some functional tests to nightly
  src/test/functional/features/final-order.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/functional/features/switch-to-sole-application.feature
  src/test/functional/features/update-contact-details.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2131

#2084 Upgrade to @hmcts/cookie-manage v1.0.0
  package.json
  src/main/assets/js/cookie.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/cookie-banner/template.njk
  src/main/steps/cookies/template.njk
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2084

#2085 Upgrade redis to v4.1.0
  config/default.yaml
  package.json
  src/main/modules/session/index.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2085

#2140 Revert "Upgrade redis to v4.1.0 (#2085)"
  config/default.yaml
  package.json
  src/main/modules/session/index.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2140

#2104 Nfdiv 1668
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/template.njk
  src/main/steps/respondentSequence.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
  src/test/functional/features/respondent.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2104

#2108 nfdiv-2189: use the previous state when OfflineDocumentsReceived
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/template.njk
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/respondent/hub-page/template.njk
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2108

#2117 Nfdiv-2169 & 2160 - Updates to respondent solicitor fields
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/do-you-have-address/content.ts
  src/main/steps/applicant1/enter-solicitor-details/post.test.ts
  src/main/steps/applicant1/enter-solicitor-details/post.ts
  src/main/steps/applicant1/their-email-address/content.ts
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2117

#2154 Create yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2154

#2156 fix progress bar
  src/main/steps/applicant1/hub-page/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2156

#2160 NFDIV-1552: Add Welsh translations for Your Comments Sent page
  src/main/steps/applicant2/your-comments-sent/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2160

#2162 progress bar
  src/main/steps/applicant1/hub-page/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2162

#2148 NFDIV-2302 - AOS Statement of truth set to YES when respondent submits AOS (V2)
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2148
