Repository hmcts/nfdiv-frontend, pull requests merged in 2022-07, with the labels that each got.

#2279 nfdiv-2346 fix upload doc welsh
  src/main/assets/js/upload-manager/index.ts
  src/main/steps/applicant1/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2279

#2291 Update AccessCodePostController.ts
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2291

#2277 Nfdiv-2407-Welsh create new application-joint
  src/main/steps/switch-to-sole-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2277

#2243 Nfdiv 2309 2336 hub page updates
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-conditional-order.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2243

#2303 Fix access code post controller routes
  src/main/routes.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2303

#2305 Revert access code logging
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2305

#2306 Update access code logging
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2306

#2302 Nfdiv-2495 trim access code form data
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2302

#2238 NFDIV-1561 - You need to apply for help with your divoce fees
  src/main/steps/applicant1/apply-for-help-with-fees/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2238

#2309 NFDIV-2427 - Add logging to case-api for isApplicantAlreadyLinked
  src/main/app/case/case-api.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2309

#2310 nfdiv-2495 allow whitespace within access code
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2310

#2224 sole applicant and respondent hub pages translations
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/conditional-order-pronounced.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/holding.njk
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-aos.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2224

#2086 NFDIV-1342 : Update case and regenerate divorce application when respondent changes contact details
  src/main/app/case/definition.ts
  src/main/steps/applicant1/check-phone-number/post.test.ts
  src/main/steps/applicant1/check-phone-number/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2086

#2318 clean up packages to fix CVEs
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2318

#2314 Nfdiv-2453 Fix CYA jurisdiction answers order
  src/main/steps/applicant1/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2314

#2239 Nfdiv-2333 and 2301 - fix hub page for general applications
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-general-consideration.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-general-consideration.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2239

#2325 Remove unreachable code in soleTemplateSelector
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2325

#2278 NFDIV-2419 - Awaiting clarification hub page update
  src/main/app/case/case.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-clarification.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-clarification.njk
  src/main/steps/common/anchor-body.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2278

#2280 Nfdiv 1754 applicant2 email address error
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/applicant1/their-email-address/content.ts
  src/test/functional/features/form-failures.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2280

#2327 Tidy up phone number usage
  config/default.yaml
  src/main/steps/applicant1/how-you-can-proceed/content.ts
  src/main/steps/applicant1/how-you-can-proceed/template.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/application-submitted/content.ts
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2327

#2233 NFDIV-1820
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant2/needs-to-confirm-joint-application/content.ts
  src/main/steps/applicant2/you-need-to-review-your-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2233

#2336 Update definition.ts
  src/main/app/case/definition.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2336

#2334 NFDIV-2513 - Webchat application submitted page bugfix
  src/main/modules/state-redirect/index.ts
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us.njk
  src/main/steps/common/webchat.html
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2334

#2348 Revert "chore(deps-dev): bump playwright from 1.23.3 to 1.23.4 (#2347)"
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2348

#2340 nfdiv-2523 fix home get controller for CO states
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2340

#2354 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2354

#2355 nfdiv-2555 allow navigation to signInNotRequired pages
  src/main/modules/state-redirect/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2355

#2360 NFDIV-2187 - Typo APP_1_APP_2_LAST_RESIDENT
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2360

#2335 NFDIV-2313 - CO response docs not uploaded bug
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2335

#2363 fixing issues for nfdiv-2175
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/steps/switch-to-sole-application/post.test.ts
  src/main/steps/switch-to-sole-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2363

#2368 NFDIV-2566: Update translations for cookie and webchat Welsh content
  src/main/steps/common/common.content.ts
  src/main/steps/contact-us/content.ts
  src/main/steps/cookies/content.ts
  src/main/steps/terms-and-conditions/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2368

#2369 nfdiv-1567 respondent CYA welsh
  src/main/steps/respondent/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2369

#2362 NFDIV-2565 - Pages that don't require sign in should not timeout
  src/main/assets/js/session-timeout.ts
  src/main/steps/contact-us/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2362

#2372 NFDIV-2392- Welsh-Accessibility statement
  src/main/steps/accessibility-statement/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2372

#2367 Nfdiv-2581 Fix applicant 2 log in - 2
  src/main/app/access-code/AccessCodePostController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/applicant2/you-need-to-review-your-application/template.njk
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2367

#2326 NFDIV-2447 and 2434 - Hub page update clarification submitted
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/common/court-feedback.njk
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-clarification.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/clarification-submitted.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-clarification.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/clarification-submitted.njk
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/template.njk
  src/main/steps/common/content.utils.test.ts
  src/main/steps/common/content.utils.ts
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2326

#2374 NFDIV-2467: Add Welsh translation for same email error message
  src/main/steps/applicant1/their-email-address/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2374

#2383 Fix nightly 27 July 22
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/test/functional/features/joint-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2383

#2376 translations
  src/main/steps/applicant1/apply-for-help-with-fees/content.ts
  src/main/steps/applicant1/certificate-in-english/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/details-other-proceedings/content.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant1/enter-solicitor-details/content.ts
  src/main/steps/applicant1/get-certified-translation/content.ts
  src/main/steps/applicant1/help-with-your-fee/content.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/content.ts
  src/main/steps/applicant1/other-court-cases/content.ts
  src/main/steps/applicant1/their-email-address/content.ts
  src/main/steps/applicant1/where-your-lives-are-based/content.ts
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
  src/main/steps/applicant1/your-names-on-certificate/content.ts
  src/main/steps/common/common.content.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2376

#2384 clean up welsh progress bar app submitted
  src/main/assets/scss/application-submitted.scss
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2384
