Repository hmcts/nfdiv-frontend, pull requests merged in 2022-12, with the labels that each got.

#2711 NFDIV-3196 - Prevent double click for FO
  src/main/steps/applicant1/finalising-your-application/content.ts
  src/main/steps/applicant2/finalising-your-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2711

#2735 NFDIV-3213 - Update definition.ts file
  sonar-project.properties
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/common/hubTemplates.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2735

#2734 Format issue date on /review-the-application page
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2734

#2698 NFDiv-2697 fo switch to sole finalising divorce as sole
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/steps/applicant1/finalising-your-application/content.ts
  src/main/steps/applicant1/finalising-your-application/post.test.ts
  src/main/steps/applicant1/finalising-your-application/post.ts
  src/main/steps/applicant1/finalising-your-application/template.njk
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-final-order.njk
  src/main/steps/applicant2/finalising-your-application/content.ts
  src/main/steps/common/content.utils.test.ts
  src/main/steps/common/content.utils.ts
  src/main/steps/common/switch-to-sole-content.utils.test.ts
  src/main/steps/common/switch-to-sole-content.utils.ts
  src/main/steps/respondent/review-the-application/post.ts
  src/test/functional/features/joint-final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2698

#2746 Suppress @hmcts/nodejs-healthcheck security issue (qs)
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2746

#2728 NFDIV-2801 - Middle name inset text content change
  src/main/steps/applicant1/enter-your-name/content.ts
  src/main/steps/applicant1/enter-your-name/template.njk
  src/main/steps/applicant1/enter-your-names/template.njk
  src/main/steps/applicant2/enter-your-name/content.ts
  src/main/steps/applicant2/enter-your-names/content.ts
  src/main/steps/applicant2/enter-your-names/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2728

#2747 Revert sauce-service upgrade
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2747

#2760 Revert "chore(deps-dev): bump @wdio/sauce-service from 7.27.0 to 8.0.…
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2760

#2720 NFDIV-3204 - Prevent users visiting certain URLs
  src/main/routes.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/routeHiding.test.ts
  src/main/steps/routeHiding.ts
  src/main/steps/url-utils.test.ts
  src/main/steps/url-utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2720

#2765 Bulk dependency upgrade 16/12/22
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2765

#2767 Revert "NFDIV-3204 - Prevent users visiting certain URLs (#2720)"
  src/main/routes.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/routeHiding.test.ts
  src/main/steps/routeHiding.ts
  src/main/steps/url-utils.test.ts
  src/main/steps/url-utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2767

#2770 Revert webdriverio major upgrade
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2770
