Repository hmcts/nfdiv-frontend, pull requests merged in 2022-01, with the labels that each got.

#1602 Fix nightly tests
  src/main/steps/applicant1/check-your-answers/template.njk
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/switch-to-sole-application.feature
  src/test/steps/date.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1602

#1598 Clean up CYA pages
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1598

#1608 Fix private address fields showing on CYA
  src/main/steps/applicant1/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1608

#1604 NFDIV-1556 Collapse citizen update events
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/steps/applicant1/hub-page/post.test.ts
  src/main/steps/applicant1/hub-page/post.ts
  src/main/steps/applicant2/hub-page/post.test.ts
  src/test/functional/features/applicant1-sole-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1604

#1610 Merged citizen and solicitor invite applicant 2 event
  src/main/app/case/definition.ts
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/main/steps/applicant1/check-your-answers/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1610

#1612 Update home get controller for ConditionalOrderPending state
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1612

#1614 Fix progress bar for joint hub page
  src/main/steps/applicant1/hub-page/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1614

#1613 Nfdiv-1309-1308 hub page awaitingCO with deemed/dispensed or bailiff …
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/form.njk
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/test/functional/features/hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1613

#1620 Add missing punctuation to hub page
  src/main/steps/applicant1/hub-page/sole/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1620

#1618 Nfdiv 1207
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1618

#1617 Nfdiv 1555
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/switch-to-sole-application/content.ts
  src/main/steps/switch-to-sole-application/form.njk
  src/main/steps/switch-to-sole-application/get.test.ts
  src/main/steps/switch-to-sole-application/get.ts
  src/main/steps/switch-to-sole-application/post.test.ts
  src/main/steps/switch-to-sole-application/post.ts
  src/main/steps/switch-to-sole-application/template.njk
  src/test/functional/features/applicant-middleware.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1617

#1625 Nfdiv 1207 fix
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1625

#1624 NFDIV-1204 & NFDIV-1176
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/template.njk
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1624

#1619 Nfdiv-1319 Sole hub page CO pronounced
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/home/get.test.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/template.njk
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1619

#1633 Updated field type for applicant 2 solicitor prayer from yes/no to checkbox
  package-lock.json
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1633

#1636 Mark PCQ e2e tests as flaky
  src/test/functional/features/equality.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1636

#1646 Nfdiv 1306
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/home/get.test.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1646

#1632 Nfdiv 1155 joint co continuing with application
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/continue-with-your-application/content.ts
  src/main/steps/applicant1/continue-with-your-application/template.njk
  src/main/steps/applicant1/withdrawing-your-application/content.ts
  src/main/steps/applicant1/withdrawing-your-application/template.njk
  src/main/steps/applicant2/continue-with-your-application/content.ts
  src/main/steps/applicant2/continue-with-your-application/template.njk
  src/main/steps/applicant2/withdrawing-your-application/content.ts
  src/main/steps/applicant2/withdrawing-your-application/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/test/functional/features/applicant1-sole-conditional-order.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/features/joint-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1632

#1647 Move anchor tags to template for withdrawing your app page
  src/main/steps/applicant1/withdrawing-your-application/content.ts
  src/main/steps/applicant1/withdrawing-your-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1647

#1648 Add latest definition.ts with court label constants
  src/main/app/case/definition.ts
  src/main/steps/applicant2/check-your-joint-application/post.test.ts
  src/main/steps/applicant2/check-your-joint-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1648

#1651 Fix certificate of entitlement download
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1651

#1652 Fix certificate of entitlement for respondent
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1652

#1654 Fix and clean up conditional order hub page
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1654

#1657 Fix nightly tests
  src/test/functional/features/applicant-middleware.feature
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1657

#1663 clean up
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1663

#1664 Clean up progression index for hub page
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/applicant2/hub-page/form.njk
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1664

#1666 Fix nightly test
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1666

#1667 Fix incorrect state on progress bar
  src/main/steps/applicant1/hub-page/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1667

#1672 clean up
  src/main/routes.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1672

#1662 Nfdiv-1157 CYA page for joint CO
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/template.njk
  src/main/steps/applicant2/check-your-conditional-order-answers/content.ts
  src/main/steps/applicant2/check-your-conditional-order-answers/post.ts
  src/main/steps/applicant2/check-your-conditional-order-answers/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/index.ts
  src/test/functional/features/applicant2.feature
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/fixtures/jointApplicant2CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1662

#1665 Nfdiv 1610
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/sole-conditional-order.feature
  src/test/steps/IdamUserManager.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1665

#1680 Add more tests
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/to-api-format.test.ts
  src/main/steps/index.test.ts
  src/main/steps/urls.ts
  src/test/functional/fixtures/completeCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1680

#1682 Revert index.ts changes until coverage can be fixed
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1682

#1688 Update package.json
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1688

#1696 Nfdiv 1610 fix
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1696

#1699 Clean up joint hub page and add test
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-pronouncement.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/holding.njk
  src/test/functional/features/joint-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1699

#1695 Clean up sole hub page and add tests
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-due.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-conditional-order.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-general-consideration.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/conditional-order-pronounced.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/holding.njk
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-aos.njk
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-general-consideration.njk
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/respondent/hub-page/latest-update-content/conditional-order-pronounced.njk
  src/main/steps/respondent/hub-page/latest-update-content/holding.njk
  src/main/steps/respondent/hub-page/template.njk
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1695

#1689 clean up respondent hub page after joint was merged
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/conditional-order-pronounced.njk
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/sole-hub-page.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1689

#1701 Nfdiv-1611 Joint hub CO pronounced
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/conditional-order-pronounced.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1701

#1705 Clean up and collate e2e tests
  src/test/functional/features/applicant-middleware.feature
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/enter-your-access-code.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/how-you-can-proceed.feature
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/respondent.feature
  src/test/functional/features/sole-conditional-order.feature
  src/test/functional/features/sole-hub-page.feature
  src/test/functional/features/switch-to-sole-application.feature
  src/test/functional/features/their-address.feature
  src/test/functional/features/update-contact-details.feature
  src/test/functional/features/your-address.feature
  src/test/functional/features/your-details.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1705

#1710 Remove duplicated jurisdiction tests
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/enter-your-access-code.feature
  src/test/functional/features/footer-links.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/functional/features/jurisdiction-may-not-be-able-to-england-and-wales.feature
  src/test/functional/features/living-in-england-wales-six-months.feature
  src/test/functional/features/living-in-england-wales-twelve-months.feature
  src/test/functional/features/may-not-be-able-to-england-and-wales.feature
  src/test/functional/features/residual-jurisdiction.feature
  src/test/functional/features/where-your-lives-are-based.feature
  src/test/functional/features/your-domicile.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1710
