Repository hmcts/nfdiv-frontend, pull requests merged in 2022-03, with the labels that each got.

#1806 Add payments to smoketest
  src/main/steps/applicant1/payment-callback/get.test.ts
  src/main/steps/applicant1/payment-callback/get.ts
  src/test/smoke/smoke.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1806

#1802 Feature/nfdiv 1158 hubpage submitted co
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-legal-advisor-referral.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/conditional-order-pending.njk
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/applicant2/hub-page/form.njk
  src/main/steps/respondent/hub-page/template.njk
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
  src/test/functional/features/joint-conditional-order.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1802

#1793 Nfdiv 1477
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/template.njk
  src/main/steps/applicant2/provide-information-to-the-court/content.ts
  src/main/steps/applicant2/provide-information-to-the-court/post.ts
  src/main/steps/applicant2/provide-information-to-the-court/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/home/get.ts
  src/test/functional/features/joint-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1793

#1812 Add fee register integration
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/fees/service/get-fee.test.ts
  src/main/app/fees/service/get-fee.ts
  src/main/modules/fees-register/index.ts
  src/main/server.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/how-you-can-proceed/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1812

#1814 Update definition and change applicant address
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1814

#1815 Ignore CSRF errors
  src/main/modules/appinsights/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1815

#1808 NFDIV-1674 - Add hub page content for AwaitingServicePayment state
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-payment.njk
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1808

#1827 Change use of email from session to explicitly use applicant1Email
  src/main/app/case/case.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1827

#1823 Update the date on respondent hub page to be issueDate+37days
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1823

#1813 Nfdiv-1507 Update jurisdiction
  src/main/app/form/Form.ts
  src/main/app/jurisdiction/JurisdictionPostController.test.ts
  src/main/app/jurisdiction/JurisdictionPostController.ts
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/app/jurisdiction/moreDetailsContent.test.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/assets/js/go-back.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/connection-summary/content.ts
  src/main/steps/applicant1/connection-summary/post.ts
  src/main/steps/applicant1/connection-summary/template.njk
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/template.njk
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
  src/main/steps/applicant1/you-can-use-english-welsh-courts/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/content.ts
  src/main/steps/urls.ts
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1813

#1828 nfdiv-1158: fix response dates on hub page
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1828

#1829 Add 2 new jurisdiction connections
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1829

#1797 Nfdiv 1640
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/fees/service/get-fee.ts
  src/main/steps/respondent/finalising-your-application/content.ts
  src/main/steps/respondent/finalising-your-application/form.njk
  src/main/steps/respondent/finalising-your-application/post.ts
  src/main/steps/respondent/finalising-your-application/template.njk
  src/main/steps/respondentSequence.ts
  src/test/functional/features/final-order.feature
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1797

#1831 attempt to add GA tracking and update CSP
  src/main/assets/js/cookie.ts
  src/main/modules/helmet/index.ts
  src/main/steps/common/page.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1831

#1830 NFDIV-1677 Update postal and email addresses
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/how-you-can-proceed/template.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/terms-and-conditions/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1830

#1833 Nfdiv 1797
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1833

#1838 Nfdiv-1700 fix sequence for alternate service
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1838

#1840 NFDIV-1756 Add same-sex field to CYA
  src/main/steps/applicant1/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1840

#1839 Fix nightly tests
  src/test/functional/features/form-failures.feature
  src/test/functional/features/respondent.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1839

#1843 Missed some fees
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/dividing-money-property/content.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant1/help-with-your-fee/content.ts
  src/main/steps/applicant1/how-to-apply-to-serve/content.ts
  src/main/steps/applicant1/need-to-get-address/content.ts
  src/main/steps/applicant1/pay-and-submit/content.ts
  src/main/steps/applicant1/pay-your-fee/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant2/help-with-your-fee/content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1843

#1841 NFDIV 1751 - Displaying respondent overseas page
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/enter-their-address/content.ts
  src/main/steps/applicant1/you-need-to-serve/content.ts
  src/main/steps/applicant1Sequence.test.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1841

#1803 NFDIV 1672 clean up & NFDIV 1781
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1803

#1842 Nfdiv-1831 fix disputed due date
  config/default.yaml
  src/main/app/case/case.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/respondent/disputing-the-application/content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1842

#1847 Add feature test for final order overdue
  src/test/functional/features/final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1847

#1821 Nfdiv 1676
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/bailiff-service-unsuccessful.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/service-application-rejected.njk
  src/test/functional/features/sole-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1821

#1844 Clean up dates
  config/default.yaml
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/application-sent-for-review/content.ts
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/how-you-can-proceed/content.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1844

#1860 Nfdiv 1810 add redirect
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1860

#1817 new changes for joint hub page
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/clarification-submitted.njk
  src/test/functional/features/joint-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1817

#1854 Feature/nfdiv 1045 review joint solicitor app1 answers
  src/main/app/case/formatter/uploaded-files.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/template.njk
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant1/upload-your-documents/document-upload.njk
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/upload-your-documents/content.ts
  src/main/steps/applicant2/upload-your-documents/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1854

#1861 Fix an issue where logging out in decree nisi and returning to NFD will cause an error
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1861

#1862 Refactor applicant1/you-can-use-english-welsh-courts/content.ts
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1862

#1866 Fix nightly tests after gender change
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1866

#1865 NFDIV-1674 sole hub page for awaiting service
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-consideration-or-awaiting-bailiff-referral.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-payment.njk
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1865

#1867 move to bottom
  src/main/steps/common/page.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1867

#1878 Fix jurisdiction content
  src/main/app/jurisdiction/bulletedPointsContent.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1878

#1876 NFDIV-1888 - Hub when the bailiff application is successful
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-bailiff-service.njk
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1876

#1875 content update
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1875

#1883 Fix issue with missing case type in dev env
  src/main/app/case/CaseApi.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1883

#1884 nfdiv-1833: update application-submitted page content
  config/default.yaml
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1884

#1888 Fix undefined showing for middle name of applicant2 on confirm-your-joint-application page
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1888

#1887 first commit to remove what language do you want to receive emails an…
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/common/page.njk
  src/main/steps/respondentSequence.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/homepage.feature
  src/test/functional/features/respondent.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1887

#1889 nfdiv-1672: fix address formatting
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/content.utils.test.ts
  src/main/steps/common/content.utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1889

#1898 relax timeouts
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1898

#1906 remove babel, upgrade jest, remove jest-extended
  jest.config.js
  package.json
  src/global.d.ts
  src/main/app/auth/service/get-service-auth-token.test.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/fees/service/get-fee.test.ts
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/applicant1/payment-callback/get.test.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1906

#1907 run unit tests once
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1907

#1902 Fix applicant 2 CYA
  src/main/steps/applicant2/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1902

#1908 Add missing dateFinalOrderNoLongerEligible field for NPE
  src/test/functional/features/final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1908

#1910 nfdiv-1936: tidy up content and template
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
  src/main/steps/common/content.utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1910

#1912 node 16
  .nvmrc
  Dockerfile
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1912

#1904 clean up cannot upload checkbox and cya page
  src/main/assets/js/upload-manager/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/upload-your-documents/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1904

#1914 nfdiv-1942: add country to cya page
  src/main/steps/respondent/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1914

#1913 Rename redis which will create new instance as there are connection issues in prod
  infrastructure/main.tf
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1913

#1917 tweak config
  src/test/functional/codecept.conf.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1917

#1922 Move webchat script to contact-us partial
  src/main/steps/common/contact-us.njk
  src/main/steps/common/page.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1922

#1909 Fix e2e tests
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/final-order.feature
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1909

#1934 Fix for NPE in app insights
  src/test/functional/features/final-order.feature
  src/test/functional/fixtures/finalOrderCompleteCase.ts
  src/test/functional/fixtures/finalOrderOverdueCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1934

#1923 NFDIV-1957 - Non descriptive names
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/template.njk
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant1/upload-your-documents/document-upload.njk
  src/main/steps/common/content.utils.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1923

#1936 Fix incorrect url for test
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1936

#1926 Nfdiv 1948
  jest.a11y.config.js
  src/main/steps/common/form/fields/checkboxes.njk
  src/main/steps/common/form/fields/date.njk
  src/main/steps/common/form/fields/input.njk
  src/main/steps/common/form/fields/option.njk
  src/main/steps/common/form/fields/radios.njk
  src/main/steps/common/form/fields/textarea.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1926

#1925 common page for application submitted and clean up
  src/main/routes.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/get.test.ts
  src/main/steps/application-submitted/get.ts
  src/main/steps/application-submitted/template.njk
  src/test/functional/features/applicant2.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1925

#1937 add autocomplete
  src/main/app/form/Form.ts
  src/main/steps/applicant1/enter-their-address/content.ts
  src/main/steps/applicant1/enter-their-name/content.ts
  src/main/steps/applicant1/enter-your-address/content.ts
  src/main/steps/applicant1/enter-your-name/content.ts
  src/main/steps/applicant1/your-names-on-certificate/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1937

#1939 add address 2 label and make it visually hidden
  src/main/assets/js/address/links.ts
  src/main/steps/applicant1/enter-your-address/postcodeEnter.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1939

#1941 add descriptive label to delete button
  src/main/assets/js/upload-manager/updateFileList.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1941

#1946 Remove pcq from cross browser test
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1946

#1928 Nfdiv-1966 update residual jurisdiction question
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/steps/applicant1/are-you-eligible-for-residual-jurisdiction/content.ts
  src/main/steps/applicant1Sequence.ts
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/functional/features/jurisdiction-may-not-be-able-to-england-and-wales.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1928

#1947 Add wait to postcode lookup functional test
  src/test/functional/features/form-failures.feature
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1947

#1948 Nfdiv 1952 CSS Dac 2
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/template.njk
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1948

#1956 clean up
  src/main/steps/applicant1/provide-information-to-the-court/form.njk
  src/main/steps/applicant1/provide-information-to-the-court/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1956

#1940 NFDIV-1953 - Add structure to review-the-application page (DAC)
  src/main/assets/scss/main.scss
  src/main/assets/scss/review-pages.scss
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1940

#1963 Re-add pcq to cross browser test
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1963

#1964 Configure the webchat URLs for respective environments
  charts/nfdiv-frontend/Chart.yaml
  config/custom-environment-variables.yaml
  src/main/steps/common/webchat.html
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1964

#1943 Nfdiv-1955 Update middle name text
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/enter-their-name/content.ts
  src/main/steps/applicant1/enter-your-name/content.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1943

#1958 Bug/nfdiv 1949 dac visual headings
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/app/jurisdiction/moreDetailsContent.test.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/more-details.njk
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/how-do-you-want-to-apply/template.njk
  src/main/steps/applicant1/how-you-can-proceed/template.njk
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/clarification-submitted.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/clarification-submitted.njk
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/form.njk
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/form.njk
  src/main/steps/applicant1/review-your-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/template.njk
  src/main/steps/applicant2/check-your-joint-application/template.njk
  src/main/steps/applicant2/help-with-your-fee/template.njk
  src/main/steps/applicant2/review-your-joint-application/content.ts
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/content.utils.test.ts
  src/main/steps/common/content.utils.ts
  src/main/steps/common/service-address.njk
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/holding.njk
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/template.njk
  src/main/steps/terms-and-conditions/content.ts
  src/main/steps/terms-and-conditions/template.njk
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1958

#1874 NFDIV-1879 Prevent users from updating case after submission
  src/main/app/jurisdiction/jurisdictionRemovalHelper.ts
  src/main/routes.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/template.njk
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1Sequence.test.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/respondent/check-your-answers/content.ts
  src/main/steps/respondentSequence.ts
  src/main/steps/state-sequence.test.ts
  src/test/functional/features/applicant2.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1874

#1957 add error summary for upload
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
  src/main/steps/applicant1/provide-information-to-the-court/template.njk
  src/test/functional/features/form-failures.feature
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/joint-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1957

#1955 Updates to residual jurisdiction
  src/main/steps/applicant1/are-you-eligible-for-residual-jurisdiction/content.ts
  src/main/steps/applicant1/are-you-eligible-for-residual-jurisdiction/template.njk
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1955

#1966 Revert temporary webchat URL - don't merge
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us.njk
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1966

#1970 Fix form failure nightly test
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1970
