Repository hmcts/nfdiv-frontend, pull requests merged in 2022-04, with the labels that each got.

#1977 Fix CYA bug
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant2/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1977

#1924 Nfdiv-1968 Update jurisdiction content
  src/main/app/case/definition.ts
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/app/jurisdiction/connections.test.ts
  src/main/app/jurisdiction/connections.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1924

#1985 nfdiv-2067: set applicant2ApplyForFinancialOrder in form
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/main/steps/applicant1/check-your-answers/post.ts
  src/main/steps/applicant2/check-your-answers/post.test.ts
  src/main/steps/applicant2/check-your-answers/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1985

#1990 Fix jurisdiction connection content error
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1990

#1983 NFDIV-2070 and 2071 revert clean up changes to CYA
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/app/jurisdiction/moreDetailsContent.test.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/more-details.njk
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-joint-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1983

#1982 NFDIV-2059 - Fix the save and sign out button on pay-your-fee page
  src/main/app/access-code/AccessCodePostController.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/applicant1/pay-your-fee/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1982

#1991 change session timeout to include checkboxes
  src/main/assets/js/session-timeout.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1991

#1992 Nullify respondent sol fields if appType is joint
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1992

#1993 Nfdiv-2115 application submitted progress bar fix
  src/main/steps/application-submitted/content.ts
  src/main/steps/application-submitted/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1993

#2003 Nfdiv-2128 Fix upload doc page content
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2003

#2004 nfdiv-2112: retry failed request if 409 or 422 status
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2004

#2011 Nfdiv-1944 Fix postcode look up
  src/main/assets/js/address/submit.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2011

#2017 Suppress CVEs
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2017

#1997 NFDIV-2113 - Increase upload size and timeout
  config/default.yaml
  src/main/app/document/DocumentManagementClient.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/modules/timeouts/index.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1997

#2021 remove spaces within data for idam token
  src/main/app/auth/user/oidc.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2021

#2025 mega dep upgrade
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2025

#2026 Update hmcts logging
  package.json
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/postcode/postcode-lookup.test.ts
  src/main/app/postcode/postcode-lookup.ts
  src/main/modules/csrf/index.ts
  src/main/modules/error-handler/index.ts
  src/main/server.ts
  src/test/steps/common.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2026

#2012 Nfdiv-2079 Fix due dates on hub page
  config/default.yaml
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2012

#2030 remove asset watch as we have webpack dev middleware
  nodemon.assets.json
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2030

#2027 fix to use data to create form on next step sequence function
  src/main/steps/index.test.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2027

#2016 Nfdiv-2137 Fix content on respondent page
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2016

#2018 fix incorrect gender on aos page
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/content.utils.test.ts
  src/main/steps/common/content.utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2018

#2049 Revert dependency upgrade
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2049

#2035 Improve and clean up functional tests
  src/test/config.ts
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/final-order.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/jurisdiction-may-not-be-able-to-england-and-wales.feature
  src/test/functional/features/sole-conditional-order.feature
  src/test/functional/features/switch-to-sole-application.feature
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2035

#2052 remove jest circus
  jest.a11y.config.js
  jest.smoke.config.js
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2052

#2036 Combine jurisdiction functional tests
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/functional/features/jurisdiction-may-not-be-able-to-england-and-wales.feature
  src/test/steps/common.ts
  src/test/steps/jurisdiction.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2036

#1998 Nfdiv 2090
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/template.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/test/functional/features/homepage.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1998

#2013 NFDIV-1735 - On ExUI, show whether supporting documents have been uploaded
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2013
