Repository hmcts/nfdiv-frontend, pull requests merged in 2022-10, with the labels that each got.

#2597 nfdiv-2683: increase timeout to reduce flakiness
  package.json
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2597

#2568 NFDiv-2874 Add Submit Property to Common.Content
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/check-your-answers/content.ts
  src/main/steps/respondent/finalising-your-application/content.ts
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/sole-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2568

#2380 DAC report fix
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/assets/scss/upload-documents.scss
  src/main/steps/applicant1/upload-your-documents/document-upload.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2380

#2599 NFDIV-2843 Welsh Conditional Order -Error
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2599

#2564 NFDIV-2455 Add Welsh Translation
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2564

#2563 NFDiv-2458 Add Welsh Translation
  src/main/steps/applicant1/finalising-your-application/content.ts
  src/test/functional/features/final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2563

#2605 fix nightly tests
  src/test/functional/features/final-order.feature
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2605

#2574 Nfdiv-2871 Remove back buttons on certain CO pages
  src/main/steps/applicant1/check-your-conditional-order-answers/template.njk
  src/main/steps/applicant1/continue-with-your-application/template.njk
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/read-the-response/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2574

#2567 NFDIV-1607 - Do you want to finalise your divorce
  config/default.yaml
  src/main/steps/applicant1/finalising-your-application/content.ts
  src/main/steps/applicant1/finalising-your-application/template.njk
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/finalising-your-application/content.ts
  src/main/steps/applicant2/finalising-your-application/post.ts
  src/main/steps/applicant2/finalising-your-application/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/home/get.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2567

#2556 Bug/nfdiv 2699 prevent new case linking for ceratain states
  config/default.yaml
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/applicant1/application-ended/get.test.ts
  src/main/steps/applicant1/application-ended/template.njk
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/progressBarLabels.test.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/withdrawing-your-application/template.njk
  src/main/steps/applicant2/enter-your-access-code/get.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/contact-us/get.test.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/error/error.controller.test.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/existing-application/content.ts
  src/main/steps/existing-application/get.test.ts
  src/main/steps/existing-application/get.ts
  src/main/steps/existing-application/post.test.ts
  src/main/steps/existing-application/post.ts
  src/main/steps/existing-application/template.njk
  src/main/steps/index.ts
  src/main/steps/no-response-yet/get.test.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
  src/main/steps/switch-to-sole-application/get.test.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/timed-out/get.test.ts
  src/main/steps/urls.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2556

#2612 NFDIV-1607 applicant 2-Final Overdue state-For Nightly tests fix
  src/main/steps/applicant2Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2612

#2588 Nfdiv-1790: Welsh Final order complete latest update hub page
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/final-order-complete.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/final-order-complete.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/final-order-complete.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2588

#2616 Fix nightly tests
  src/test/functional/features/final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2616

#2617 Change button text to Continue
  src/test/functional/features/final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2617

#2553 NFDIV-1608/NFDIV-2478
  src/main/app/case/from-api-format.ts
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-final-order.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/final-order-requested.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/home/get.ts
  src/test/functional/features/joint-hub-page-applied-first.feature
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/sole-final-order.feature
  src/test/functional/fixtures/jointApplicant1AppliedFirstCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2553

#2619 Cache test IDAM tokens
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.aat.template.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  package.json
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/test/steps/common.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2619

#2618 NFDIV-3089 - Prevent submit aos double click
  src/main/steps/respondent/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2618

#2620 NFDIV-3098 - Change logic for showing CO hub page
  src/main/steps/applicant1/check-your-conditional-order-answers/template.njk
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2620

#2607 NFDIV-3048 - Fix case priority (v2)
  src/main/app/case/case-api.test.ts
  src/main/app/case/case-api.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2607

#2555 NFDIV-2461 Add Welsh Translation
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2555

#2593 NFDiv-2804 Add translations for doc download links
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2593

#2538 NFDIV-1580 Hub when FO Granted
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/final-order-complete.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/final-order-complete.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/final-order-complete.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2538

#2611 Fix preview URL
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2611

#2646 nfdiv-2362: add errors to dataLayer for analytics
  src/main/assets/js/data-layer.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2646
