Repository hmcts/nfdiv-frontend, pull requests merged in 2022-09, with the labels that each got.

#2510 NFDIV-2777 Prioritise submitted cases
  src/main/app/case/case-api.test.ts
  src/main/app/case/case-api.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2510

#2463 NFDIV-2442 - Update final order requested to account for new applicant2 event
  src/main/app/case/definition.ts
  src/main/steps/applicant1/finalising-your-application/post.test.ts
  src/main/steps/applicant1/finalising-your-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2463

#2401 NFDIV-2207
  catalog-info.yaml
  src/main/app/case/case-api.test.ts
  src/main/app/case/case-api.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/applicant1/pay-your-fee/post.ts
  src/main/steps/applicant1/payment-callback/get.test.ts
  src/main/steps/applicant1/payment-callback/get.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2401

#2523 NFDIV-2787 Prevent double click on conditional order fields
  src/main/assets/js/disable-upon-submit.ts
  src/main/assets/js/index.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/main/steps/applicant1/hub-page/joint/form.njk
  src/main/steps/applicant1/hub-page/sole/form.njk
  src/main/steps/applicant2/check-your-conditional-order-answers/content.ts
  src/main/steps/common/content.utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2523

#2530 nfdiv-2794: remove feature toggle
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  src/main/app/case/case-api.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2530

#2518 NFDIV-2785 - Fix timeout page issues
  src/main/assets/js/session-timeout.ts
  src/main/steps/save-sign-out/get.ts
  src/main/steps/timed-out/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2518

#2349 nfdiv-1159 and nfdiv-2414 changing to a sole application CO
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/changing-to-a-sole-application/content.ts
  src/main/steps/applicant1/changing-to-a-sole-application/form.njk
  src/main/steps/applicant1/changing-to-a-sole-application/post.test.ts
  src/main/steps/applicant1/changing-to-a-sole-application/post.ts
  src/main/steps/applicant1/changing-to-a-sole-application/template.njk
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/conditional-order-pending.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/changing-to-a-sole-application/content.ts
  src/main/steps/applicant2/changing-to-a-sole-application/post.ts
  src/main/steps/applicant2/changing-to-a-sole-application/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2349

#2511 NFDIV-2740 - Prevent multiple cases creation
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/applicant1/your-details/content.ts
  src/main/steps/applicant1/your-details/post.test.ts
  src/main/steps/applicant1/your-details/post.ts
  src/main/steps/common/form/form.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/test/config.ts
  src/test/functional/features/form-failures.feature
  src/test/steps/common.ts
  src/test/steps/happy-path.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2511

#2475 Nfdiv-2628 respondent ConditionalOrderPronounced hub page update
  src/main/steps/respondent/hub-page/content.ts
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2475

#2488 Nfdiv-2733 fix welsh translations on app2 pages
  src/main/steps/applicant1/apply-for-help-with-fees/content.ts
  src/main/steps/applicant2/apply-for-help-with-fees/content.ts
  src/main/steps/applicant2/have-you-applied-for-help-with-fees/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2488

#2542 Move jointHubPageSubheading into content file
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/common/content.utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2542

#2498 NFDIV-2754 - Prevent save on save and sign out on respondent/review-the-application page
  src/main/steps/respondent/review-the-application/post.test.ts
  src/main/steps/respondent/review-the-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2498

#2548 Add test for getExistingAndNewUserCases to bump coverage
  src/main/app/case/case-api.test.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2548

#2540 nfdiv-2806 prevent caseworker from seeing citizen cases
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2540

#2545 DTSSE-1790 nfdiv-frontend README
  README.md
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2545

#2550 Fix nightly tests
  src/test/config.ts
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2550

#2562 Fix PR URLs
  README.md
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2562

#2573 reduce no of concurrent tests
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2573

#2557 NFDIV-2786 - Change sequence index for app2 in joint CO journey
  src/main/steps/index.test.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2557

#2572 nfdiv-2872 fix applicant2ConfirmInformationStillCorrect field
  src/main/steps/applicant2/review-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2572

#2554 NFDIV-2805
  src/main/modules/state-redirect/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2554

#2509 NFDIV-1620: update hub when final order is submitted
  src/main/app/case/case.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/final-order-requested.njk
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/final-order-requested.njk
  src/test/functional/features/final-order.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2509

#2454 NFDIV-2446 Welsh Hub (joint/sole) when refused for amendment
  src/main/app/case/case.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-amended-application.njk
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-amended-application.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-amended-application.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2454

#2430 Nfdiv 2385 - Welsh review application sole
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2430

#2529 update govuk-frontend 4.3.1
  package.json
  src/main/assets/scss/main.scss
  webpack/govukFrontend.js
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2529
