Repository hmcts/nfdiv-frontend, pull requests merged in 2022-06, with the labels that each got.

#2182 Fix e2e tests
  src/test/functional/features/joint-hub-page.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2182

#2195 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2195

#2152 Bug/nfdiv 2245 fix linking url issues
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/case-api-client.test.ts
  src/main/app/case/case-api-client.ts
  src/main/app/case/case-api.test.ts
  src/main/app/case/case-api.ts
  src/main/app/controller/AppRequest.ts
  src/main/modules/oidc/index.ts
  src/main/modules/oidc/noSignInRequiredUrls.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/applicant2/enter-your-access-code/get.test.ts
  src/main/steps/applicant2/enter-your-access-code/get.ts
  src/main/steps/switch-to-sole-application/post.ts
  src/main/steps/url-utils.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2152

#2213 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2213

#2159 NFDIV-1816: Add Welsh translations to the disputing the application page
  src/main/steps/respondent/disputing-the-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2159

#2158 NFDIV-1814: Add Welsh translations for how do you want to respond page
  src/main/steps/respondent/how-do-you-want-to-respond/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2158

#2163 NFDIV-1521: Update Welsh content on application sent for review page
  src/main/steps/applicant1/application-sent-for-review/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2163

#2164 NFDIV-1518: Add Welsh translations for Application Ended page
  src/main/steps/applicant1/application-ended/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2164

#2197 NFDIV-1519
  src/main/steps/applicant1/changes-to-your-name/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2197

#2199 NFDIV-2347: Add Welsh translation for You need to serve page
  src/main/steps/applicant1/you-need-to-serve/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2199

#2169 NFDIV-1517
  src/main/steps/applicant1/no-response-yet/content.ts
  src/main/steps/applicant1/no-response-yet/template.njk
  src/main/steps/no-response-yet/content.ts
  src/main/steps/no-response-yet/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2169

#2220 nfdiv-2378: login with applicant 2 to fix test
  src/test/functional/features/form-failures.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2220

#2227 Fix nightly tests
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2227

#2229 Remove unused code
  src/main/steps/applicant1/help-with-your-fee/content.ts
  src/main/steps/applicant1/you-cannot-apply/content.ts
  src/main/steps/applicant1/you-cannot-apply/template.njk
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2229

#2112 NFDIV-2221 Represented Respondent NoP posted to Respondent Address
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2112

#2166 Nfdiv-1913 jurisdiction connections welsh
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/you-can-use-english-welsh-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2166

#2232 Hub page clean up
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/applicant-not-yet-applied-for-conditional-order.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/final-order-requested.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  src/main/steps/respondent/hub-page/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2232

#2203 Nfdiv-2353 allow applicants to link onto a new case
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/case/case-api-client.test.ts
  src/main/app/case/case-api-client.ts
  src/main/app/case/case-api.test.ts
  src/main/app/case/case-api.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant2/enter-your-access-code/get.test.ts
  src/main/steps/applicant2/enter-your-access-code/get.ts
  src/main/steps/applicant2/enter-your-access-code/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2203

#2250 Nfdiv 2348 you cannot apply welsh
  src/main/steps/applicant2/you-cannot-apply/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2250

#2253 NFDIV-2429 - Fix What this means bug
  src/main/app/jurisdiction/moreDetailsContent.test.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/review-the-application/template.njk
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2253

#2183 Nfdiv-2345 Welsh dates translation fix
  src/main/app/form/Form.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/applicant1/date-from-certificate/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2183

#2216 NFDIV-2372 - Applicant 2 shown upload documents page if name change not by marriage certificate
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant2Sequence.test.ts
  src/main/steps/applicant2Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2216

#2242 update dependencies
  .nvmrc
  package.json
  src/main/modules/helmet/index.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2242

#2155 Nfdiv 1520
  src/main/app/jurisdiction/bulletedPointsContent.test.ts
  src/main/app/jurisdiction/bulletedPointsContent.ts
  src/main/app/jurisdiction/moreDetailsContent.test.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2155

#2257 NFDIV-1815 (V2) => Welsh - The legal power (jurisdiction) of the courts
  src/main/app/jurisdiction/moreDetailsContent.test.ts
  src/main/app/jurisdiction/moreDetailsContent.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/respondent/legal-jurisdiction-of-the-courts/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2257

#2161 NFDIV-1550 Welsh translation of You need to review your joint application
  src/main/steps/applicant2/you-need-to-review-your-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2161

#2258 Update cookie manager
  package.json
  src/main/assets/js/cookie.ts
  src/main/assets/js/data-layer.ts
  src/main/assets/js/index.ts
  src/main/steps/common/page.njk
  src/main/steps/cookie-banner/template.njk
  src/main/steps/cookies/template.njk
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2258

#2275 Revert "chore(deps-dev): bump @wdio/sauce-service from 7.20.4 to 7.25 (#2263)"
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2275

#2248 NFDIV-2254 Incorrect screen is displayed after withdrawing CO application - v2
  src/main/steps/applicant1/check-your-conditional-order-answers/content.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/template.njk
  src/main/steps/applicant1/withdrawing-your-application/template.njk
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2248

#2264 NFDIV-2405 Welsh-Help with the divorce fee-Applicant2
  src/main/steps/applicant2/help-with-your-fee/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2264

#2268 NFDIV-2298 - Welsh Joint Applicant 1 for review - Check your answers
  src/main/steps/applicant1/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2268

#2285 NFDIV-2482 - Fix XB
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2285
