Repository hmcts/nfdiv-frontend, pull requests merged in 2022-02, with the labels that each got.

#1714 content change clean up
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-pronouncement.njk
  src/test/functional/features/joint-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1714

#1715 Fix issue date and case reference after review
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1715

#1674 NFDIV-1321 - Hub for sole applicant when legal advisor requested clarification
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/document-download/index.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/form.njk
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-clarification.njk
  src/test/functional/features/sole-hub-page.feature
  src/test/steps/IdamUserManager.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1674

#1716 Nfdiv 1546
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-application/template.njk
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/do-you-want-to-apply-financial-order/content.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
  src/test/functional/fixtures/jointApplicant2CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1716

#1725 clean up pages
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/review-the-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1725

#1726 Removing trailing space
  src/main/steps/applicant1/hub-page/joint/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1726

#1724 Run nightly pipeline every 15 minutes
  Jenkinsfile_nightly
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1724

#1728 Clean up fo page
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1728

#1745 Trigger switch to sole as systemUser if app2
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/steps/switch-to-sole-application/post.test.ts
  src/main/steps/switch-to-sole-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1745

#1720 Nfdiv-1589 & Nfdiv-328 Sole hub page - awaiting final order
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/form.njk
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-clarification.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-final-order-or-final-order-overdue.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-final-order-or-final-order-overdue.njk
  src/main/steps/respondent/hub-page/template.njk
  src/main/steps/urls.ts
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1720

#1753 Nfdiv 1324 hub page clarification submitted
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/clarification-submitted.njk
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/clarification-submitted.njk
  src/main/steps/respondent/hub-page/template.njk
  src/test/functional/features/sole-conditional-order.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1753

#1747 provide clarifiation page validation
  src/main/steps/applicant1/provide-information-to-the-court/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1747

#1752 Nfdiv-330 FO do you want to finalise page
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/finalising-your-application/content.ts
  src/main/steps/applicant1/finalising-your-application/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/urls.ts
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1752

#1755 Nfdiv 1665 does your partner have a solicitor page 2
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/do-they-have-a-solicitor/content.ts
  src/main/steps/applicant1/do-they-have-a-solicitor/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/fixtures/completeCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1755

#1748 Ignore 404s
  src/main/modules/appinsights/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1748

#1737 Combine hub page tests
  src/main/app/case/case.ts
  src/test/functional/features/joint-conditional-order.feature
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/sole-conditional-order.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1737

#1746 NFDIV 1657 & NFDIV 1658
  src/main/steps/applicant1/do-you-have-address/content.ts
  src/main/steps/applicant1/do-you-have-address/template.njk
  src/main/steps/applicant1/their-email-address/content.ts
  src/main/steps/applicant1Sequence.ts
  src/test/functional/features/applicant1-sole.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1746

#1766 Nfdiv-1355 financial order overdue page
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/explain-the-delay/content.ts
  src/main/steps/applicant1/explain-the-delay/form.njk
  src/main/steps/applicant1/explain-the-delay/post.test.ts
  src/main/steps/applicant1/explain-the-delay/post.ts
  src/main/steps/applicant1/explain-the-delay/template.njk
  src/main/steps/applicant1/finalising-your-application/post.test.ts
  src/main/steps/applicant1/finalising-your-application/post.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/final-order.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1766

#1775 Service update
  src/main/steps/applicant1/address-private/content.ts
  src/main/steps/applicant1/application-sent-for-review/content.ts
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/apply-for-help-with-fees/content.ts
  src/main/steps/applicant1/check-jurisdiction/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/date-from-certificate/content.ts
  src/main/steps/applicant1/dividing-money-property/content.ts
  src/main/steps/applicant1/do-you-have-your-certificate/content.ts
  src/main/steps/applicant1/do-you-want-to-apply-financial-order/content.ts
  src/main/steps/applicant1/help-with-your-fee/content.ts
  src/main/steps/applicant1/help-with-your-fee/template.njk
  src/main/steps/applicant1/how-do-you-want-to-apply/content.ts
  src/main/steps/applicant1/how-do-you-want-to-apply/template.njk
  src/main/steps/applicant1/how-the-court-will-contact-you/content.ts
  src/main/steps/applicant1/irretrievable-breakdown/content.ts
  src/main/steps/applicant1/pay-and-submit/template.njk
  src/main/steps/applicant1/pay-your-fee/template.njk
  src/main/steps/applicant1/relationship-not-broken/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant1/their-email-address/content.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/help-with-your-fee/content.ts
  src/main/steps/applicant2/needs-to-confirm-joint-application/content.ts
  src/main/steps/applicant2/you-cannot-apply/content.ts
  src/main/steps/applicant2/you-have-not-confirmed-joint-application/content.ts
  src/main/steps/common/common.content.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1775

#1777 clean up
  src/main/steps/applicant1/check-jurisdiction/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-answers/template.njk
  src/main/steps/applicant1/confirm-your-joint-application/content.ts
  src/main/steps/applicant1/confirm-your-joint-application/template.njk
  src/main/steps/applicant1/connection-summary/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-your-application/content.ts
  src/main/steps/applicant1/review-your-joint-application/content.ts
  src/main/steps/applicant2/check-your-joint-application/content.ts
  src/test/functional/features/applicant1-sole.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1777

#1774 Unset app2 solicitor fields 2
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/sole-hub-page.feature
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1774

#1776 Nfdiv 329
  src/main/app/case/case.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/hub.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/final-order-requested.njk
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/template.njk
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1776

#1792 remove superfluous failing scenario
  src/main/app/case/definition.ts
  src/main/steps/applicant1/finalising-your-application/post.test.ts
  src/main/steps/applicant1/finalising-your-application/post.ts
  src/test/functional/features/final-order.feature
  src/test/functional/features/joint-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1792

#1785 update chart
  charts/nfdiv-frontend/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1785

#1786 update session cookie settings
  src/main/modules/session/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1786

#1788 no response page moved to parent dir due to common use.
  src/main/routes.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/no-response-yet/content.ts
  src/main/steps/no-response-yet/get.test.ts
  src/main/steps/no-response-yet/get.ts
  src/main/steps/no-response-yet/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1788

#1782 Nfdiv 1672 & Nfdiv 1757
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/review-the-application/content.ts
  src/main/steps/applicant1/review-the-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1782

#1789 NFDIV-1586
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/hub.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-clarification.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/home/get.ts
  src/test/functional/features/joint-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1789

#1800 NFDIV-1765 sanitize user input
  src/main/steps/applicant1/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-1800
