Repository hmcts/nfdiv-frontend, pull requests merged in 2022-11, with the labels that each got.

#2626 NFDIV-3090 - Prevent AOS being updated after submit
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/respondentSequence.ts
  src/main/steps/url-utils.test.ts
  src/main/steps/url-utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2626

#2643 NFDiv-3127 Refactor template selectors
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2643

#2655 NFDIV-3137 - Add more caching
  src/main/app/auth/user/oidc.test.ts
  src/main/app/auth/user/oidc.ts
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2655

#2592 NFDiv-2967 Update Contact Email Address
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2592

#2663 NFDIV-3143 - Add return to redirect statement
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2663

#2662 small errorHandler refactor to improve readability
  src/main/app/case/answers/possibleAnswers.test.ts
  src/main/app/case/answers/possibleAnswers.ts
  src/main/app/jurisdiction/jurisdictionRemovalHelper.ts
  src/main/modules/error-handler/index.ts
  src/main/modules/webpack-dev/index.ts
  src/main/server.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2662

#2664 NFDIV-3142 - Tidy up templates
  src/main/steps/applicant1/application-sent-for-review/template.njk
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/email-resent/template.njk
  src/main/steps/applicant1/how-you-can-proceed/template.njk
  src/main/steps/applicant1/hub-page/common/court-feedback.njk
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-amended-application.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/clarification-submitted.njk
  src/main/steps/applicant1/provide-information-to-the-court/form.njk
  src/main/steps/applicant1/you-cannot-update-their-email/template.njk
  src/main/steps/common/contact-us/text.njk
  src/main/steps/common/macros/download-link.njk
  src/main/steps/common/macros/page-link.njk
  src/main/steps/common/macros/service-address.njk
  src/main/steps/cookie-banner/template.njk
  src/main/steps/respondent/hub-page/latest-update-content/holding.njk
  src/main/steps/webchat/content.ts
  src/main/steps/webchat/link-to-webchat.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2664

#2673 NFDIV-3149 - Add joint-final-order nightly test
  src/test/functional/features/joint-final-order.feature
  src/test/functional/fixtures/jointFinalOrderCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2673

#2661 NFDIV-2870 - Welsh translation of added error page
  src/main/steps/existing-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2661

#2625 NFDIV-2374: Update hub page when applicant2 does not apply for FO within 14 days
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-joint-final-order.njk
  src/test/functional/features/joint-hub-page-applied-first.feature
  src/test/functional/fixtures/jointApplicant1AppliedFirstCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2625

#2684 NFDiv-2659 and NFDiv-2751 Hub Page After Switching To Sole Intended FO
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/intend-to-switch-to-sole-final-order.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2684

#2676 NFD-2658 new confirm switch to sole FO page
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/how-to-finalise/content.ts
  src/main/steps/applicant1/how-to-finalise/post.test.ts
  src/main/steps/applicant1/how-to-finalise/post.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/how-to-finalise/content.ts
  src/main/steps/applicant2/how-to-finalise/post.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/urls.ts
  src/test/functional/features/joint-final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2676

#2708 Change cron nightly trigger 4am to 6pm
  Jenkinsfile_nightly
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2708

#2699 Add caching for yarn start:docker
  config/docker.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2699

#2675 NFDIV-2297 - Update AOS SOT logic
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2675

#2681 NFDIV-2521 extend session dialog
  src/main/assets/js/session-timeout.ts
  src/main/assets/scss/main.scss
  src/main/assets/scss/timeout-modal.scss
  src/main/steps/applicant1/apply-for-help-with-fees/template.njk
  src/main/steps/applicant1/get-certified-translation/template.njk
  src/main/steps/applicant1/you-cannot-update-their-email/template.njk
  src/main/steps/applicant1/you-need-their-email-address/template.njk
  src/main/steps/applicant1/you-need-your-certificate/template.njk
  src/main/steps/applicant2/needs-to-confirm-joint-application/template.njk
  src/main/steps/applicant2/you-have-not-confirmed-joint-application/template.njk
  src/main/steps/applicant2/your-comments-sent/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/common/timeout-dialog.njk
  src/main/steps/no-response-yet/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2681
