Repository hmcts/nfdiv-frontend, pull requests merged in 2023-07, with the labels that each got.

#2797 NFDIV-3210 - Translation for NFDIV-2801
  src/main/steps/applicant1/enter-your-name/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2797

#3067 Suppress errors when a user accesses documents when not logged in
  package.json
  src/main/modules/document-download/index.ts
  src/main/steps/url-utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3067

#3068 Cut down noise from CSRF errors
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/modules/csrf/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3068

#3078 update yarn audit known issue file
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3078

#3084 see if we can ignore the response code 0 errors
  src/main/modules/document-download/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3084

#3076 use striptags package to remove html tags from string.
  package.json
  src/main/steps/applicant1/check-your-answers/content.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3076

#3085 use the setTimeout plugin for codecept to increase the timeout globally.
  src/test/functional/codecept.conf.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3085

#3090 increase login timeout to 3 minutes to reduce flakiness of test
  src/test/config.ts
  src/test/functional/codecept.conf.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3090

#3094 Lowered number of workers to 4
  package.json
Labels: ns:nfdiv, prd:nfdiv, no-changes, rel:nfdiv-frontend-pr-3094

#3091 add bypassCSP to playwright config to allow waitforfunction to work.
  src/test/config.ts
Labels: ns:nfdiv, prd:nfdiv, no-changes, rel:nfdiv-frontend-pr-3091

#3103 NFDIV-3584 - Improve logging around linking applicants to case
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3103

#3106 Handle errors getting token from IDAM
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3106
