Repository hmcts/nfdiv-frontend, pull requests merged in 2023-09, with the labels that each got.

#2986 NFDiv-3481 Welsh Webchat Support
  src/main/assets/locales/avaya-webchat/cy-gb/locale_en-GB.json
  src/main/assets/locales/avaya-webchat/en-gb/locale_en-GB.json
  src/main/steps/common/common.content.ts
  src/main/steps/webchat/link-to-webchat.njk
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2986

#3186 fix e2e nightly test
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3186

#3116 uncomment overdue sole fo test to complete its journey.
  src/test/functional/features/sole-final-order.feature
Labels: ns:nfdiv, prd:nfdiv, no-changes, rel:nfdiv-frontend-pr-3116

#3140 Fix: Update Respondent FO application received notification
  .nvmrc
  package.json
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/test/functional/features/sole-final-order.feature
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, no-changes, rel:nfdiv-frontend-pr-3140

#3199 remove final order overdue state
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/controller.utils.test.ts
  src/main/app/controller/controller.utils.ts
  src/main/steps/applicant1/changing-to-a-sole-application/content.ts
  src/main/steps/applicant1/finalising-your-application/content.ts
  src/main/steps/applicant1/finalising-your-application/post.test.ts
  src/main/steps/applicant1/finalising-your-application/template.njk
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
  src/test/functional/features/joint-final-order.feature
  src/test/functional/features/sole-final-order.feature
  src/test/functional/fixtures/finalOrderOverdueCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3199, enable_keep_helm

#3211 Make case type configurable
  src/main/app/case/case-api-client.test.ts
  src/main/app/case/case-api-client.ts
  src/main/app/case/case-api.ts
  src/main/app/case/case-type.ts
  src/main/app/case/definition.ts
  src/main/app/document/CaseDocumentManagementClient.ts
  src/main/app/payment/PaymentClient.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3211

#3210 FOO applied hub page update
  package.json
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/respondent/hub-page/content.ts
  src/test/functional/features/joint-final-order.feature
  src/test/functional/features/sole-final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3210

#3229 Remove dateFinalOrderNoLongerEligible check
  src/main/steps/applicant1/hub-page/joint/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3229

#3237 considering the state AwaitingGeneralConsideration for joint applicants.
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3237

#3248 Add logging
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3248
