Repository hmcts/nfdiv-frontend, pull requests merged in 2023-12, with the labels that each got.

#3395 NFDIV-3039: content update
  src/main/steps/applicant1/upload-your-documents/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3395

#3402 update feedback text and style
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3402

#3407 display awaiting aos page for cases in holding but havent submitted aos
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3407
