Repository hmcts/nfdiv-frontend, pull requests merged in 2023-06, with the labels that each got.

#2951 NFDIV-3451: Add check to display the page once
  src/main/app/case/case.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/common/content.utils.test.ts
  src/main/steps/common/content.utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2951

#2979 NFDIV-3294 - Remove use of docstore CDAM flag
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/document/CaseDocumentManagementClient.test.ts
  src/main/app/document/DocumentManagementClient.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/app/document/__mocks__/CaseDocumentManagementClient.ts
  src/main/modules/document-download/index.ts
  src/main/modules/document-download/proxy-list.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2979

#3003 Bump dependency with CVE open to fix it
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3003

#3020 Add side-by-side redis
  infrastructure/main.tf
Labels: ns:nfdiv, prd:nfdiv, add-or-update, rel:nfdiv-frontend-pr-3020

#3021 use redis 6
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  charts/nfdiv-frontend/values.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3021

#3022 remove redis 4 instance
  infrastructure/main.tf
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, destroy, rel:nfdiv-frontend-pr-3022

#3046 Updating to v8 broke the crossbrowser tests
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3046
