Repository hmcts/nfdiv-frontend, pull requests merged in 2023-01, with the labels that each got.

#2786 Add suppression of json5
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2786

#2789 Bump tsconfig-paths as it has updated json5 fixing CVE issue
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2789

#2794 update suppress to fix failing pipeline
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2794

#2796 update suppression for json5 issue
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2796

#2769 NFDIV-3204 - Prevent users visiting certain URLs (V3)
  src/main/routes.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/routeHiding.test.ts
  src/main/steps/routeHiding.ts
  src/main/steps/url-utils.test.ts
  src/main/steps/url-utils.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2769

#2800 Update suppression file to new ID
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2800

#2801 Bump nodejs chart to latest version - old version deprecated
  charts/nfdiv-frontend/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2801

#2803 Bump node js chart to v2.4.13 latest
  charts/nfdiv-frontend/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2803

#2795 NFDIV-3242 Fix CSP blocking PCQ
  src/main/modules/helmet/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2795

#2810 Suppress until later nodejs-healthcheck version is relased to fix this
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2810

#2811 Enable renovate for terraform to get updates automatically
  .github/renovate.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2811
