Repository hmcts/nfdiv-frontend, pull requests merged in 2023-10, with the labels that each got.

#3242 test PR to PR
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/app/payment/PaymentClient.ts
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-3242

#3257 Combines log messages
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3257

#3220 Update functionality to allow joint to switch to sole when case is ov…
  src/main/steps/applicant1/explain-the-delay/post.test.ts
  src/main/steps/applicant1/explain-the-delay/post.ts
  src/main/steps/applicant1/finalising-your-application/post.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  src/test/functional/features/joint-final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3220

#3221 Feature: Add a link for general order on the hub page for joint and s…
  src/main/modules/document-download/proxy-list.ts
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/final-order-complete.njk
  src/main/steps/respondent/hub-page/content.ts
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-3221

#3258 pin specific versions for packages.
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3258

#3262 update allure package for codeceptjs
  package.json
  src/test/cross-browser/codecept.conf.ts
  src/test/functional/codecept.conf.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3262

#3271 update codeceptjs and playwright
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3271

#3272 Fix/next incomplete step save signout
  src/main/steps/index.test.ts
  src/main/steps/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3272

#3321 NFDIV-3751: Retry on 504 status code
  src/main/app/case/case-api-client.test.ts
  src/main/app/case/case-api-client.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3321

#3322 NFDIV-3751: Retry on 502 status code
  src/main/app/case/case-api-client.test.ts
  src/main/app/case/case-api-client.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3322

#3323 update properties volume
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3323

#3310 Test azure playwright
  Jenkinsfile_CNP
  package.json
  src/test/config.ts
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/jurisdiction-can-use-english-or-welsh-courts.feature
  src/test/functional/features/sole-hub-page.feature
  src/test/functional/fixtures/issuedCase.ts
  src/test/steps/common.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-3310
