Repository hmcts/nfdiv-frontend, pull requests merged in 2023-03, with the labels that each got.

#2741 NFDIV-2591 Update name change logic
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/changes-to-your-name/content.ts
  src/main/steps/applicant1/changes-to-your-name/post.test.ts
  src/main/steps/applicant1/changes-to-your-name/post.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/how-did-you-change-your-name/content.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/changes-to-your-name/content.ts
  src/main/steps/applicant2/changes-to-your-name/post.test.ts
  src/main/steps/applicant2/changes-to-your-name/post.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/how-did-you-change-your-name/content.ts
  src/main/steps/applicant2Sequence.ts
  src/main/steps/common/content.utils.test.ts
  src/main/steps/common/content.utils.ts
  src/main/steps/urls.ts
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/fixtures/completeCase.ts
  src/test/functional/fixtures/jointApplicant1AppliedFirstCompleteCase.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
  src/test/functional/fixtures/jointApplicant2CompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2741

#2840 Revert upgrade of sauce-service as it has broken cross browser tests
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2840

#2841 Update all preview URLs for deployments to be the new platform URL
  README.md
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  config/default.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2841

#2857 Add new gov uk payments url to allowed form actions on CSP
  src/main/modules/helmet/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2857

#2858 Fix govpay url for CSP
  src/main/modules/helmet/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2858

#2833 Upgrade Redis client
  config/default.yaml
  package.json
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/modules/health/index.ts
  src/main/modules/session/index.ts
  src/main/routes.ts
  src/main/server.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2833

#2834 NFDiv-3296 Yarn v3 Upgrade
  .gitignore
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-2834
