Repository hmcts/nfdiv-frontend, pull requests merged in 2024-02, with the labels that each got.

#3495 NFDiv-3863 Update Welsh Webchat
  src/main/assets/locales/avaya-webchat/cy-gb/locale_en-GB.json
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us/text.njk
  src/main/steps/webchat/link-to-webchat.njk
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3495

#3506 Revert "NFDiv-3863 Update Welsh Webchat (#3495)"
  src/main/assets/locales/avaya-webchat/cy-gb/locale_en-GB.json
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us/text.njk
  src/main/steps/webchat/link-to-webchat.njk
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3506

#3510 bump for new logo
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3510

#3520 NFDiv-3834 Email link on Joint Application Submission Page
  src/main/steps/accessibility-statement/template.njk
  src/main/steps/applicant1/application-submitted/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3520

#3449 NFDIV-3859: Fix 404 not found error for state LAReview
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3449

#3551 enable autoscaling and set max to 8 pods
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3551

#3557 Mem settings Update Chart.yaml
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3557
