Repository hmcts/nfdiv-frontend, pull requests merged in 2024-07, with the labels that each got.

#3763 Update crossbrowser test script
  package.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3763

#3728 NFDIV-4099 INC5621509 - Case moved into incorrect state at Final Order stage after General Referral
  src/main/app/case/case.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/common/common.content.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-3728

#3772 NFDIV-4184 INC5631092 - Temporary fix to show blank hub-page for pending hearing outcome
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/pending-hearing-outcome.njk
  src/main/steps/applicant1/hub-page/progress-bar.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/pending-hearing-outcome.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/hubTemplates.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/pending-hearing-outcome.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3772

#3727 NFDIV-3974
  src/main/app/case/case.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/app-represented/content.ts
  src/main/steps/applicant1/app-represented/progress-bar.njk
  src/main/steps/applicant1/app-represented/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/app-represented/content.ts
  src/main/steps/applicant2/app-represented/progress-bar.njk
  src/main/steps/applicant2/app-represented/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/app-represented/content.ts
  src/main/steps/respondent/app-represented/progress-bar.njk
  src/main/steps/respondent/app-represented/template.njk
  src/main/steps/respondentSequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-3727

#3780 Fixed functional test report
  .gitignore
  package-lock.json
  package.json
  src/test/functional/codecept.conf.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3780

#3775 NFDIV-4019: Fix issue with service application refused hub page
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3775

#3782 NFDIV-3990 Hub Page for new PendingHearingDate state
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3782

#3801 Crossbrowser tests now generate an HTML report
  package.json
  src/test/cross-browser/codecept.conf.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3801

#3794 NFDIV-4224 fix respondent
  src/main/modules/state-redirect/index.ts
  src/main/steps/respondentSequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3794
