Repository hmcts/nfdiv-frontend, pull requests merged in 2024-12, with the labels that each got.

#4005 NFDIV-4545 Fix reporting for FE Functional Tests
  package.json
  src/test/functional/codecept.conf.ts
  src/test/functional/features/sole-final-order.feature
  src/test/functional/features/sole-hub-page.feature
  src/test/functional/fixtures/issuedCase.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4005

#4007 NFDIV-4559
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, enable_full_functional_tests, rel:nfdiv-frontend-pr-4007

#4003 NFDIV-4520: redirect solicitors to manage case
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4003

#4002 [NFDIV-4337] Redirect based on service type during login
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.aat.template.yaml
  charts/nfdiv-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/case/case-api.test.ts
  src/main/app/case/case-api.ts
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-4002

#4016 NFDIV-4579 fix for dependency on nanoid
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, enable_full_functional_tests, rel:nfdiv-frontend-pr-4016

#3912 NFDIV-4298
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  README.md
  config/custom-environment-variables.yaml
  config/default.yaml
  package-lock.json
  package.json
  src/main/app/auth/user/oidc.test.ts
  src/main/app/controller/PostController.test.ts
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/server.ts
  src/main/steps/applicant1/respond-to-the-courts-feedback/form.njk
  src/main/steps/applicant2/respond-to-the-courts-feedback/form.njk
  src/test/config.ts
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew.bat
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/add-or-update, fortify, enable_fortify_scan, rel:nfdiv-frontend-pr-3912
