Repository hmcts/nfdiv-frontend, pull requests merged in 2024-06, with the labels that each got.

#3707 [NFDIV-3987] Add hub page for new BailiffRefused state with the same content as AwaitingBailiffReferral
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/home/get.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
  src/test/functional/features/sole-hub-page.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3707

#3706 NFDIV-4053 POC to call the payment service first to get the serviceRequestReference before taking the payment
  src/main/app/case/definition.ts
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/app/payment/PaymentModel.test.ts
  src/main/app/payment/PaymentModel.ts
  src/main/app/payment/__mocks__/PaymentClient.ts
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/applicant1/pay-your-fee/post.ts
  src/main/steps/applicant1/payment-callback/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3706

#3742 Add test reports to pipeline
  Jenkinsfile_CNP
  package.json
  src/test/functional/codecept.conf.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3742
