Repository hmcts/nfdiv-frontend, pull requests merged in 2024-08, with the labels that each got.

#3813 NFDIV-4216: Fix issue with cya
  src/main/steps/applicant2/check-your-answers/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3813

#3818 NFDIV-4225 Add new question to respondent online AoS
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/respondent/check-your-answers/content.ts
  src/main/steps/respondent/intend-to-delay/content.ts
  src/main/steps/respondent/intend-to-delay/template.njk
  src/main/steps/respondentSequence.ts
  src/main/steps/routeHiding.ts
  src/main/steps/urls.ts
  src/test/functional/features/respondent.feature
  src/test/functional/fixtures/respondentCompleteCase.ts
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3818

#3830 [NFDIV-4098] Allow respondents to pay by HWF for final orders
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/respondent/apply-for-help-with-final-order-fees/content.ts
  src/main/steps/respondent/apply-for-help-with-final-order-fees/template.njk
  src/main/steps/respondent/have-you-applied-for-help-with-final-order-fees/content.ts
  src/main/steps/respondent/have-you-applied-for-help-with-final-order-fees/post.ts
  src/main/steps/respondent/hub-page/content.ts
  src/main/steps/respondent/hub-page/latest-update-content/final-order-requested.njk
  src/main/steps/respondentSequence.ts
  src/main/steps/routeHiding.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/urls.ts
  src/test/functional/features/sole-final-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3830
