Repository hmcts/nfdiv-frontend, pull requests merged in 2024-10, with the labels that each got.

#3911 [NFDIV-4314] Use payment service requests created by case-api (Part 1)
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/BasePaymentCallbackGetController.ts
  src/main/app/controller/BasePaymentPostController.ts
  src/main/app/controller/PostController.ts
  src/main/steps/applicant1/check-your-answers/post.test.ts
  src/main/steps/applicant1/confirm-your-joint-application/post.test.ts
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/respondent/pay-your-final-order-fee/post.test.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/add-or-update, rel:nfdiv-frontend-pr-3911

#3917 Update Docker setup instructions in ReadMe
  README.md
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3917

#3895 [NFDIV-4314] Use payment service requests created by case-api (Part 2)
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/BasePaymentPostController.ts
  src/main/app/payment/PaymentClient.test.ts
  src/main/app/payment/PaymentClient.ts
  src/main/app/payment/PaymentModel.test.ts
  src/main/app/payment/PaymentModel.ts
  src/main/app/payment/__mocks__/PaymentClient.ts
  src/main/steps/applicant1/pay-your-fee/post.test.ts
  src/main/steps/applicant1/pay-your-fee/post.ts
  src/main/steps/respondent/pay-your-final-order-fee/post.test.ts
  src/main/steps/respondent/pay-your-final-order-fee/post.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/add-or-update, rel:nfdiv-frontend-pr-3895

#3935 NFDIV-4299: Add fortify scans to nightly pipeline
  .gitignore
  Jenkinsfile_nightly
  package.json
  src/test/java/build.gradle
  src/test/java/config/fortify-client.properties
  src/test/java/gradle/wrapper/gradle-wrapper.jar
  src/test/java/gradle/wrapper/gradle-wrapper.properties
  src/test/java/gradlew
  src/test/java/gradlew.bat
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3935, enable_fortify_scan

#3939 NFDIV-4299: Temporary disable fortify scan to fix issues
  Jenkinsfile_nightly
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3939

#3922 NFDIV-4358: Update bailiff service url
  package.json
  src/main/steps/applicant1/how-you-can-proceed/template.njk
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3922

#3943 NFDIV-4438 Update text temporarily for webchat agents busy
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3943

#3947 Revert "NFDIV-4438 Update text temporarily for webchat agents busy"
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3947

#3948 NFDIV-4350: Update readme file
  README.md
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3948

#3959 NFDIV-4430 - Configure workflow to mark PRs stale or closed
  .github/workflows/stale.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3959

#3932 [NFDIV-4296] Set up page for applicant 2 when joint case awaiting payment
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3932

#3963 Nfdiv 4430 front end
  .github/workflows/stale.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3963

#3971 NFDIV-4479 Fix Welsh Webform URL in Common Content
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3971
