Repository hmcts/nfdiv-frontend, pull requests merged in 2024-11, with the labels that each got.

#3984 NFDIV-4495 Add Global Env Var to force Civil mode locally on the FE
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/modules/nunjucks/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3984

#3990 NFDIV-4439 Add functional tests for RFI frontend journey
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-requested-information.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/information-requested-from-partner-or-other.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/information-requested.njk
  src/main/steps/applicant1/hub-page/joint/latest-update-content/responded-to-information-request.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-requested-information.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/information-requested-from-other.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/information-requested.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/responded-to-information-request.njk
  src/main/steps/applicant1/respond-to-the-courts-feedback/content.ts
  src/main/steps/applicant1/respond-to-the-courts-feedback/template.njk
  src/main/steps/applicant1/review-your-response-to-the-courts-feedback/template.njk
  src/main/steps/applicant2/respond-to-the-courts-feedback/content.ts
  src/main/steps/applicant2/respond-to-the-courts-feedback/template.njk
  src/test/functional/features/joint-rfi-response.feature
  src/test/functional/features/sole-rfi-response.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3990

#3903 NFDIV-4177: Update hub page, update layout of progress bar for pre request for information
  src/main/assets/scss/main.scss
  src/main/assets/scss/progress-bar.scss
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/app-represented/content.ts
  src/main/steps/applicant1/app-represented/progress-bar.njk
  src/main/steps/applicant1/app-represented/template.njk
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/progress-bar.njk
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-documents.njk
  src/main/steps/applicant1/hub-page/progressBarLabels.test.ts
  src/main/steps/applicant1/hub-page/progressBarLabels.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-documents.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/app-represented/content.ts
  src/main/steps/applicant2/app-represented/progress-bar.njk
  src/main/steps/applicant2/app-represented/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/hmcts-progress-bar/macro.njk
  src/main/steps/common/hmcts-progress-bar/template.njk
  src/main/steps/common/hubTemplates.ts
  src/main/steps/common/progress-bar.njk
  src/main/steps/respondent/app-represented/content.ts
  src/main/steps/respondent/app-represented/progress-bar.njk
  src/main/steps/respondent/app-represented/template.njk
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/respondent.feature
  src/test/functional/features/sole-conditional-order.feature
  src/test/functional/features/sole-final-order.feature
  src/test/functional/features/update-contact-details.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3903

#3997 [NFDIV-4530] Update nightly functional tests following recent frontend releases
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, nightly, enable_full_functional_tests, rel:nfdiv-frontend-pr-3997

#3978 [NFDIV-3967] Remove deprecated hmcts frontend dependency
  package.json
  src/main/assets/images/icon-progress-tick.svg
  src/main/assets/scss/_ie8.scss
  src/main/assets/scss/main.scss
  src/main/assets/scss/progress-bar.scss
  src/main/modules/nunjucks/index.ts
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant2/app-represented/template.njk
  src/main/steps/respondent/app-represented/template.njk
  webpack.config.js
  webpack/hmctsFrontend.js
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3978
