Repository hmcts/nfdiv-frontend, pull requests merged in 2024-05, with the labels that each got.

#3507 NFDiv-3863 Update Welsh Webchat
  src/main/assets/locales/avaya-webchat/cy-gb/locale_en-GB.json
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us/text.njk
  src/main/steps/webchat/link-to-webchat.njk
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, add-or-update, rel:nfdiv-frontend-pr-3507, aat/add-or-update, prod/no-changes

#3658 Add Exceptions for new vulns
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3658

#3659 NFDIV-4025 Update opening hours
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3659

#3654 Reactivate tests marked as flaky
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/equality.feature
  src/test/functional/features/joint-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3654

#3570 NFDiv-3905 Overseas Solicitor Address - FE
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/enter-solicitor-details/content.ts
  src/main/steps/applicant1/enter-solicitor-details/post.test.ts
  src/main/steps/applicant1/enter-solicitor-details/post.ts
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, add-or-update, enable_keep_helm, rel:nfdiv-frontend-pr-3570

#3690 Revert "Reactivate tests marked as flaky"
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/equality.feature
  src/test/functional/features/joint-conditional-order.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3690
