Repository hmcts/nfdiv-frontend, pull requests merged in 2024-09, with the labels that each got.

#3852 [NFDIV-4302] Hide frontend download links from respondents
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/respondent/hub-page/latest-update-content/awaiting-legal-advisor-referral-or-awaiting-pronouncement.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3852

#3884 NFDIV-4210: Update hub page when respondent represented and international address
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
  src/main/steps/common/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3884

#3880 NFDIV-4206: Add logic for represented respondent and HWF
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/common/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3880

#3878 NFDIV-4203: Update hub page for international address
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/common/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3878

#3875 NFDIV-4198: Add help with fees ref number on hub page
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/applicant1Sequence.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3875

#3873 NFDIV-4201: Add application saved hub page, update submitted page
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-documents.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-documents.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/hubTemplates.ts
  src/main/steps/common/progress-bar.njk
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/respondent.feature
  src/test/functional/features/sole-conditional-order.feature
  src/test/functional/features/sole-final-order.feature
  src/test/functional/features/update-contact-details.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3873

#3898 NFDIV-4252: Update court checks progress bar
  src/main/steps/common/progress-bar.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3898

#3850 NFDIV-4196: Update hub page, update layout of progress bar
  src/main/assets/scss/main.scss
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/app-represented/content.ts
  src/main/steps/applicant1/app-represented/progress-bar.njk
  src/main/steps/applicant1/app-represented/template.njk
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/application-submitted/progress-bar.njk
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/awaiting-documents.njk
  src/main/steps/applicant1/hub-page/progressBarLabels.test.ts
  src/main/steps/applicant1/hub-page/progressBarLabels.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-documents.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/applicant1/hub-page/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/app-represented/content.ts
  src/main/steps/applicant2/app-represented/progress-bar.njk
  src/main/steps/applicant2/app-represented/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/hmcts-progress-bar/_progress-bar.scss
  src/main/steps/common/hmcts-progress-bar/macro.njk
  src/main/steps/common/hmcts-progress-bar/template.njk
  src/main/steps/common/hubTemplates.ts
  src/main/steps/common/progress-bar.njk
  src/main/steps/respondent/app-represented/content.ts
  src/main/steps/respondent/app-represented/progress-bar.njk
  src/main/steps/respondent/app-represented/template.njk
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  src/test/functional/features/joint-hub-page.feature
  src/test/functional/features/respondent.feature
  src/test/functional/features/sole-conditional-order.feature
  src/test/functional/features/sole-final-order.feature
  src/test/functional/features/update-contact-details.feature
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-3850
