Repository hmcts/nfdiv-frontend, pull requests merged in 2024-03, with the labels that each got.

#3519 NFDiv-3850 Dynatrace Tagging
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/modules/nunjucks/index.ts
  src/main/steps/common/page.njk
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-3519

#3579 [NFDIV-3939] Force puppeteer update to fix CI build
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3579

#3594 Fix CI Pipeline
  package.json
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3594
