Repository hmcts/nfdiv-frontend, pull requests merged in 2024-01, with the labels that each got.

#3431 Fix failing functional test due to card payment page changes
  src/test/steps/happy-path.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3431

#3432 Fix frontend login redirect
  src/main/modules/oidc/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3432

#3429 NFDIV-3847: Reset statement of truth on save and sign out
  src/main/steps/respondent/check-your-answers/post.test.ts
  src/main/steps/respondent/check-your-answers/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3429

#3430 NFDIV-3845: Change back button to hyperlink due to submit issue
  src/main/steps/applicant1/changing-to-a-sole-application/form.njk
  src/main/steps/switch-to-sole-application/form.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3430

#3467 NFDIV-3856 - Dockerfile change to yarn v3 and production bug fix (radio button conditionals)
  .dockerignore
  Dockerfile
  package.json
  src/main/assets/js/pdfjs.ts
  webpack/app.js
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-3467

#3473 Upgrade pdfjs-dist to latest
  package.json
  src/main/assets/js/pdfjs.ts
  webpack/app.js
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3473
