Repository hmcts/nfdiv-frontend, pull requests merged in 2025-02, with the labels that each got.

#4042 [NFDIV-4605] Allow contact details updates in submitted states
  src/main/modules/state-redirect/index.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4042

#3988 NFDIV-4356 Front end changes to allow applicant to join case from new invites.
  src/main/app/access-code/AccessCodePostController.test.ts
  src/main/app/access-code/AccessCodePostController.ts
  src/main/app/case/case-api-client.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/steps/applicant1/enter-your-access-code/content.ts
  src/main/steps/applicant1/enter-your-access-code/get.test.ts
  src/main/steps/applicant1/enter-your-access-code/get.ts
  src/main/steps/applicant1/enter-your-access-code/post.ts
  src/main/steps/applicant1/enter-your-access-code/template.njk
  src/main/steps/urls.ts
  src/test/functional/fixtures/jointApplicant1CompleteCase.ts
  src/test/steps/common.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-3988

#4048 [NFDIV-4657] Prevent joint app1 updating application details after sending for review
  src/main/modules/state-redirect/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4048

#4036 [NFDIV-4592] New hub page for AwaitingServicePayment
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-payment.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/common/hubTemplates.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4036

#4041 NFDIV-4539 Show court's reason for RFI on the Citizen's Hub Page and Manage cases for Sols
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/information-requested.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/information-requested.njk
  src/main/steps/applicant1/respond-to-the-courts-feedback/content.ts
  src/main/steps/applicant1/respond-to-the-courts-feedback/template.njk
  src/main/steps/applicant2/respond-to-the-courts-feedback/template.njk
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-frontend-pr-4041

#4070 NFDIV-4680: Add url to redirect for perftest issue
  src/main/modules/state-redirect/index.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4070

#4068 [NFDIV-4635] Remove red text for accessibility
  src/main/assets/scss/main.scss
  src/main/steps/applicant1/confirm-their-name/content.ts
  src/main/steps/applicant1/confirm-their-name/template.njk
  src/main/steps/applicant1/confirm-your-name/content.ts
  src/main/steps/applicant1/confirm-your-name/template.njk
  src/main/steps/applicant2/confirm-your-name/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4068

#4071 [NFDIV-4486] Welsh updates for several pages
  src/main/steps/applicant1/changes-to-your-name/content.ts
  src/main/steps/applicant1/check-phone-number/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/confirm-their-name/content.ts
  src/main/steps/applicant1/confirm-your-name/content.ts
  src/main/steps/applicant2/confirm-your-name/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4071

#4076 Add Welsh for document download links
  src/main/steps/applicant1/hub-page/right-column/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4076

#4018 NFDIV-4533: Change clarification submitted offset to 56 days
  config/default.yaml
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-frontend-pr-4018

#4069 [NFDIV-4636] Move page specific title in front of service name
  src/main/steps/common/page.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4069

#4075 NFDIV-4488: Add Welsh translation for intending to switch to sole content
  src/main/steps/applicant1/hub-page/joint/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4075

#4074 NFDIV-4487: Add Welsh translation for explain the delay content
  src/main/steps/applicant1/explain-the-delay/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4074

#4080 [NFDIV-4712] Update access code post controller to work for /respondent
  src/main/app/access-code/AccessCodePostController.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4080

#4081 [NFDIV-4705] Fix nightly cross browser tests
  src/test/cross-browser/features/happy-path.feature
  src/test/functional/features/homepage.feature
Labels: ns:nfdiv, prd:nfdiv, enable_full_functional_tests, rel:nfdiv-frontend-pr-4081
