Repository hmcts/nfdiv-frontend, pull requests merged in 2025-05, with the labels that each got.

#4159 [NFDIV-4817] Update place of marriage hint text
  package.json
  src/main/steps/applicant1/country-and-place/content.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4159

#4135 NFDIV-4714 Applicant Options flow - Happy path
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/general-applications/deemed-service/deemed-service-application/content.ts
  src/main/steps/applicant1/general-applications/deemed-service/deemed-service-application/template.njk
  src/main/steps/applicant1/general-applications/no-response/evidence-received-application/content.ts
  src/main/steps/applicant1/general-applications/no-response/evidence-received-application/form.njk
  src/main/steps/applicant1/general-applications/no-response/evidence-received-application/template.njk
  src/main/steps/applicant1/general-applications/no-response/have-they-received-represented/content.ts
  src/main/steps/applicant1/general-applications/no-response/have-they-received-represented/template.njk
  src/main/steps/applicant1/general-applications/no-response/have-they-received/content.ts
  src/main/steps/applicant1/general-applications/no-response/have-they-received/form.njk
  src/main/steps/applicant1/general-applications/no-response/have-they-received/template.njk
  src/main/steps/applicant1/general-applications/no-response/options-for-progressing/content.ts
  src/main/steps/applicant1/general-applications/no-response/options-for-progressing/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/deemedServiceApplication.ts
  src/main/steps/error/error.njk
  src/main/steps/noResponseJourneyOptions.ts
  src/main/steps/routeHiding.ts
  src/main/steps/urls.ts
  src/test/functional/features/general-applications-no-response.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4135

#4175 [NFDIV-4855] Remove jitpack
  src/test/java/build.gradle
Labels: ns:nfdiv, prd:nfdiv, fortify, enable_fortify_scan, rel:nfdiv-frontend-pr-4175
