Repository hmcts/nfdiv-frontend, pull requests merged in 2025-09, with the labels that each got.

#4320 [NFDIV-4772] Dispense with service submission and hub pages
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/interim-applications/common/apply-for-hwf/content.ts
  src/main/steps/applicant1/interim-applications/common/help-with-fees/content.ts
  src/main/steps/applicant1/interim-applications/common/hwf-reference-number/content.ts
  src/main/steps/applicant1/interim-applications/service-application-submitted/content.ts
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4320

#4330 NFDIV-4968 - Add missing welsh translations for no-response unhappy path - In person service
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/interim-applications/no-response/no-new-address/content.ts
  src/main/steps/applicant1/interim-applications/no-response/partner-in-person/content.ts
  src/main/steps/applicant1/interim-applications/no-response/process-server/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4330

#4316 NFDIV-4747: Add hub page content for search gov records
  src/main/app/case/definition.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/right-column/template.njk
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-general-application-consideration.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/applicant1/interim-applications/general-application-submitted/content.ts
  src/main/steps/common/hubTemplates.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4316

#4337 NFDIV-4945 - Fix welsh after QA review
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/how-you-want-to-serve/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/service-application/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/why-apply-this-way/content.ts
  src/main/steps/applicant1/interim-applications/service-application-submitted/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4337

#4359 NFDIV-4713: Fix undefined error for search gov records
  src/main/modules/document-download/proxy-list.ts
  src/main/steps/applicant1/interim-applications/general-application-submitted/content.ts
  src/main/steps/common/common.content.ts
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4359

#4365 NFDIV-4713: Add approximate age validation
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-date-of-birth/content.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4365

#4375 NFDIV-4713: Get correct fee code
  config/default.yaml
  src/main/steps/applicant1/interim-applications/dispense-service/da-search/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/final-order-search/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/service-application/content.ts
  src/main/steps/applicant1/interim-applications/pay-your-general-application-fee/content.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4375

#4376 [NFDIV-5065] Hide update contact details when resp is confidential
  src/main/steps/applicant1/interim-applications/alternative-service/service-application/form.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/service-application/form.njk
  src/main/steps/applicant1/interim-applications/deemed-service/service-application/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/searching-online/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/service-application/form.njk
  src/main/steps/applicant1/interim-applications/no-response/process-server/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/general-application/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/search-gov-records-application/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/search-gov-records-application/post.test.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/search-gov-records-application/post.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/search-gov-records-application/template.njk
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4376

#4381 Fix failing nightly test
  src/test/functional/features/form-failures.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4381

#4383 [NFDIV-5064] Aos submission in awaiting documents
  src/main/app/document/DocumentManagementConstants.test.ts
  src/main/app/document/DocumentManagementConstants.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/general-application/form.njk
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4383

#4324 NFDIV-4996: Add Welsh translation for search gov records
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/general-application/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional-addresses/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-date-of-birth/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-name/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-national-insurance/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/which-departments/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/why-gov-records/content.ts
  src/main/steps/common/common.content.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4324

#4389 [NFDIV-5065] Reset interim application answers when application type changes
  src/main/app/case/definition.ts
  src/main/steps/applicant1/interim-applications/alternative-service/interruption/post.test.ts
  src/main/steps/applicant1/interim-applications/alternative-service/interruption/post.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/service-application/post.test.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/service-application/post.ts
  src/main/steps/applicant1/interim-applications/common/start-interim-application/post.ts
  src/main/steps/applicant1/interim-applications/deemed-service/interruption/post.test.ts
  src/main/steps/applicant1/interim-applications/deemed-service/interruption/post.ts
  src/main/steps/applicant1/interim-applications/dispense-service/service-application/post.test.ts
  src/main/steps/applicant1/interim-applications/dispense-service/service-application/post.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/general-application/post.test.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/general-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4389

#4328 NFDIV-4869 Welsh - Options Flow - Happy Path and Deemed Service
  src/main/steps/applicant1/interim-applications/common/help-with-fees/content.ts
  src/main/steps/applicant1/interim-applications/common/hwf-reference-number/content.ts
  src/main/steps/applicant1/interim-applications/common/want-upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/deemed-service/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/deemed-service/service-application/content.ts
  src/main/steps/applicant1/interim-applications/deemed-service/upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/deemed-service/want-upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/no-response/evidence-received-application/content.ts
  src/main/steps/applicant1/interim-applications/no-response/have-they-received/content.ts
  src/main/steps/applicant1/interim-applications/no-response/options-for-progressing/content.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4328

#4333 NFDIV-4947 Welsh - Dispense with service
  src/main/steps/applicant1/enter-their-address/content.ts
  src/main/steps/applicant1/enter-your-address/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/aware-partner-address/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/child-maintenance/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/children-contact/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/children-family/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/da-search/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/da-search/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/da-search/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/email-description/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/email/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/employment-contact/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/employment-details/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/final-order-search/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/friends-or-relatives/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/last-address/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/last-contact-children/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/last-date/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/last-seen/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/other-enquiries/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/partner-new-address/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/phone-description/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/phone-number/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/phone-number/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/searching-online-results/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/searching-online/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/service-application/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/tracing-agent-results/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/tracing-agent/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/tracing-online-results/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/tracing-online/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/when-contact-children/content.ts
  src/main/steps/applicant1/interim-applications/service-application-submitted/content.ts
  src/main/steps/dispenseServiceApplicationSequence.ts
  yarn-audit-known-issues
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4333

#4390 NFDIV-5062 - Show options flow link obly in AosOverdue state. Also hub page for Issued to Bailiff state
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-due.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4390

#4392 Remove case-api feature branch config
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4392
