Repository hmcts/nfdiv-frontend, pull requests merged in 2025-03, with the labels that each got.

#4073 NFDIV-4534: Add new hub content for state aos drafted
  src/main/app/case/case.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-frontend-pr-4073

#4099 [NFDIV-4741] Update save and sign out text for R&D
  src/main/steps/save-sign-out/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4099

#4077 NFDIV-4490:Add Welsh translation
  src/main/steps/applicant1/dividing-money-property/content.ts
  src/main/steps/applicant2/dividing-money-property/content.ts
  src/main/steps/applicant2/you-have-not-confirmed-joint-application/content.ts
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-frontend-pr-4077

#4116 [NFDIV-4709] Use OCI node base chart
  charts/nfdiv-frontend/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4116

#4119 [NFDIV-4709] Update idam chart to OCI
  charts/nfdiv-frontend/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4119

#4082 [NFDIV-4711] Allow both applicants to accept case invites when already linked to a case
  src/main/app/controller/AppRequest.ts
  src/main/modules/oidc/index.ts
  src/main/steps/existing-application/content.ts
  src/main/steps/existing-application/get.ts
  src/main/steps/existing-application/post.test.ts
  src/main/steps/existing-application/post.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4082
