Repository hmcts/nfdiv-frontend, pull requests merged in 2025-04, with the labels that each got.

#4057 NFDIV-4344: Add logic to prevent submission with missing required fields
  src/main/steps/applicant1/check-your-conditional-order-answers/post.test.ts
  src/main/steps/applicant1/check-your-conditional-order-answers/post.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4057

#4136 [NFDIV-4756] Update page title and radio button order on intend to delay page
  src/main/steps/respondent/intend-to-delay/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4136

#4131 NFDIV-4778: Change logic to get fee from fee order if present
  config/default.yaml
  src/main/app/fees/service/get-fee.ts
  src/main/steps/applicant1/pay-and-submit/content.ts
  src/main/steps/applicant1/pay-your-fee/content.ts
  src/main/steps/respondent/pay-your-final-order-fee/content.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4131

#4146 [NFDIV-4676] Fix functional tests in local dev
  src/main/modules/properties-volume/index.ts
  src/test/config.ts
  src/test/functional/features/homepage.feature
Labels: ns:nfdiv, prd:nfdiv, nightly, enable_full_functional_tests, aat/add-or-update, prod/no-changes, fortify, enable_fortify_scan, rel:nfdiv-frontend-pr-4146

#4152 NFDIV-4805 Certain lines should not be displayed on hub pages when respondent identified as overseas
  src/main/steps/applicant1/application-submitted/template.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/aos-awaiting-or-drafted.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4152
