Repository hmcts/nfdiv-frontend, pull requests merged in 2025-01, with the labels that each got.

#4004 NFDIV-4011
  Jenkinsfile_CNP
  charts/nfdiv-frontend/Chart.yaml
  charts/nfdiv-frontend/values.preview.template.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.test.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/Form.ts
  src/main/steps/applicant1/address-private/content.ts
  src/main/steps/applicant1/address-private/post.test.ts
  src/main/steps/applicant1/address-private/post.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/applicant2/address-private/content.ts
  src/main/steps/applicant2/address-private/post.test.ts
  src/main/steps/applicant2/address-private/post.ts
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/index.test.ts
  src/main/steps/respondent/address-private/post.ts
  tslint.json
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:nfdiv-frontend-pr-4004

#4026 [NFDIV-4606] Hub page for AwaitingHWFEvidence
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/home/get.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/add-or-update

#4027 [NFDIV-4614] Add missing refuge question to functionals
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
Labels: ns:nfdiv, prd:nfdiv, enable_full_functional_tests

#3993 [NFDIV-4433] Allow card payments after HWF refused
  src/main/app/case/definition.ts
  src/main/app/controller/BasePaymentCallbackGetController.ts
  src/main/app/controller/BasePaymentPostController.ts
  src/main/modules/state-redirect/index.ts
  src/main/steps/applicant1/application-submitted/content.ts
  src/main/steps/applicant1/hub-page/joint/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/pay-your-fee/post.ts
  src/main/steps/applicant1/payment-callback/get.ts
  src/main/steps/applicant2/awaiting-response-to-hwf-decision/content.ts
  src/main/steps/applicant2/awaiting-response-to-hwf-decision/template.njk
  src/main/steps/applicant2Sequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/pay-your-final-order-fee/post.ts
  src/main/steps/respondent/payment-callback/get.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes

#4035 NFDIV-4625: Fix issue with not submitted AoS
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/holding.njk
  src/test/functional/fixtures/respondentCompleteCase.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4035
