Repository hmcts/nfdiv-frontend, pull requests merged in 2025-08, with the labels that each got.

#4232 NFDIV-4750 - Alternative Service 2, 3 & 4
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.ts
  src/main/steps/alternativeServiceApplicationSequence.test.ts
  src/main/steps/alternativeServiceApplicationSequence.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-application-documents.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-payment.njk
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/post.ts
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/explain-serve-documents/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/explain-serve-documents/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/explain-serve-documents/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/how-you-want-to-serve/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/how-you-want-to-serve/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/how-you-want-to-serve/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/sending-papers-to-your-partner/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/sending-papers-to-your-partner/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/sending-papers-to-your-partner/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/upload-evidence/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/want-upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/want-upload-evidence/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/why-apply-this-way/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/why-apply-this-way/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/why-apply-this-way/template.njk
  src/main/steps/applicant1/interim-applications/common/hwf-reference-number/content.ts
  src/main/steps/applicant1/interim-applications/common/want-upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/service-application-submitted/content.ts
  src/main/steps/applicant1/interim-applications/service-application-submitted/template.njk
  src/main/steps/urls.ts
  src/test/functional/features/interim-applications-alternative.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4232

#4231 NFDIV-4749 Alternative Service 1 changes
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation.ts
  src/main/steps/alternativeServiceApplicationSequence.test.ts
  src/main/steps/alternativeServiceApplicationSequence.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-application-documents.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/awaiting-service-payment.njk
  src/main/steps/applicant1/interim-applications/alternative-service/apply-for-hwf/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/apply-for-hwf/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/post.ts
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/explain-serve-documents/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/explain-serve-documents/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/explain-serve-documents/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/help-with-fees/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/help-with-fees/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/how-you-want-to-serve/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/how-you-want-to-serve/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/how-you-want-to-serve/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/hwf-reference-number-input/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/hwf-reference-number-input/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/hwf-reference-number/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/hwf-reference-number/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/interruption/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/interruption/post.test.ts
  src/main/steps/applicant1/interim-applications/alternative-service/interruption/post.ts
  src/main/steps/applicant1/interim-applications/alternative-service/interruption/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/sending-papers-to-your-partner/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/sending-papers-to-your-partner/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/sending-papers-to-your-partner/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/service-application/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/upload-evidence/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/want-upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/want-upload-evidence/template.njk
  src/main/steps/applicant1/interim-applications/alternative-service/why-apply-this-way/content.ts
  src/main/steps/applicant1/interim-applications/alternative-service/why-apply-this-way/form.njk
  src/main/steps/applicant1/interim-applications/alternative-service/why-apply-this-way/template.njk
  src/main/steps/applicant1/interim-applications/common/apply-for-hwf/content.ts
  src/main/steps/applicant1/interim-applications/common/help-with-fees/content.ts
  src/main/steps/applicant1/interim-applications/common/hwf-reference-number/content.ts
  src/main/steps/applicant1/interim-applications/common/want-upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/service-application-submitted/content.ts
  src/main/steps/applicant1/interim-applications/service-application-submitted/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/urls.ts
  src/test/functional/features/interim-applications-alternative.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4231

#4296 NFDIV-4955 Tidy Up
  package.json
  src/main/steps/common/contact-us/text.njk
  src/main/steps/webchat/template.njk
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4296

#4285 NFDIV-4744: Search Gov Records Part 2
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/applicant1/interim-applications/common/check-answers/template.njk
  src/main/steps/applicant1/interim-applications/no-response/check-your-answers/post.ts
  src/main/steps/applicant1/interim-applications/no-response/details-updated/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/apply-for-hwf/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/apply-for-hwf/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/check-answers/post.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/check-answers/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/help-with-fees/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/help-with-fees/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/hwf-reference-number-input/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/hwf-reference-number-input/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/hwf-reference-number/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/hwf-reference-number/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional-addresses/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional-addresses/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional-addresses/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address-additional/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-address/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-date-of-birth/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-date-of-birth/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-date-of-birth/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-name/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-name/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-name/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-national-insurance/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-national-insurance/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/partner-national-insurance/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/which-departments/content.ts
  src/main/steps/applicant1/interim-applications/search-gov-records/which-departments/form.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/which-departments/template.njk
  src/main/steps/applicant1/interim-applications/search-gov-records/why-gov-records/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/noResponseJourneySequence.ts
  src/main/steps/searchGovRecordsApplicationSequence.test.ts
  src/main/steps/searchGovRecordsApplicationSequence.ts
  src/main/steps/searchGovRecordsJourneySequence.test.ts
  src/main/steps/searchGovRecordsJourneySequence.ts
  src/main/steps/urls.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4285

#4317 NFDIV-4767 Dispense with service 5
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/steps/applicant1/interim-applications/dispense-service/child-maintenance/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/child-maintenance/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/child-maintenance/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/children-contact/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/children-contact/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/children-contact/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/children-family/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/children-family/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/children-family/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/employment-details/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/employment-details/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/employment-details/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/friends-or-relatives/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/friends-or-relatives/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/friends-or-relatives/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/last-contact-children/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/last-contact-children/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/last-contact-children/template.njk
  src/main/steps/applicant1/interim-applications/dispense-service/when-contact-children/content.ts
  src/main/steps/applicant1/interim-applications/dispense-service/when-contact-children/form.njk
  src/main/steps/applicant1/interim-applications/dispense-service/when-contact-children/template.njk
  src/main/steps/dispenseServiceApplicationSequence.test.ts
  src/main/steps/dispenseServiceApplicationSequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/interim-applications-dispense.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4317

#4274 NFDIV-4849 Hub page changes when service app is refused
  src/main/app/case/definition.ts
  src/main/modules/document-download/proxy-list.ts
  src/main/steps/applicant1/hub-page/right-column/content.ts
  src/main/steps/applicant1/hub-page/sole/content.ts
  src/main/steps/applicant1/hub-page/sole/latest-update-content/service-admin-refusal-or-bailiff-refused-or-alternative-service-granted.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/common/hubTemplates.ts
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-4274

#4289 NFDIV-4940 - Hub page for WelshTranslatiomReview and WelshTranslationRequested state
  src/main/steps/applicant1/hub-page/content.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/joint/jointTemplateSelector.ts
  src/main/steps/applicant1/hub-page/joint/latest-update-content/welsh-translation-requested-or-review.njk
  src/main/steps/applicant1/hub-page/sole/latest-update-content/welsh-translation-requested-or-review.njk
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.test.ts
  src/main/steps/applicant1/hub-page/sole/soleTemplateSelector.ts
  src/main/steps/common/hubTemplates.ts
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/hub-page/latest-update-content/welsh-translation-requested-or-review.njk
  src/main/steps/respondent/hub-page/respondentTemplateSelector.test.ts
  src/main/steps/respondent/hub-page/respondentTemplateSelector.ts
  src/main/steps/state-sequence.test.ts
  src/main/steps/state-sequence.ts
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-frontend-pr-4289
