Repository hmcts/nfdiv-frontend, pull requests merged in 2025-07, with the labels that each got.

#4227 [NFDIV-4904] Redirect to hub when AoS is overdue and response not started
  src/main/steps/home/get.test.ts
  src/main/steps/home/get.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4227

#4233 NFDIV-4752 - Alternative Service 4
  src/main/steps/alternativeServiceApplicationSequence.test.ts
  src/main/steps/alternativeServiceApplicationSequence.ts
  src/main/steps/applicant1/interim-applications/alternative-service/check-answers/post.ts
  src/test/functional/features/interim-applications-alternative.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4233

#4237 NFDIV-4786: Bailiff part 6
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/are-there-dangerous-animals/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/check-answers/post.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/check-answers/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-have-mental-health-issues/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-have-mental-health-issues/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-hold-firearms-license/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-hold-firearms-license/template.njk
  src/main/steps/bailiffServiceApplicationSequence.test.ts
  src/main/steps/bailiffServiceApplicationSequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/interim-applications-bailiff.feature
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4237

#4249 Update dependencies for on-headers CVE
  package-lock.json
  package.json
  src/test/functional/features/applicant1-joint.feature
  src/test/functional/features/applicant1-sole.feature
  src/test/functional/features/applicant2.feature
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4249

#4254 NFDIV-4960 - Update dependencies version
  src/test/functional/features/respondent.feature
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4254

#4228 [NFDIV-4784] Bailiff service parts 4 and 5
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/able-to-upload-partner-photo/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/able-to-upload-partner-photo/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/are-there-dangerous-animals/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/are-there-dangerous-animals/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/check-answers/post.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/check-answers/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-have-a-vehicle/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-have-a-vehicle/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-have-mental-health-issues/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-have-mental-health-issues/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-hold-firearms-license/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/does-partner-hold-firearms-license/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/has-partner-been-violent/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/has-partner-been-violent/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/has-partner-made-threats/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/has-partner-made-threats/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/have-police-been-involved/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/have-police-been-involved/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/have-social-services-been-involved/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/have-social-services-been-involved/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/partner-vehicle-details/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/partner-vehicle-details/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/upload-partner-photo/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/upload-partner-photo/template.njk
  src/main/steps/applicant1/interim-applications/bailiff-service/when-is-best-to-serve/content.ts
  src/main/steps/applicant1/interim-applications/bailiff-service/when-is-best-to-serve/template.njk
  src/main/steps/applicant1/interim-applications/common/upload-evidence/content.ts
  src/main/steps/applicant1/interim-applications/common/upload-evidence/template.njk
  src/main/steps/bailiffServiceApplicationSequence.test.ts
  src/main/steps/bailiffServiceApplicationSequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/interim-applications-bailiff.feature
Labels: ns:nfdiv, prd:nfdiv, enable_keep_helm, rel:nfdiv-frontend-pr-4228

#4240 [NFDIV-4929] Add new HWF guidance text
  src/main/steps/applicant1/apply-for-help-with-fees/content.ts
  src/main/steps/applicant1/apply-for-help-with-fees/template.njk
  src/main/steps/applicant1/have-you-applied-for-help-with-fees/content.ts
  src/main/steps/applicant1/have-you-applied-for-help-with-fees/template.njk
  src/main/steps/applicant2/have-you-applied-for-help-with-fees/template.njk
Labels: ns:nfdiv, prd:nfdiv, stale, rel:nfdiv-frontend-pr-4240

#4244 NFDIV-4816: Joint journey to confirm marriage cert names
  package.json
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/changes-to-your-name/content.ts
  src/main/steps/applicant1/check-your-answers/content.ts
  src/main/steps/applicant1/check-your-name/content.ts
  src/main/steps/applicant1/upload-your-documents/content.ts
  src/main/steps/applicant1/upload-your-documents/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/applicant2/changes-to-your-name/content.ts
  src/main/steps/applicant2/changes-to-your-name/template.njk
  src/main/steps/applicant2/check-your-answers/content.ts
  src/main/steps/applicant2/check-your-name/content.ts
  src/main/steps/applicant2/check-your-name/template.njk
  src/main/steps/applicant2/enter-your-name/content.ts
  src/main/steps/applicant2/enter-your-name/post.ts
  src/main/steps/applicant2/enter-your-name/template.njk
  src/main/steps/applicant2/your-name-on-certificate/content.ts
  src/main/steps/applicant2/your-name-on-certificate/template.njk
  src/main/steps/applicant2Sequence.ts
  src/test/functional/features/applicant2.feature
  src/test/functional/features/form-failures.feature
  src/test/functional/fixtures/jointApplicant2CompleteCase.ts
  yarn.lock
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4244

#4180 NFDIV-4732: Add update email and postal address logic
  Jenkinsfile_CNP
  charts/nfdiv-frontend/values.preview.template.yaml
  config/default.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/steps/applicant1/interim-applications/common/check-answers/content.ts
  src/main/steps/applicant1/interim-applications/common/check-answers/template.njk
  src/main/steps/applicant1/interim-applications/no-response/check-your-answers/content.ts
  src/main/steps/applicant1/interim-applications/no-response/check-your-answers/form.njk
  src/main/steps/applicant1/interim-applications/no-response/check-your-answers/post.test.ts
  src/main/steps/applicant1/interim-applications/no-response/check-your-answers/post.ts
  src/main/steps/applicant1/interim-applications/no-response/check-your-answers/template.njk
  src/main/steps/applicant1/interim-applications/no-response/details-updated/content.ts
  src/main/steps/applicant1/interim-applications/no-response/details-updated/template.njk
  src/main/steps/applicant1/interim-applications/no-response/have-they-received/content.ts
  src/main/steps/applicant1/interim-applications/no-response/new-email-address/content.ts
  src/main/steps/applicant1/interim-applications/no-response/new-email-address/form.njk
  src/main/steps/applicant1/interim-applications/no-response/new-email-address/template.njk
  src/main/steps/applicant1/interim-applications/no-response/new-postal-address/content.ts
  src/main/steps/applicant1/interim-applications/no-response/new-postal-address/post.test.ts
  src/main/steps/applicant1/interim-applications/no-response/new-postal-address/post.ts
  src/main/steps/applicant1/interim-applications/no-response/new-postal-address/template.njk
  src/main/steps/applicant1/interim-applications/no-response/new-postal-and-email/content.ts
  src/main/steps/applicant1/interim-applications/no-response/new-postal-and-email/form.njk
  src/main/steps/applicant1/interim-applications/no-response/new-postal-and-email/template.njk
  src/main/steps/applicant1/interim-applications/no-response/provide-new-email-address/content.ts
  src/main/steps/applicant1/interim-applications/no-response/provide-new-email-address/form.njk
  src/main/steps/applicant1/interim-applications/no-response/provide-new-email-address/template.njk
  src/main/steps/applicant1Sequence.ts
  src/main/steps/deemedServiceApplicationSequence.test.ts
  src/main/steps/noResponseJourneySequence.test.ts
  src/main/steps/noResponseJourneySequence.ts
  src/main/steps/urls.ts
  src/test/functional/features/interim-applications-deemed.feature
  src/test/functional/features/interim-applications-no-response.feature
  src/test/steps/common.ts
Labels: ns:nfdiv, prd:nfdiv, aat/add-or-update, prod/no-changes, rel:nfdiv-frontend-pr-4180

#4280 [NFDIV-4949] Make cookie preferences secure
  src/main/assets/js/cookie.ts
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-frontend-pr-4280
